### PR TITLE
fix crash when resizing tiled scratchpad windows

### LINKED ISSUE #6693: Segfault in cmd_resize
### Please fill out the following:
- **Sway Version:**
   `-sway version 1.6-a23cdbbe (Nov 23 2021, branch 'master')`

- **Debug Log:**
Unfortunately do not have debug log.

- **Configuration File:**
The relevant command, as of my knowledge:
```
for_window [app_id="qalculate-gtk"] move to scratchpad
bindsym $mod+c exec pidof qalculate-gtk || qalculate-gtk ; [app_id="qalculate-gtk"] scratchpad show, resize set 1440 810, move position center
```

- **Stack Trace:**
```
* thread #1, name = 'sway', stop reason = signal SIGSEGV
  * frame #0: 0x000055d49fe66077 sway`cmd_resize(argc=<unavailable>, argv=<unavailable>) at resize.c:291:51
    frame #1: 0x000055d49fe36310 sway`execute_command(_exec=<unavailable>, seat=0x000055d4a22f6e00, con=0x0000000000000000) at commands.c:305:31
    frame #2: 0x000055d49fe596c6 sway`seat_execute_command(seat=0x000055d4a22f6e00, binding=0x000055d4a303f900) at bind.c:631:21
    frame #3: 0x000055d49fe4aa94 sway`handle_key_event(keyboard=0x000055d4a2c71970, event=0x00007ffe083f18f0) at keyboard.c:491:3
    frame #4: 0x00007fc36d4a9f9e libwlroots.so.10`wlr_signal_emit_safe(signal=0x000055d4a2fc6538, data=0x00007ffe083f18f0) at signal.c:29:3
    frame #5: 0x00007fc36d48b975 libwlroots.so.10`wlr_keyboard_notify_key(keyboard=0x000055d4a2fc6430, event=0x00007ffe083f18f0) at wlr_keyboard.c:96:2
    frame #6: 0x00007fc36d4a9f9e libwlroots.so.10`wlr_signal_emit_safe(signal=0x000055d4a24508e8, data=0x00007ffe083f18f0) at signal.c:29:3
    frame #7: 0x00007fc36d48b975 libwlroots.so.10`wlr_keyboard_notify_key(keyboard=0x000055d4a24507e0, event=0x00007ffe083f18f0) at wlr_keyboard.c:96:2
    frame #8: 0x00007fc36d469986 libwlroots.so.10`handle_libinput_readable(fd=<unavailable>, mask=<unavailable>, _backend=<unavailable>) at keyboard.c:82:2
    frame #9: 0x00007fc36d50104a libwayland-server.so.0`wl_event_loop_dispatch + 202
    frame #10: 0x00007fc36d4febc7 libwayland-server.so.0`wl_display_run + 39
    frame #11: 0x000055d49fe2fa03 sway`main [inlined] server_run(server=<unavailable>) at server.c:297:2
    frame #12: 0x000055d49fe2f9d4 sway`main(argc=<unavailable>, argv=<unavailable>) at main.c:428:2
    frame #13: 0x00007fc36d1fbb25 libc.so.6`__libc_start_main + 213
    frame #14: 0x000055d49fe2fdce sway`_start + 46
(lldb) up
frame #1: 0x000055d49fe36310 sway`execute_command(_exec=<unavailable>, seat=0x000055d4a22f6e00, con=0x0000000000000000) at commands.c:305:31
   302 				for (int i = 0; i < containers->length; ++i) {
   303 					struct sway_container *container = containers->items[i];
   304 					set_config_node(&container->node, true);
-> 305 					struct cmd_results *res = handler->handle(argc-1, argv+1);
   306 					if (res->status == CMD_SUCCESS) {
   307 						free_cmd_results(res);
   308 					} else {
(lldb) down
frame #0: 0x000055d49fe66077 sway`cmd_resize(argc=<unavailable>, argv=<unavailable>) at resize.c:291:51
   288 				if (parent) {
   289 					width->amount = parent->pending.width * width->amount / 100;
   290 				} else {
-> 291 					width->amount = con->pending.workspace->width * width->amount / 100;
   292 				}
   293 				width->unit = MOVEMENT_UNIT_PX;
   294 			}
```

- **Description:**
This has happened a few times now, but very random. On $mod-c I have calculator app showing floating, $mod-c again to hide it. Normally works perfectly fine, but some times, it crashes just after disappearing. Now running with sway-git-aur, so managed to get useful stacktrace.
Have not had opportunity to try to reproduce it.

### PR DESCRIPTION
**Pull request by bretello**
Splitting and then hiding a scratchpad container results in a segfault.

fixes #6693

### CODE REVIEW

**Comment by bretello** [comment]
This crash can be reproduced with the config/script mentioned in https://github.com/swaywm/sway/issues/6693#issuecomment-1638982111

**Comment by rpigott** [comment]
It would prolly make sense to check container_is_scratchpad_hidden_or_child at the beginning of container_resize_tiled.

File: sway/commands/resize.c [hunk 1]
```diff
@@ -292,6 +292,11 @@ static struct cmd_results *resize_adjust_tiled(uint32_t axis,
  */
 static struct cmd_results *resize_set_tiled(struct sway_container *con,
 		struct movement_amount *width, struct movement_amount *height) {
+	if (container_is_scratchpad_hidden_or_child(con)) {
+		return cmd_results_new(CMD_FAILURE,
+			"Cannot resize a hidden scratchpad or child container");
+	  }
```
Comment (emersion) [inline sway/commands/resize.c:298]: Style: 3the codebase uses tabs, but this patch uses mixed spaces and tabs.

Comment (bretello) [reply sway/commands/resize.c]: Hi @emersion,
thanks, this slipped by. Fixed in the last force-push.

**Review by emersion — APPROVED** [review]
LGTM, but I'd like @rpigott to check as well :)

File: sway/commands/resize.c [hunk 2]
```diff
@@ -292,6 +292,10 @@ static struct cmd_results *resize_adjust_tiled(uint32_t axis,
  */
 static struct cmd_results *resize_set_tiled(struct sway_container *con,
 		struct movement_amount *width, struct movement_amount *height) {
+	if (container_is_scratchpad_hidden_or_child(con)) {
```
Comment (rpigott) [inline sway/commands/resize.c:295]: Refusing in `resize_set_tiled` won't handle the grow/shrink resize incantations. E.g. try growing a scratchpad hidden split container perpendicular to the parent layout and you can still repro the crash.

<details><summary>bt</summary>

```
#0  0x00005555555d8c4d in list_find (list=0x0, item=0x555555a240c0) at ../common/list.c:71
#1  0x00005555555c7fc8 in container_sibling_index (child=0x555555a240c0) at ../sway/tree/container.c:1386
#2  0x00005555555b2e1a in container_find_resize_parent (con=0x555555a240c0, axis=12) at ../sway/commands/resize.c:54
#3  0x00005555555b2eac in container_resize_tiled (con=0x555555a1dfe0, axis=12, amount=10) at ../sway/commands/resize.c:72
#4  0x00005555555b39d7 in resize_adjust_tiled (axis=12, amount=0x7fffffffd690) at ../sway/commands/resize.c:282
#5  0x00005555555b4951 in cmd_resize_adjust (argc=0, argv=0x555555a92730, multiplier=1) at ../sway/commands/resize.c:556
#6  0x00005555555b4a92 in cmd_resize (argc=3, argv=0x555555a92718) at ../sway/commands/resize.c:579
#7  0x000055555556c481 in execute_command (_exec=0x5555557384e0 "[con_mark=test] resize grow width 10px", seat=0x555555713710, con=0x0) at ../sway/commands.c:309
#8  0x0000555555578f41 in ipc_client_handle_command (client=0x555555a22180, payload_length=38, payload_type=IPC_COMMAND) at ../sway/ipc-server.c:651
#9  0x0000555555577a9f in ipc_client_handle_readable (client_fd=56, mask=1, data=0x555555a22180) at ../sway/ipc-server.c:262
#10 0x00007ffff7805ae2 in wl_event_loop_dispatch (loop=0x555555612050, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1027
#11 0x00007ffff78062d7 in wl_display_run (display=0x555555611f60) at ../wayland-1.22.0/src/wayland-server.c:1493
#12 0x000055555557cbac in server_run (server=0x555555601b40 <server>) at ../sway/server.c:337
#13 0x000055555557bb67 in main (argc=3, argv=0x7fffffffde78) at ../sway/main.c:415
```
</details>

Refusing in `container_resize_tiled` as suggested effectively removes all broken (and working) cases of resize with scratchpad hidden split containers, but I'm not sure it's a feature we care to keep. Resize of normal scratchpad windows will still be handled as part of the floating case, as there are otherwise no tiled containers in the scratchpad.

**Review by rpigott — CHANGES_REQUESTED** [review]

File: sway/commands/resize.c (hunk 2 above)
Comment (bretello) [reply sway/commands/resize.c:304]: Hi @rpigott, thanks for the feedback. I updated the patch.

I'm unsure on what `cmd_status` to use (`CMD_FAILURE` vs `CMD_INVALID`)

Comment (rpigott) [reply sway/commands/resize.c:304]: When the request is not serviceable or it doesn't make sense with the layout, please use CMD_FAILURE. CMD_INVALID is for when we don't understand what is requested.

**Review by rpigott — APPROVED** [review]
LGTM, thanks!

**Comment by rpigott** [comment]
Ehm, can you maybe rebase this so it can be merged? I dunno what github's problem with it is.

**Comment by bretello** [comment]
@rpigott Done. Thanks!
