### PR TITLE
xkb_switch_layout: fix relative layout switches

### LINKED ISSUE #6011: Cycling through layouts doesn't work
**Sway Version:** 1.5.1

**Debug Log:**
https://pbox.ca/4064245

**Relevant config:** 
```
input type:keyboard {
     xkb_layout us,us(intl)
}
```

**Steps to reproduce:**
Set two keyboard layouts under xkb_layout. Either with a bindsym or through swaymsg, run `input type:keyboard xkb_switch_layout next`. Specifying an index (ie, 0 or 1) rather than `next` or `prev` is able to switch the layout just fine, but the keyboard layout does not change if `next` or `prev` is used.

### PR DESCRIPTION
**Pull request by vitek**
First calculate absolute layout indexes and then apply

Fixes #6011

### CODE REVIEW

File: sway/commands/input/xkb_switch_layout.c [hunk 1]
```diff
@@ -67,6 +73,9 @@ struct cmd_results *input_cmd_xkb_switch_layout(int argc, char **argv) {
 		relative = 0;
 	}
 
+	struct wl_list actions;
+	wl_list_init(&actions);
```
Comment (emersion) [inline sway/commands/input/xkb_switch_layout.c:77]: We should be able to just use a `xkb_layout_index_t` array instead of a `wl_list` here

File: sway/commands/input/xkb_switch_layout.c [hunk 2]
```diff
@@ -29,10 +35,10 @@ static xkb_layout_index_t get_current_layout_index(struct wlr_keyboard *kbd) {
 	return layout_idx;
 }
 
-static void switch_layout_relative(struct wlr_keyboard *kbd, int dir) {
+static xkb_layout_index_t get_layout_relative(struct wlr_keyboard *kbd, int dir) {
 	xkb_layout_index_t num_layouts = xkb_keymap_num_layouts(kbd->keymap);
 	xkb_layout_index_t idx = get_current_layout_index(kbd);
-	switch_layout(kbd, (idx + num_layouts + dir) % num_layouts);
+	return  (idx + num_layouts + dir) % num_layouts;
```
Comment (emersion) [inline sway/commands/input/xkb_switch_layout.c:41]: Style nit: two spaces here

File: sway/commands/input/xkb_switch_layout.c (hunk 1 above)
Comment (vitek) [reply sway/commands/input/xkb_switch_layout.c:77]: Do you suggest to create an array of pre calculated xkb_layout_index_t[] and then zip it with original input devices list server.input->devices? This approach requires to do input device filtration twice. That's why I've introduced xkb_switch_layout_action struct. 

As I understand sway/wl doesn't provide vector-like type array only array of pointers so I still have to manually free() every single element.

Perhaps I didn't get your idea.

Comment (emersion) [reply sway/commands/input/xkb_switch_layout.c:77]: Eh, right, I forgot that some filtering was necessary.

What I had in mind was something among these lines:

```c
struct xkb_switch_layout_action *actions = calloc(wl_list_length(&server.input->devices), sizeof(struct xkb_switch_layout_action));
size_t actions_len = 0;

// To add an entry:
actions[actions_len++] = (struct xkb_switch_layout_action){
    .keyboard = kbd,
    .layout = layout,
};

// To iterate:
for (size_t i = 0; i < actions_len; i++) {
    switch_layout(actions[i].keyboard, actions[i].layout);
}

// To cleanup:
free(actions);
```

Comment (vitek) [reply sway/commands/input/xkb_switch_layout.c]: Fixed thanks!

File: sway/commands/input/xkb_switch_layout.c [hunk 3]
```diff
@@ -77,12 +91,23 @@ struct cmd_results *input_cmd_xkb_switch_layout(int argc, char **argv) {
...
-			switch_layout_relative(dev->wlr_device->keyboard, relative);
+			action->layout = get_layout_relative(
+				dev->wlr_device->keyboard, relative);
 		} else {
-			switch_layout(dev->wlr_device->keyboard, layout);
+			action->layout = layout;
 		}
 	}
 
+	for (size_t i = 0; i < actions_len; i++) {
```
Comment (emersion) [inline sway/commands/input/xkb_switch_layout.c:107]: Can we add a small comment somewhere explaining that we need a two-step process because switching a layout in one keyboard may result in a change on other keyboards as well because of keyboard groups?

**Comment by emersion** [comment]
Code LGTM!

File: sway/commands/input/xkb_switch_layout.c (hunk 3 above)
Comment (vitek) [reply sway/commands/input/xkb_switch_layout.c:110]: fixed

**Review by emersion — APPROVED** [review]
Thanks!

(Next time, please amend your commit instead of pushing an additional fixup commit.)
