### PR TITLE
Ensure that seat->focused_layer is cleared on unmap

### LINKED ISSUE #4502: Segfault in wl_resource_get_client
Triggered randomly while testing wldash. Seems to be the focus logic breaking. Unfortunately lost the debug log.

sway 1a8b9fda8a81d71ec9de65fd4c3f1df40e03f971, wlroots a20bb38763877410a80a0c02ddfbfaa906c288fd

Dump below is debugoptimized, not a release build.

```
GNU gdb (GDB) Fedora 8.3-6.fc30
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/sway...
[New LWP 26525]
[New LWP 26527]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/bin/sway -d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa4e04349e4 in wl_resource_get_client () from /lib64/libwayland-server.so.0
[Current thread is 1 (Thread 0x7fa4df569a80 (LWP 26525))]
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.6-29.fc30.x86_64 cairo-1.16.0-5.fc30.x86_64 expat-2.2.7-1.fc30.x86_64 fontconfig-2.13.1-8.fc30.x86_64 freetype-2.9.1-7.fc30.x86_64 fribidi-1.0.5-2.fc30.x86_64 glib2-2.60.6-1.fc30.x86_64 glibc-2.29-15.fc30.x86_64 graphite2-1.3.10-7.fc30.x86_64 harfbuzz-2.3.1-1.fc30.x86_64 json-c-0.13.1-4.fc30.x86_64 libX11-1.6.7-1.fc30.x86_64 libX11-xcb-1.6.7-1.fc30.x86_64 libXau-1.0.9-1.fc30.x86_64 libXext-1.3.3-11.fc30.x86_64 libXrender-0.9.10-9.fc30.x86_64 libblkid-2.33.2-2.fc30.x86_64 libcap-2.26-5.fc30.x86_64 libdrm-2.4.99-1.fc30.x86_64 libevdev-1.7.0-1.fc30.x86_64 libffi-3.1-19.fc30.x86_64 libgcc-9.1.1-1.fc30.x86_64 libgcrypt-1.8.4-3.fc30.x86_64 libglvnd-egl-1.1.0-4.gitf92208b.fc30.x86_64 libglvnd-gles-1.1.0-4.gitf92208b.fc30.x86_64 libgpg-error-1.33-2.fc30.x86_64 libgudev-232-5.fc30.x86_64 libinput-1.14.0-1.fc30.x86_64 libmount-2.33.2-2.fc30.x86_64 libpciaccess-0.14-3.fc30.x86_64 libpng-1.6.36-1.fc30.x86_64 libstdc++-9.1.1-1.fc30.x86_64 libthai-0.1.28-2.fc30.x86_64 libwayland-client-1.17.0-1.fc30.x86_64 libwayland-egl-1.17.0-1.fc30.x86_64 libwayland-server-1.17.0-1.fc30.x86_64 libxcb-1.13.1-2.fc30.x86_64 libxkbcommon-0.8.3-1.fc30.x86_64 lz4-libs-1.9.1-1.fc30.x86_64 mesa-dri-drivers-19.1.4-1.fc30.x86_64 mesa-libEGL-19.1.4-1.fc30.x86_64 mesa-libgbm-19.1.4-1.fc30.x86_64 mesa-libglapi-19.1.4-1.fc30.x86_64 mtdev-1.1.5-14.fc30.x86_64 pango-1.43.0-3.fc30.x86_64 pcre-8.43-2.fc30.x86_64 pixman-0.38.0-1.fc30.x86_64 sssd-client-2.2.0-3.fc30.x86_64 systemd-libs-241-10.git511646b.fc30.x86_64 xcb-util-wm-0.4.1-15.fc30.x86_64 xz-libs-5.2.4-5.fc30.x86_64
(gdb) #0  0x00007fa4e04349e4 in wl_resource_get_client () at /lib64/libwayland-server.so.0
#1  0x00007fa4e0a55050 in wlr_seat_keyboard_enter (seat=0x18b2be0, surface=0x1eac0f0, keycodes=0x1ca9e30, num_keycodes=1, modifiers=0x1ca8a20) at ../subprojects/wlroots/types/seat/wlr_seat_keyboard.c:232
        wl_client = <optimized out>
        client = 0x0
        focused_client = <optimized out>
        focused_surface = <optimized out>
        event = {seat = 0x1e4c140, old_surface = 0x18b2aa0, new_surface = 0x1cc7e90}
#2  0x0000000000424828 in seat_set_focus_layer (seat=0x18b2aa0, layer=0x18d5e60) at ../sway/input/seat.c:1091
#3  0x0000000000426cc3 in check_focus_follows_mouse (e=0x1cc7e90, hovered_node=0x1e4c140, seat=0x18b2aa0) at ../sway/input/seatop_default.c:442
        focus = <optimized out>
        e = 0x1cc7e90
        cursor = 0x18b49b0
        surface = 0x1c9f090
        sx = 66.004519005871316
        sy = 1137.7788745331859
        node = 0x1e4c140
        drag_icon = <optimized out>
#4  0x0000000000426cc3 in handle_motion (seat=0x18b2aa0, time_msec=14617567, dx=<optimized out>, dy=<optimized out>) at ../sway/input/seatop_default.c:458
        e = 0x1cc7e90
        cursor = 0x18b49b0
        surface = 0x1c9f090
        sx = 66.004519005871316
        sy = 1137.7788745331859
        node = 0x1e4c140
        drag_icon = <optimized out>
#5  0x000000000041fce5 in cursor_motion (cursor=0x18b49b0, time_msec=14617567, device=0x1d58c50, dx=68, dy=0, dx_unaccel=34, dy_unaccel=0) at ../sway/input/cursor.c:261
        surface = 0x0
        sx = -nan(0xfffffffffffff)
        sy = 2.1219957909652723e-314
#6  0x000000000041ff1b in handle_cursor_motion_relative (listener=<optimized out>, data=<optimized out>) at ../sway/input/cursor.c:269
        cursor = <optimized out>
        e = <optimized out>
#7  0x00007fa4e0a7a49c in wlr_signal_emit_safe (signal=<optimized out>, data=0x7ffcca3a8df0) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x18b4a20
        l = 0x18b4a20
        cursor = {link = {prev = 0x18b4a20, next = 0x7ffcca3a8d30}, notify = 0x7fa4e0a7a420 <handle_noop>}
        end = {link = {prev = 0x7ffcca3a8d10, next = 0x18b3028}, notify = 0x7fa4e0a7a420 <handle_noop>}
#8  0x00007fa4e0a7a49c in wlr_signal_emit_safe (signal=<optimized out>, data=data@entry=0x7ffcca3a8df0) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x1d58dd0
        l = 0x1d58dd0
        cursor = {link = {prev = 0x1d58dd0, next = 0x7ffcca3a8da0}, notify = 0x7fa4e0a7a420 <handle_noop>}
        end = {link = {prev = 0x7ffcca3a8d80, next = 0x1d58cd8}, notify = 0x7fa4e0a7a420 <handle_noop>}
#9  0x00007fa4e0a46ac1 in handle_pointer_motion (event=<optimized out>, libinput_dev=<optimized out>) at ../subprojects/wlroots/backend/libinput/pointer.c:41
        wlr_dev = 0x1d58c50
        pevent = 0x1c311d0
        wlr_event = {device = 0x1d58c50, time_msec = 14617567, delta_x = 68, delta_y = 0, unaccel_dx = 34, unaccel_dy = 0}
#10 0x00007fa4e0a4594b in handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=0x170a990) at ../subprojects/wlroots/backend/libinput/backend.c:41
        backend = 0x170a990
        event = 0x1c311d0
#11 0x00007fa4e043736a in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#12 0x00007fa4e0435f25 in wl_display_run () at /lib64/libwayland-server.so.0
#13 0x000000000041650c in server_run (server=<optimized out>) at ../sway/server.c:202
#14 0x000000000040c369 in main (argc=2, argv=0x7ffcca3a91a8) at ../sway/main.c:400
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x44d85b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x450999 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x44d860 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x44d869 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x44d7bf "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x44c730 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x44d86f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x44d87e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x44d88e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x44dba0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
(gdb) quit
           PID: 26525 (sway)
           UID: 1000 (kenny)
           GID: 1000 (kenny)
        Signal: 11 (SEGV)
     Timestamp: Tue 2019-08-27 13:43:27 CEST (1min 41s ago)
  Command Line: /usr/local/bin/sway -d
    Executable: /usr/local/bin/sway
 Control Group: /user.slice/user-1000.slice/session-5.scope
          Unit: session-5.scope
         Slice: user-1000.slice
       Session: 5
     Owner UID: 1000 (kenny)
       Boot ID: debac3a6ce0c4b2f846819c98893aec3
    Machine ID: 090308f23ebd425d83fd87c64d7d39bf
      Hostname: kl-elitedesk
       Storage: /var/lib/systemd/coredump/core.sway.1000.debac3a6ce0c4b2f846819c98893aec3.26525.1566906207000000.lz4
       Message: Process 26525 (sway) of user 1000 dumped core.
                
                Stack trace of thread 26525:
                #0  0x00007fa4e04349e4 wl_resource_get_client (libwayland-server.so.0)
                #1  0x00007fa4e0a55050 wlr_seat_keyboard_enter (libwlroots.so.3)
                #2  0x0000000000424828 seat_set_focus_layer (sway)
                #3  0x0000000000426cc3 check_focus_follows_mouse (sway)
                #4  0x000000000041fce5 cursor_motion (sway)
                #5  0x000000000041ff1b handle_cursor_motion_relative (sway)
                #6  0x00007fa4e0a7a49c wlr_signal_emit_safe (libwlroots.so.3)
                #7  0x00007fa4e0a7a49c wlr_signal_emit_safe (libwlroots.so.3)
                #8  0x00007fa4e0a46ac1 handle_pointer_motion (libwlroots.so.3)
                #9  0x00007fa4e0a4594b handle_libinput_readable (libwlroots.so.3)
                #10 0x00007fa4e043736a wl_event_loop_dispatch (libwayland-server.so.0)
                #11 0x00007fa4e0435f25 wl_display_run (libwayland-server.so.0)
                #12 0x000000000040c369 main (sway)
                #13 0x00007fa4e0208f33 __libc_start_main (libc.so.6)
                #14 0x000000000040c4ee _start (sway)
                
                Stack trace of thread 26527:
                #0  0x00007fa4dfee24d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa4dea6a20b n/a (i965_dri.so)
                #2  0x00007fa4dea69e1b n/a (i965_dri.so)
                #3  0x00007fa4dfedc5a2 start_thread (libpthread.so.0)
                #4  0x00007fa4e02e0303 __clone (libc.so.6)
```

### PR DESCRIPTION
**Pull request by kennylevinsen**
The current seat may have changed between the last focus change and
this unmap, so we need to scan through all seats to find our layer.

### CODE REVIEW

File: sway/desktop/layer_shell.c [hunk 1]
```diff
@@ -302,8 +302,10 @@ static void unmap(struct sway_layer_surface *sway_layer) {
 		sway_layer->layer_surface->surface, true);
 
 	struct sway_seat *seat = input_manager_current_seat();
```
Comment (emersion) [inline sway/desktop/layer_shell.c]: This assignment is no longer necessary.

**Comment by kennylevinsen** [comment]
Closing for now, as this does not appear to be the issue. Unsure if my assumption that the seat can change holds.

**Comment by emersion** [comment]
I still think it's a good idea to have this merged. We don't want dangling free'ed pointers.

**Comment by kennylevinsen** [comment]
If you insist. :)
