### PR TITLE
Fix segfaults on output destruction

### LINKED ISSUE #3065: Segfault on exit when an output is disabled
* Sway Version: sway version 1.0-beta.1 (Nov  2 2018, branch 'HEAD') compiled without second check in drop_permission due to #3024 

* Debug Log: [sway.log](https://gist.github.com/apilat/72f49550966eb14185060c4063c6b8a3)

* Configuration File: only change to default is `output VGA-1 disable`. the error is not reproducible with the default configuration

* Full backtrace from coredump: [btfull.log](https://gist.github.com/apilat/5ce3d2115ddcaa0b8c2e86bcae28d0b6)

I ran sway, waited for all the screens to load, then exited with `Mod+Shift+E`.

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #3065 

This fixes two causes of segfaulting when an output is destroyed.

The first occurred when an output was never enabled. The issue was that
the destroy signal was never initialized so when it was emitted, sway
segfaulted. This was fixed by moving the initialization into
`output_create` since all outputs, regardless of whether they have ever
been enabled, will be destroyed at some point.

The second occurred when the cursor was on an output that was being
destroyed. The sway output would have already been removed, but if there
are other outputs, a cursor rebase would still occur. Since the
wlr_output still existed and the sway output was destroyed, the cursor
could be over nothing, resulting in a segfault when trying to get the
sway output, which was destroyed.

### CODE REVIEW

**Comment by emersion** [comment]
TBH I'm not a fan of dynamically adding/removing listeners when enabling/disabling outputs.

File: sway/input/cursor.c [hunk 1]
```diff
@@ -87,6 +87,10 @@ static struct sway_node *node_at_coords(
 	struct sway_output *output = wlr_output->data;
 	double ox = lx, oy = ly;
 	wlr_output_layout_output_coords(root->output_layout, wlr_output, &ox, &oy);
+	if (!output) {
```
Comment (emersion) [inline sway/input/cursor.c]: Can we move this check on line 87?

Comment (RedSoxFan) [reply sway/input/cursor.c]: Yup, moved

**Comment by RedSoxFan** [comment]
> TBH I'm not a fan of dynamically adding/removing listeners when enabling/disabling outputs.

Well this is one step towards not dynamically adding/removing them since it moves the destroy listener out of `output_enable` and into `output_create`

**Comment by emersion** [comment]
Thanks!
