### PR TITLE
output: fix updating output manager config

### LINKED ISSUE #5014: Starting kanshi causes failed assertion in `wlr_output_management_v1.c` [already bisected]
## Problem Description

`sway` master crashes via failed assertion when starting `kanshi` with an empty config file.

## Versions and Logs

* `sway` Version: 1.4-f5fa0c71 (Feb 13 2020, branch 'HEAD'), AUR r6219.f5fa0c71-1
* `wlroots` Version: AUR 0.10.0.r9.g273b280f-1
* `kanshi` Version: AUR r80.86d6aff-1
* Debug Log, Backtrace, and Configuration File: https://gist.github.com/Ferdi265/60c62196aa8ce518bcbd4e0d46b947d9

## Additional Information

* Failed Assertion:
```
sway: types/wlr_output_management_v1.c:689: head_send_state: Assertion `head->state.mode != NULL || wl_list_empty(&head->state.output->modes)' failed.
```
Using a debugger I confirmed, that `head->state.mode` is `NULL` and `&head->state.output->modes` is not empty.

* Triggering Commit: f5fa0c7124dde3438a22550aae017f824d20c93b "Stop calling apply_output_config from output_enable"

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #5014 

The output manager config is created when the output is created. It is
updated when the mode, transform, scale, or layout for the output
changes, as well as, when the output is destroyed.

Since the output->enabled property was not being set before calling
apply_output_config, the output event handlers were early returning and
never updating the output manager config when the output state was
committed.

This fixes the issue by setting output->enabled in apply_output_config
below the output disabling section. There are also a few other minor
changes that are required to function.

### CODE REVIEW

File: sway/tree/output.c [hunk 1]
```diff
@@ -102,20 +102,19 @@ struct sway_output *output_create(struct wlr_output *wlr_output) {
...
 
+	size_t len = sizeof(output->layers) / sizeof(output->layers[0]);
+	for (size_t i = 0; i < len; ++i) {
+		wl_list_init(&output->layers[i]);
+	}
+
 	return output;
 }
 
 void output_enable(struct sway_output *output) {
```
Comment (emersion) [inline sway/tree/output.c]: Hmm, maybe rename this to `configure_output`?

File: sway/config/output.c [hunk 2]
```diff
@@ -393,6 +395,7 @@ bool apply_output_config(struct output_config *oc, struct sway_output *output) {
 		// output disabled for now and try again when the output gets the mode
 		// we asked for.
 		sway_log(SWAY_ERROR, "Failed to modeset output %s", wlr_output->name);
+		output->enabled = output->configured;
```
Comment (emersion) [inline sway/config/output.c]: Maybe it makes more sense to save the previous value of `output->enabled` prior to the `apply_output_config` call, and change it back here?

File: sway/tree/output.c (hunk 1 above)
Comment (RedSoxFan) [reply sway/tree/output.c]: Renamed `output_enable` to `output_configure`

File: sway/config/output.c (hunk 2 above)
Comment (RedSoxFan) [reply sway/config/output.c]: Changed. Although I'm pretty sure it's a logic error if the value did not match output->configured.

Comment (emersion) [reply sway/config/output.c]: Yeah, the previous version worked. It just required the reader to understand that previously enabled outputs were always configured.
