### PR TITLE
Fix segfaults caused by faulty command parsing

### LINKED ISSUE #4239: crash on swaymsg command
* **Sway Version**: `sway version 1.1-rc1-34-g5b1a8d62 (Jun  9 2019, branch 'master')`

* **Debug Log**: of `./build/sway/sway -d -c /etc/sway/config &>/tmp/sway.log`: http://sprunge.us/KcmhqR

* **Default Config File** (untouched): `/etc/sway/config` http://sprunge.us/jsajhn
* **CUSTOM Config File**: `/etc/sway/config.d/99-custom.mine`: http://sprunge.us/YxWBgg

* **Steps to reproduce**:
 1.) start sway as user `me` with standard config + above 99-custom.mine config: with `./build/sway/sway -d -c /etc/sway/config`
 2.) start sakura with app_id `my-shell` using custom shortcut `$mod+shift+return`
 3.) switch to empty/fresh workspace with default shortcut `$mod+2`
 4.) try to get sakura shell over using custom shortcut `$mod+shift+s`

* **Stack Trace**, if sway crashes:
    `coredumpctl gdb sway` with `bt full`: http://sprunge.us/HIv9ZV

### PR DESCRIPTION
**Pull request by mcoffin**
This fixes faulty command parsing introduced by
f0f5de9a9e87ca1f0d74e7cbf82ffceba51ffbe6. When that commit allowed
criteria reset on ';' delimeters in commands lists, it failed to account
for its inner ','-parsing loop eating threw the entire rest of the
string.

This refactors argsep to use a list of multiple separators, and
(optionally) return the separator that it matched against in this
iteration via a pointer. This allows it to hint at the command parser
which separator was used at the end of the last command, allowing it to
trigger a potential secondary read of the criteria.

Fixes #4239

### CODE REVIEW

File: common/stringop.c [hunk 1]
```diff
@@ -251,37 +251,60 @@ char *join_args(char **argv, int argc) {
...
-		} else if (*end == '\0') {
-			*stringp = NULL;
-			break;
-		} else if (!in_string && !in_char && !escaped && strchr(delim, *end)) {
+			end = interesting + 1;
+		} else if (*interesting == '\\') {
+			if (escaped) {
+				escaped = NULL;
+			} else {
+				escaped = end;
```
Comment (RedSoxFan) [inline common/stringop.c]: I'm pretty sure that this should be `escaped = interesting`.  That would also mean that `escaped` could remain a `bool` and the check above could be changed to `if (escaped && interesting != end) {`

File: common/stringop.c [hunk 2]
```diff
@@ -251,37 +251,60 @@ char *join_args(char **argv, int argc) {
...
+		} else {
+			end++;
 		}
-		if (*end != '\\') {
-			escaped = false;
-		}
-		++end;
+	}
+	if (!interesting) {
+		*stringp = NULL;
```
Comment (RedSoxFan) [inline common/stringop.c]: `*matched` should also be set to `\0` since the end was reached instead of a delim. Otherwise, the previous value set will still be there (unless reset by the caller).

File: common/stringop.c (hunk 1 above)
Comment (mcoffin) [reply common/stringop.c]: Yep. Nice catch. I've been blessed so much with using Rust to write parsers that I'd forgotten how much of a PITA it is in raw C before I built this. :rofl:

File: common/stringop.c [hunk 3]
```diff
@@ -251,37 +251,61 @@ char *join_args(char **argv, int argc) {
...
 	bool in_string = false;
 	bool in_char = false;
 	bool escaped = false;
-	while (1) {
-		if (*end == '"' && !in_char && !escaped) {
+	char *interesting = NULL;
+
+	while ((interesting = argsep_next_interesting(end, delim))) {
+		if (escaped && interesting != end) {
+			escaped = NULL;
```
Comment (RedSoxFan) [inline common/stringop.c]: `escaped = false`

**Comment by mcoffin** [comment]
@RedSoxFan done.

**Comment by RedSoxFan** [comment]
Thanks!
