### PR TITLE
check for workspace command name arg (fix #5131)

### LINKED ISSUE #5131: Sway segfaults when trying to move workspace between outputs
Hello!

First of all, thank you for the greatest thing that happened to Linux graphics subsystem. 

I'm using sway version 1.4:

```
$ swaymsg -t get_version
sway version 1.4
```
and I have my Nvidia card disabled using bbswitch.

```
$ lsmod | grep nvidia | wc -l
0
```
```
$ cat /etc/modprobe.d/bbswitch.conf
options load_state=0 unload_state=0
```
```
$ cat /etc/mkinitcpio.conf | grep bbswitch
MODULES=(intel_agp i915 bbswitch)
```

I have two monitors. One is my laptop monitor that has resolution of `1920x1080` and another is an external monitor with 4k resolution.

Whenever I try to run the following command:
```
swaymsg workspace output DP-1
```
sway segfaults.

Here is the stracktrace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa08177f1e5 in __strlen_avx2 () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fa08022edc0 (LWP 35541))]
(gdb) bt full
#0  0x00007fa08177f1e5 in __strlen_avx2 () at /usr/lib/libc.so.6
#1  0x00007fa0816acbc3 in strdup () at /usr/lib/libc.so.6
#2  0x00005583ba98ba89 in  ()
#3  0x00005583ba98be7e in  ()
#4  0x00005583ba9b7687 in  ()
#5  0x00005583ba9b7b85 in  ()
#6  0x00005583ba9b8dc9 in  ()
#7  0x00007fa081028faa in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#8  0x00007fa0810274e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#9  0x00005583ba9775ff in  ()
#10 0x00007fa081645023 in __libc_start_main () at /usr/lib/libc.so.6
#11 0x00005583ba97794e in  ()
(gdb)
```

I've also uploaded [the log file](https://gist.github.com/dikeert/01e189d9a03346cd9ecbe5483f104dd6). I found the very end of it interesting:

```
2020-03-23 20:35:14 - [sway/commands.c:255] Handling command 'workspace output DP-1'
2020-03-23 20:35:14 - [common/stringop.c:237] join_args:argc should be positive
```

My config is pretty much default. Exceptions are: disabled bar, a rule for `telegram-desktop` to move it into scratchpad and that's it for now. 

Just in case, here are my outputs:

```
$ swaymsg -t get_outputs
Output eDP-1 'Unknown 0x103D 0x00000000'
  Current mode: 1920x1080 @ 60.006001 Hz
  Position: 3840,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Available modes:
    1920x1080 @ 60.006001 Hz

Output DP-1 'Samsung Electric Company U28E590 H4ZMC00814' (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Max render time: off
  Available modes:
    720x400 @ 70.082001 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 66.667000 Hz
    640x480 @ 72.808998 Hz
    640x480 @ 75.000000 Hz
    800x600 @ 56.250000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 72.188004 Hz
    800x600 @ 75.000000 Hz
    832x624 @ 74.551003 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 70.069000 Hz
    1024x768 @ 75.028999 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1152x864 @ 75.000000 Hz
    1280x800 @ 59.810001 Hz
    1440x900 @ 59.887001 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 59.953999 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz
    2560x1440 @ 59.951000 Hz
    3840x2160 @ 29.969999 Hz
    3840x2160 @ 30.000000 Hz
    3840x2160 @ 59.997002 Hz
```

Please let me know if I can provide any other useful information.

### PR DESCRIPTION
**Pull request by r-c-f**
For the 'workspace <name> output <output>' command, output_location must
be greater than zero or the attempt to get the workspace name with
join_args will segfault or abort() (depending on the flavor of
sway_assert() in use). This checks and returns an error instead.

### CODE REVIEW

File: sway/commands/workspace.c [hunk 1]
```diff
@@ -140,7 +140,10 @@ struct cmd_results *cmd_workspace(int argc, char **argv) {
 			break;
 		}
 	}
-	if (output_location >= 0) {
+	if (output_location == 0) {
+		return cmd_results_new(CMD_INVALID, "Expected 'workspace "
```
Comment (emersion) [inline sway/commands/workspace.c]: Can we move the whole string on the second line to make grepping easier?

**Comment by emersion** [comment]
Shouldn't we do the same for `gaps`?
