### PR TITLE
Pass gesture events to clients

### LINKED ISSUE #4724: Implement pointer-gestures wayland protocol [Former: Trackpad (pinch) gestures are not passed to clients]
Steps to reproduce:
 - start evince (or any other app that uses pinch gestures. Mostly gtk3 apps. eyg, inkscape 1.0 ...)
 - pinch your trakpad... (I am using a mbp 2015) nothing happens
 - On gnome shell the document gets zoomed in/out

The pointer-gestures protocol is not yet implementd for sway.
It is part of wlroots: https://github.com/swaywm/wlroots/pull/1731/files
Maybe there is only very little additional work to do?

### PR DESCRIPTION
**Pull request by lolzballs**
Fixes #4724.

This change can be tested quite easily if you use a backend which supports gestures (i.e. libinput). Open evince and your favourite pdf and you shall now see that pinch-to-zoom works properly. Prior to this, pinch-to-zoom would not do anything since the pinch and swipe events generated by the libinput backend are not handled anywhere (i.e. passed to the active client).

I'm not too sure how this will affect #1904 but I think there shouldn't be a huge change, as this change is solely passing pointer gestures to clients, rather than detecting a configurable gesture and executing a sway routine.

### CODE REVIEW

**Comment by ddevault** [comment]
Thanks! This doesn't effect touch gestures, which are a different animal entirely.

File: sway/input/cursor.c [hunk 1]
```diff
@@ -825,6 +879,20 @@ struct sway_cursor *sway_cursor_create(struct sway_seat *seat) {
 	cursor->hide_source = wl_event_loop_add_timer(server.wl_event_loop,
 			hide_notify, cursor);
 
+	cursor->pointer_gestures = wlr_pointer_gestures_v1_create(server.wl_display);
+	cursor->pinch_begin.notify = handle_pointer_pinch_begin;
+	wl_signal_add(&wlr_cursor->events.pinch_begin, &cursor->pinch_begin);
```
Comment (emersion) [inline sway/input/cursor.c]: These signals are not removed when the cursor is destroyed.

Comment (lolzballs) [reply sway/input/cursor.c]: Ah sorry about that. I made a change to correct this, although since the pull request was merged already I'm not sure what the best path to fixing this is.

Also on a sidenote, `wlr_pointer_gestures_v1` doesn't have a destroy or free function. It seems it handles destroying itself when the display is destroyed. Is this something worth worrying about?

Comment (emersion) [reply sway/input/cursor.c]: >Ah sorry about that. I made a change to correct this, although since the pull request was merged already I'm not sure what the best path to fixing this is.

If you could submit a new PR to fix this, that would be great.

>Also on a sidenote, wlr_pointer_gestures_v1 doesn't have a destroy or free function. It seems it handles destroying itself when the display is destroyed. Is this something worth worrying about?

Yeah, wlr_pointer_gestures_v1 is destroyed when the display is.
