### PR TITLE
Perform keymap validation

### LINKED ISSUE #4148: Invalid xkb options result in unusable keyboard and therefore no way to exit sway
* Sway Version: `1.1-rc1-4-g8c8e6a6c (May 11 2019, branch 'HEAD')`

I was trying to set up a local keyboard layout. I made a mistake and confused `en` with `us`, etc. This resulted in a sway instance that I was not available to terminate (no `Ctrl-Alt-Fn` switching, no `win-shift-e`, etc). I understand that it is a config error, but it's a pity that I had to power-cycle the whole box.

- A minimal config file:
```
set $mod Mod4

input type:keyboard {
        xkb_layout "en,cs"
        xkb_variant ",qwerty"
        xkb_options "grp:alt_shift_toggle"
}

bindsym $mod+Return exec konsole

bindsym $mod+Shift+q kill

bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'
```
(Some) invalid configurations result in an error message like this in the debug log:
```
xkbcommon: ERROR: Couldn't find file "symbols/en" in include paths
xkbcommon: ERROR: 1 include paths searched:
xkbcommon: ERROR:       /usr/share/X11/xkb
xkbcommon: ERROR: 1 include paths could not be added:
xkbcommon: ERROR:       /home/jkt/.xkb
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
2019-05-13 13:15:28 - [sway-9999/sway/input/keyboard.c:515] cannot configure keyboard: keymap does not exist
```

- Expected behavior:
  - In a perfect world, I would love to see a user-visible error message (similar to what I get when I reload config on the fly and there's a config schema error).
  - Alternatively, as a minimum, make sure that keyboard is still available. Default to an english layout "as if no config was present".

In case someone ends up here by a random web search, this is the correct config stanza:
```
input type:keyboard {
        xkb_layout "us,cz"
        xkb_variant ",qwerty"
        xkb_options "grp:alt_shift_toggle"
}
```

### PR DESCRIPTION
**Pull request by RedSoxFan**
Closes #4148 (this is the error part; see #4153 for something usable)

**Just the first commit**: basic invalid keymap prevention

Before the delta input config is stored, this attempts to compile a
keymap with it. If the keymap fails to compile, then the first line of
the xkbcommon log entry will be included with a `CMD_FAILURE`, the
entire xkbcommon log entry will be included in the sway error log, and
the delta will not be stored.

This will only handle basic issues such as a layouts not existing. This
will NOT catch more complex issues such as when a variant does
exist, but not for the given layout (ex: `azerty` is a valid variant,
but the `us` layout does not have a `azerty` variant).

**Both commits combined**: full invalid keymap protection

This allows for an optional validation stage of the input config before
storing it. Currently, the only validation performed is a valid xkb
configuration. The validation stage will do a dry run of the storage
process and make sure that storing the input config will not result in
any invalid xkb configurations. If there are any xkb keymap compilation
errors, the input config will not be stored, the full xkbcommon log
will be rewritten to the sway log, and the first line will be stored in
the error variable passed to store_input_config. The error is then used
to provide a little bit of information for the CMD_FAILURE.

### CODE REVIEW

File: sway/commands/input.c [hunk 1]
```diff
@@ -86,6 +87,15 @@ struct cmd_results *cmd_input(int argc, char **argv) {
 	}
 
 	if (!res || res->status == CMD_SUCCESS) {
+		char *error = NULL;
+		struct xkb_keymap *keymap = sway_keyboard_compile_keymap(
+				config->handler_context.input_config, &error);
+		if (!keymap) {
+			return cmd_results_new(CMD_FAILURE, "Failed to compile keymap: %s",
+					error ? error : "(null)");
```
Comment (shramov) [inline sway/commands/input.c]: Is not 'error' leaking here?
Maybe it's better to log errors when they appear?

Comment (RedSoxFan) [reply sway/commands/input.c]: > Is not 'error' leaking here?

Fixed

> Maybe it's better to log errors when they appear?

The errors are being logged when they appear. There is to provide a quick description in swaymsg/swaynag  for user convenience.

Comment (shramov) [reply sway/commands/input.c]: Also it's better to print something more descriptive instead of '(null)', very confusing

Comment (RedSoxFan) [reply sway/commands/input.c]: I'll change it to `(error allocation failed)` when I get back to my laptop

Comment (shramov) [reply sway/commands/input.c]: Maybe it's not allocation error, maybe callback was not called?
Or on any error it will be called?

File: sway/input/keyboard.c [hunk 2]
```diff
@@ -476,13 +476,47 @@ struct sway_keyboard *sway_keyboard_create(struct sway_seat *seat,
...
+
+	va_copy(args_copy, args);
+	vsnprintf(error, length, format, args_copy);
+	va_end(args_copy);
+
+	if (error[length - 2] == '\n') {
+		error[length - 2] = '\0';
+	}
+
+	sway_log(SWAY_ERROR, "(xkbcommon) %s", error);
```
Comment (emersion) [inline sway/input/keyboard.c]: Maybe we can use `level` to choose the sway log level?

Comment (emersion) [inline sway/input/keyboard.c]: Nit: so far we've prefixed error messages coming from libs with `[name]` instead of `(name)`.

File: sway/input/keyboard.c [hunk 3]
```diff
@@ -476,13 +476,47 @@ struct sway_keyboard *sway_keyboard_create(struct sway_seat *seat,
...
+
+	char **data = xkb_context_get_user_data(context);
+	if (data && !*data) {
+		*data = error;
```
Comment (emersion) [inline sway/input/keyboard.c]: We should probably only fill this if the log level is error

File: sway/commands/input.c (hunk 1 above)
Comment (RedSoxFan) [reply sway/commands/input.c]: I used `(details unavailable)`, which isn't really helpful either, but shouldn't be confusing. The two causes would be the allocation failed or xkbcommon just didn't log anything (for whatever reason).

File: sway/input/keyboard.c (hunk 2 above)
Comment (RedSoxFan) [reply sway/input/keyboard.c]: Done

Comment (RedSoxFan) [reply sway/input/keyboard.c]: Noted and changed

File: sway/input/keyboard.c (hunk 3 above)
Comment (RedSoxFan) [reply sway/input/keyboard.c]: Done

**Comment by RedSoxFan** [comment]
I updated the second commit to something nicer

File: sway/input/keyboard.c [hunk 4]
```diff
@@ -495,13 +495,53 @@ struct sway_keyboard *sway_keyboard_create(struct sway_seat *seat,
...
+
+struct xkb_keymap *sway_keyboard_compile_keymap(struct input_config *ic,
+		char **error) {
 	struct xkb_rule_names rules = {0};
 	if (ic) {
 		input_config_fill_rule_names(ic, &rules);
 	}
 
 	struct xkb_context *context = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
+	xkb_context_set_user_data(context, error);
```
Comment (emersion) [inline sway/input/keyboard.c]: Can we unset user data at the end of the function? Just to be sure it won't write at an invalid address.

Comment (RedSoxFan) [reply sway/input/keyboard.c]: Done

**Comment by emersion** [comment]
First commit LGTM. The second one seems a little bit complicated.

**Comment by RedSoxFan** [comment]
> First commit LGTM. The second one seems a little bit complicated.

This first commit is simple, but will only catch basic stuff like typos. The second commit catches more (including, for example, layout and variant mismatches), but I'm not really sure how to make the implementation better. I guess it depends on how far we want to go

**Comment by RedSoxFan** [comment]
>  I guess it depends on how far we want to go

Any opinions on this? I think it may be more helpful to users to have some of the information shown by swaynag/swaymsg as opposed to being "hidden" in the debug log and them thinking it is just not working. However, I do understand that the second commit adds a lot of complexity to how input configs are stored.

The first commit is pretty straight forward so that should be fine, but I can remove the second commit if needed. Alternatively, if anyone has any ideas for making it simpler, that could work too.

**Comment by emersion** [comment]
Can't we merge configs, then sanity-check the whole thing, then apply it if it's fine? I don't understand why callbacks are needed.

**Comment by RedSoxFan** [comment]
> Can't we merge configs, then sanity-check the whole thing, then apply it if it's fine? I don't understand why callbacks are needed.

We can't just merge the configs without some way of rolling it back. Otherwise, it leaves the input configs in an invalid state anyway.

**Comment by emersion** [comment]
Can't we merge the existing config into a temporary config, then merge the new config on top, then sanity-check it, and then merge the temporary config on top on the existing config?

**Comment by RedSoxFan** [comment]
> Can't we merge the existing config into a temporary config, then merge the new config on top, then sanity-check it, and then merge the temporary config on top on the existing config?

For named input configs, yes. For type and wildcard configs, no since that may partially propagate it. But with that said, the dry run can actually be restricted to just type and wildcard related logic, which can simplify the second commit. I'll update the PR shortly

**Comment by RedSoxFan** [comment]
I reworked the second commit again. I think this version is better.

**Comment by emersion** [comment]
Thanks!
