### PR TITLE
Call view_set_tiled for mapping non-floating views

### LINKED ISSUE #2209: Toplevels are not tiled anymore
1. Run `gnome-calculator`
2. It's not rendering in a tiled state

Probably a #2205 regression.

### PR DESCRIPTION
**Pull request by RyanDwyer**
Fixes #2209.

### CODE REVIEW

File: sway/tree/view.c [hunk 1]
```diff
@@ -513,6 +513,8 @@ void view_map(struct sway_view *view, struct wlr_surface *wlr_surface) {
 	// launch it as a tiled view in the root of the workspace instead.
 	if (container_is_floating(focus)) {
 		focus = focus->parent->parent;
+	} else {
+		view_set_tiled(view, true);
```
Comment (emersion) [inline sway/tree/view.c]: I'd move this to line 537, because `container_set_floating` will un-tile views

**Comment by emersion** [comment]
Thanks!
