### PR TITLE
criteria: match containers without view

### LINKED ISSUE #4929: Command criteria only match views
Some criteria match container attributes (e.g. `con_mark`, `con_id`, `floating`) and many commands operate on containers, but there's no way to apply commands to non-leaf containers using criteria.
```
$ swaymsg 'splitv'
$ xterm &
$ swaymsg 'focus parent; mark test; focus child'
$ swaymsg '[con_mark="test"] focus'
Error: No matching node.
```
In `i3` this will correctly focus the parent container.

From what I understand criteria are expanded using `criteria_get_views` which, as the name suggests, only returns views. `handler_context.container` is then set to `view->container`. I believe this can be solved by matching on containers instead of views. I can try to make a patch if that is of interest.

* Sway Version:
```
$ swaymsg -t get_version
sway version 1.2
```
but doesn't appear to have changed on current master.

* Debug Log:
I don't believe the relevant code paths do much logging. Please let me know otherwise.

* Configuration File:
Reproducible with empty/default configuration.

### PR DESCRIPTION
**Pull request by ANerd**
Closes #4929

Replaces `criteria_get_views` with `criteria_get_containers` which can
return containers without views when the criteria only contains
container properties.

### CODE REVIEW

**Comment by ddevault** [comment]
What does i3 do about this?

**Comment by ANerd** [comment]
i3 supports this, as can be tested by the following and similar examples:
```
$ i3-msg 'splitv'
$ xterm &
$ i3-msg 'focus parent; mark test; focus child'
$ i3-msg '[con_mark="test"] focus'
```

I made this patch because this feature was part of my i3 workflow, and it broke when I moved to sway.

File: include/sway/criteria.h [hunk 1]
```diff
@@ -6,6 +6,8 @@
 #include "list.h"
 #include "tree/view.h"
 
+struct sway_container;
```
Comment (RedSoxFan) [inline include/sway/criteria.h]: I don't think this is needed. `struct sway_container` is not referenced in the header and  `sway/criteria.c` already includes `sway/tree/container.h`.

File: sway/criteria.c [hunk 2]
```diff
@@ -144,8 +158,72 @@ static void find_urgent_iterator(struct sway_container *con, void *data) {
 	list_add(urgent_views, con->view);
 }
 
+static bool criteria_matches_container(struct criteria *criteria,
```
Comment (RedSoxFan) [inline sway/criteria.c]: It looks like i3 only matches containers by `con_id` and `con_mark`. The rest of the options will only match windows/views.

https://github.com/i3/i3/blob/fc01ece3657e334d9067c40c0e7274ee955345e5/src/commands.c#L190

Comment (ANerd) [reply sway/criteria.c]: It also looks like i3 ignores any other terms when the container has no window. I verified this by doing `i3-msg '[con_mark="test" class="do_not_match"] focus` and it still focused the container. I find this inconsistent, but I'm happy to do the same for compatibility.

File: sway/criteria.c [hunk 3]
```diff
@@ -144,6 +144,35 @@ static void find_urgent_iterator(struct sway_container *con, void *data) {
 	list_add(urgent_views, con->view);
 }
 
+bool has_container_criteria(struct criteria *criteria) {
```
Comment (RedSoxFan) [inline sway/criteria.c]: Since this isn't used outside of the file and is not included in the header, can you please make this `static`?

**Comment by RedSoxFan** [comment]
Thanks!
