### PR TITLE
swaybar: fix cursor scale

### LINKED ISSUE #1750: Swaybar doesn't update cursor on output scale change
When updating an output scale, swaybar's cursor scale is oversized.

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #1750

This fixes a few issues with swaybar's cursor scaling:
1. The cursor scale is now changed when the output scale changes
2. The cursor scale is no longer bound by the max output scale when
swaybar is launched
3. Related to the previous item, the cursor is no longer tiny on low
scale outputs after the max output scale has changed

This also bumps up `wl_compositor` to version 4 to allow usage of `wl_surface_damage_buffer`.

Note: This matches the way swaynag handles cursor scaling so any changes to this PR may also need to be changed for swaynag in a follow-up PR

### CODE REVIEW

File: swaybar/input.c [hunk 1]
```diff
@@ -55,32 +55,40 @@ static enum x11_button wl_axis_to_x11_button(uint32_t axis, wl_fixed_t value) {
...
+	if (pointer->cursor_theme) {
+		wl_cursor_theme_destroy(pointer->cursor_theme);
+	}
+	int scale = pointer->current ? pointer->current->scale : 1;
+	pointer->cursor_theme = wl_cursor_theme_load(NULL, 24 * scale, bar->shm);
+	struct wl_cursor *cursor;
+	cursor = wl_cursor_theme_get_cursor(pointer->cursor_theme, "left_ptr");
+	pointer->cursor_image = cursor->images[0];
+	wl_surface_set_buffer_scale(pointer->cursor_surface, scale);
+	wl_surface_attach(pointer->cursor_surface,
```
Comment (emersion) [inline swaybar/input.c]: It'd be better to damage the whole surface with `wl_surface_damage_buffer` since we're updating it.

Comment (RedSoxFan) [reply swaybar/input.c]: Do I just need to add a call to `wl_surface_damage_bufer` or can you please explain what I should be changing?

Comment (emersion) [reply swaybar/input.c]: Ah, we probably need to bump `wl_compositor` version to 4.
