### PR TITLE
commands/resize: make resize consider all siblings

### LINKED ISSUE #5936: Resizing a window in a multi-window layout doesn't work like in i3
If I have (for example) 4 windows tiled horizontally, and I resize the rightmost window using resize mode (`$mod+r`), the behavior between i3 and sway differs.

In i3, if I increase the width of one window, the width of all other windows are evenly reduced to compensate.

In Sway, only the window immediately next to the window being resized gets its width reduced, all other windows are untouched.

I have a ultra-wide screen, and I usually start 5 chat applications horizontally. One of the chat applications is really just a list, so it doesn't need to be particularly wide, so I tend to reduce its width by about 50%.

In i3, I just select that window, reduce the width using resize mode, and afterwards all the other windows are equally wide. In Sway, the window(s) right next to the one I'm resizing end up being much larger than the rest.

### PR DESCRIPTION
**Pull request by timhallmann**
Fixes a compatibility issue with i3 where resizing works as described
hereafter:
> Direction can either be one of up, down, left or right. Or you can be
> less specific and use width or height, in which case i3 will take/give
> space from all the other containers.

Sway previously considered only the direct neighbours not all siblings.

Fixes #5936

### CODE REVIEW

**Comment by Ochiruko** [comment]
It's been three years. Has this been fixed elsewhere? If not, are any reviewers working on this?

**Comment by timhallmann** [comment]
Seems unlikely.

While I wouldn't mind getting this merged, I do not care enough to further bother with finding a reviewer.

File: sway/commands/resize.c [hunk 1]
```diff
@@ -76,105 +76,87 @@ void container_resize_tiled(struct sway_container *con,
...
 	if (is_horizontal(axis)) {
-		if (con->pending.width + amount < MIN_SANE_W) {
-			return;
-		}
-		if (next->pending.width - sibling_amount < MIN_SANE_W) {
-			return;
-		}
-		if (prev && prev->pending.width - sibling_amount < MIN_SANE_W) {
-			return;
+		for(int i = 0; i < resize->length; i++) {
```
Comment (emersion) [inline sway/commands/resize.c:106]: Style nit: missing space between `for` and `(`

(Applies to other lines of code below as well.)

**Review by emersion — COMMENTED** [review]
LGTM apart from the style issues.

**Review by emersion — APPROVED** [review]
Thank you!

**Comment by timhallmann** [comment]
Thanks for merging! :)
