### PR TITLE
cursor: update hide timer during config apply

### LINKED ISSUE #5686: sway crashes instantly (segmentation fault)
- **Sway Version:**
sway version 1.5-7aea4692 (Sep 15 2020, branch 'master')

- **Debug Log:**
[sway.log](https://gist.github.com/antisocrates/5c2db46e43234b98ff64f47b8e7de248)

- **Configuration File:**
[config](https://gist.github.com/antisocrates/85062c5f45acea51675ce7ffbfe7f84f)

- **Stack Trace:**
[journalctl](https://gist.github.com/antisocrates/c10265186126edda35470ac2e9f72b19)

    [coredump](https://ufile.io/j0nj3mfc)

- **Description:**
 Starting sway from tty, instantly crashes with segmentation fault.

### PR DESCRIPTION
**Pull request by Emantor**
We can't arm the timer during cursor creation since the config may not
be ready yet. Instead arm the timer while applying the input
configuration, cursor_get_timeout() can now handle this even if the
configuration is not ready yet:

Return NULL in calls to seat_get_config*() if the config is not
initialized yet. This is required since we try to retrieve the hide
timeout from the cursor config, even if the config is not initialized.

Return 0 if we can't find any input configuration. This is okay even if
a timeout is configured, since the config will reapply the seat
configuration after load and sets up the correct timer with the correct
timeout.

Fixes #5686

### CODE REVIEW

**Comment by Emantor** [comment]
Apologies for the breakage.

**Comment by antisocrates** [comment]
Fixes both the segmentation fault crash bug, and timeout is honored after login. Thanks

File: sway/input/seat.c [hunk 1]
```diff
@@ -1430,6 +1432,9 @@ void seat_apply_config(struct sway_seat *seat,
 
 struct seat_config *seat_get_config(struct sway_seat *seat) {
 	struct seat_config *seat_config = NULL;
+	if(!config) {
```
Comment (emersion) [inline sway/input/seat.c:1435]: Style: missing space after `if`

File: sway/input/seat.c [hunk 2]
```diff
@@ -1442,6 +1447,9 @@ struct seat_config *seat_get_config(struct sway_seat *seat) {
 
 struct seat_config *seat_get_config_by_name(const char *name) {
 	struct seat_config *seat_config = NULL;
+	if(!config) {
```
Comment (emersion) [inline sway/input/seat.c:1450]: Ditto

**Comment by Emantor** [comment]
Fixed both style issues.

File: sway/input/cursor.c [hunk 3]
```diff
@@ -246,6 +246,9 @@ int cursor_get_timeout(struct sway_cursor *cursor) {
 	if (!sc) {
 		sc = seat_get_config_by_name("*");
 	}
+	if (!sc) {
```
Comment (emersion) [inline sway/input/cursor.c:249]: This is already accounted for with the ternary expression below.

File: sway/input/seat.c [hunk 4]
```diff
@@ -1430,6 +1432,9 @@ void seat_apply_config(struct sway_seat *seat,
 
 struct seat_config *seat_get_config(struct sway_seat *seat) {
 	struct seat_config *seat_config = NULL;
+	if (!config) {
```
Comment (emersion) [inline sway/input/seat.c:1435]: Hmm. But `seat_apply_input_config` unconditionally accesses `config`. Does something make `cursor_get_timeout` different?

Comment (Emantor) [reply sway/input/seat.c]: No, I just tested again and have now removed the line and verified it by using some additional logging. I applied the changes for the crashes first and moved the event source at the very last. All that is required is moving the arm of the timer.

**Comment by Emantor** [comment]
This should be ready for merge, thanks for the review.

File: sway/input/seat.c (hunk 4 above)
Comment (emersion) [reply sway/input/seat.c]: OK. If removing completely the checks make you uncomfortable, we can add assertions instead.

**Review by emersion — APPROVED** [review]
LGTM, thanks!
