### PR TITLE
Fix dormant cursor when using multiple seats

### LINKED ISSUE #2921: A third extra cursor appears using 2 seats
I configured sway to use 2 seats, one with all the inputs in my computer and a second with just a mouse. 
I get 3 cursors, 2 of them work as intended, and a third that cannot be moved with any input device.

**Using** 
sway version 1.0-beta.1 (Oct 21 2018, branch 'master')

**Config**

```
seat myseat attach 0:3:Sleep_Button
seat myseat attach 1:1:AT_Translated_Set_2_keyboard
seat myseat attach 2:7:SynPS/2_Synaptics_TouchPad
seat myseat attach 2:10:TPPS/2_IBM_TrackPoint
seat myseat attach 6058:20564:ThinkPad_Extra_Buttons

seat sideseat attach 1118:2053:Designer_Mouse
```

**Log (grep seat)**
```
- [sway/sway/config.c:656] Read line 232: #seat sideseat attach 1118:2060:UniversalFoldableKb
- [sway/sway/config.c:656] Read line 234: seat myseat attach 0:3:Sleep_Button
- [sway/sway/config.c:593] Peeked line: `seat myseat attach 1:1:AT_Translated_Set_2_keyboard`
- [sway/sway/config.c:698] Expanded line: seat myseat attach 0:3:Sleep_Button
- [sway/sway/commands.c:387] handling config command 'seat myseat attach 0:3:Sleep_Button'
- [sway/sway/commands.c:169] find_handler(seat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/input/input-manager.c:462] applying new seat config for seat myseat
- [sway/sway/config.c:656] Read line 235: seat myseat attach 1:1:AT_Translated_Set_2_keyboard
- [sway/sway/config.c:593] Peeked line: `seat myseat attach 2:7:SynPS/2_Synaptics_TouchPad`
- [sway/sway/config.c:698] Expanded line: seat myseat attach 1:1:AT_Translated_Set_2_keyboard
- [sway/sway/commands.c:387] handling config command 'seat myseat attach 1:1:AT_Translated_Set_2_keyboard'
- [sway/sway/commands.c:169] find_handler(seat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/input/input-manager.c:462] applying new seat config for seat myseat
- [sway/sway/config.c:656] Read line 236: seat myseat attach 2:7:SynPS/2_Synaptics_TouchPad
- [sway/sway/config.c:593] Peeked line: `seat myseat attach 2:10:TPPS/2_IBM_TrackPoint`
- [sway/sway/config.c:698] Expanded line: seat myseat attach 2:7:SynPS/2_Synaptics_TouchPad
- [sway/sway/commands.c:387] handling config command 'seat myseat attach 2:7:SynPS/2_Synaptics_TouchPad'
- [sway/sway/commands.c:169] find_handler(seat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/input/input-manager.c:462] applying new seat config for seat myseat
- [sway/sway/config.c:656] Read line 237: seat myseat attach 2:10:TPPS/2_IBM_TrackPoint
- [sway/sway/config.c:593] Peeked line: `seat myseat attach 6058:20564:ThinkPad_Extra_Buttons`
- [sway/sway/config.c:698] Expanded line: seat myseat attach 2:10:TPPS/2_IBM_TrackPoint
- [sway/sway/commands.c:387] handling config command 'seat myseat attach 2:10:TPPS/2_IBM_TrackPoint'
- [sway/sway/commands.c:169] find_handler(seat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/input/input-manager.c:462] applying new seat config for seat myseat
- [sway/sway/config.c:656] Read line 238: seat myseat attach 6058:20564:ThinkPad_Extra_Buttons
- [sway/sway/config.c:593] Peeked line: `seat sideseat attach 1118:2053:Designer_Mouse`
- [sway/sway/config.c:698] Expanded line: seat myseat attach 6058:20564:ThinkPad_Extra_Buttons
- [sway/sway/commands.c:387] handling config command 'seat myseat attach 6058:20564:ThinkPad_Extra_Buttons'
- [sway/sway/commands.c:169] find_handler(seat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/config/seat.c:14] new_seat_config(myseat)
- [sway/sway/input/input-manager.c:462] applying new seat config for seat myseat
- [sway/sway/config.c:656] Read line 240: seat sideseat attach 1118:2053:Designer_Mouse
- [sway/sway/config.c:593] Peeked line: `#seat myseat fallback true`
- [sway/sway/config.c:698] Expanded line: seat sideseat attach 1118:2053:Designer_Mouse
- [sway/sway/commands.c:387] handling config command 'seat sideseat attach 1118:2053:Designer_Mouse'
- [sway/sway/commands.c:169] find_handler(seat)
- [sway/sway/config/seat.c:14] new_seat_config(sideseat)
- [sway/sway/config/seat.c:14] new_seat_config(sideseat)
- [sway/sway/input/input-manager.c:462] applying new seat config for seat sideseat
- [sway/sway/config.c:656] Read line 242: #seat myseat fallback true
- [backend/wayland/registry.c:22] Remote wayland global: wl_seat v6
- [backend/wayland/registry.c:22] Remote wayland global: wl_seat v6
- [backend/wayland/registry.c:22] Remote wayland global: wl_seat v6
sway: ../backend/wayland/wl_seat.c:412: seat_handle_name: Assertion `backend->seat == wl_seat' failed.

```

### PR DESCRIPTION
**Pull request by RyanDwyer**
The cursor's image would be removed or set when the seat's capabilities were updated, but there was nothing to prevent the image from being set at other times.

To test:

* Have `seat seat1 attach "1:1:AT_Translated_Set_2_keyboard"` in your config.
* Launch sway on DRM.
* The cursor's position will be in the top left of an output. Move it away and note there is only one cursor at the moment.
* Launch a view on that output then close the view.
* A second cursor would appear in the top left in response to the view unmapping.

Fixes #2921.

### CODE REVIEW

File: sway/input/cursor.c [hunk 1]
```diff
@@ -1220,6 +1220,9 @@ static void handle_request_set_cursor(struct wl_listener *listener,
 
 void cursor_set_image(struct sway_cursor *cursor, const char *image,
 		struct wl_client *client) {
+	if (!(cursor->seat->wlr_seat->capabilities & WL_SEAT_CAPABILITY_POINTER)) {
```
Comment (emersion) [inline sway/input/cursor.c]: What happens when the seat looses the capability? This prevents the image from being unset.

Comment (RyanDwyer) [reply sway/input/cursor.c]: It gets removed in `seat_update_capabilities`.

Comment (RyanDwyer) [reply sway/input/cursor.c]: Ah, but we've set the caps already. I'll amend.

Comment (emersion) [reply sway/input/cursor.c]: My bad, `seat_update_capabilities` doesn't call `cursor_set_image` (calls directly `wlr_cursor_set_image`).

**Comment by SirCmpwn** [comment]
Thanks!
