### PR TITLE
cmd_seat: split action and config handlers

### LINKED ISSUE #4233: Performance issues with "seat seat0 cursor set x y"
* Sway Version: `sway version 1.1.1`

Freshly compiled from git tag "1.1.1", since weirdly sway-1.1.1 on ArchLinux gives 1.0 to swaymsg -t get_version and sway -v

* Debug Log: https://pastebin.com/f8hq6yCd

Note that I removed ~ 2 MB worth of repeating lines (replaced them by --SKIP--)

* Configuration File: Bug also happen in default configuration

I want to be able to simulate smooth mouse movement from a script.

Under i3/X, I use [xte](https://linux.die.net/man/1/xte). I thought I could just `swaymsg -t command seat seat0 cursor set x y` to achieve the same result with Sway.

Unfortunately, it doesn’t works. Sending ~60 such commands per second (for visual smoothness) makes Sway use 100% of CPU, with the cursor moving only ~1-2 times per second and the terminal instance running the script (tested both with alacritty and xterm) ending up getting killed.

Here is a Python script reproducing the issue : https://gist.github.com/sloonz/865f49654a7d64d0500debe0b6e75661

It basically tries to smoothly move the cursor on a circle of radius 300 px centered around (500, 500) at 1 turn/second. Running it results in a non-smooth movement, Sway using huge amount of CPU, and the terminal running the script getting killed.

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #4233 

This separates the logic for seat subcommand handlers that only perform
actions on the seat and handlers that alter the seat config. The former
group can immediately free the seat config after running the command as
it is only used by the subcommand to find the name of the seat to
operate on. The latter group alters the seat config so it will need to
go through the storage and application stage (assuming success).

_I chose the above solution rather than the proposed flag since this
constrains all of the logic to the seat command handler. Additionally,
a flag is useless for the remainder of the life of the seat config_

### CODE REVIEW

**Comment by emersion** [comment]
Note: we'd need a similar fix for `xkb_switch_layout`, right now it's hardcoded IIRC.

File: sway/commands/seat.c [hunk 1]
```diff
@@ -7,15 +7,45 @@
...
+// these handlers perform actions on the seat
+static struct cmd_handler seat_action_handlers[] = {
+	{ "cursor", seat_cmd_cursor },
+};
+
+// must be in order for the bsearch
+// these handlers alter the seat config
 static struct cmd_handler seat_handlers[] = {
 	{ "attach", seat_cmd_attach },
-	{ "cursor", seat_cmd_cursor },
```
Comment (emersion) [inline sway/commands/seat.c]: Adding a `bool` flag to `cmd_handler` would have been much nicer… But then it wouldn't work with `config_subcommand` and `find_handler`.

Comment (RedSoxFan) [reply sway/commands/seat.c]: Actually, `find_handler` has some issues that need to be fixed anyway. For example, `seat * layout tabbed` works the same as `layout tabbed` (plus the unnecessary seat overhead)
