### PR TITLE
Fix moving out of tab/stack when only child

### LINKED ISSUE #2078: segfault in container_move
same config:
```
default_orientation vertical
workspace_layout stacking
```

open a single window, move it left (that splits the screen in two with nothing on the right side, it probably shouldn't?), move it back and segfault.

```
==3344==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000068 (pc 0x00000045af3c bp 0x7ffe32176040 sp 0x7ffe3
2175fd0 T0)
==3344==The signal is caused by a READ memory access.
==3344==Hint: address points to the zero page.
    #0 0x45af3b in container_move ../sway/tree/layout.c:515
    #1 0x4433fe in cmd_move ../sway/commands/move.c:180
    #2 0x40e414 in execute_command ../sway/commands.c:369
    #3 0x435f7d in keyboard_execute_command ../sway/input/keyboard.c:100
    #4 0x43636e in keyboard_execute_bindsym ../sway/input/keyboard.c:168
    #5 0x437590 in handle_keyboard_key ../sway/input/keyboard.c:380
    #6 0x7f0287709948 in wlr_signal_emit_safe ../util/signal.c:29
    #7 0x7f02876eb08f in wlr_keyboard_notify_key ../types/wlr_keyboard.c:125
    #8 0x7f02876ac64a in handle_keyboard_key ../backend/libinput/keyboard.c:73
    #9 0x7f02876ab0ca in handle_libinput_readable ../backend/libinput/backend.c:35
    #10 0x7f0287977f01 in wl_event_loop_dispatch src/event-loop.c:641
    #11 0x7f0287976601 in wl_display_run src/wayland-server.c:1260
    #12 0x409da6 in main ../sway/main.c:428
    #13 0x7f0286e5918a in __libc_start_main (/lib64/libc.so.6+0x2318a)
    #14 0x40b049 in _start (/opt/wayland/bin/sway+0x40b049)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../sway/tree/layout.c:515 in container_move
```

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #2078 

This handles moving out of a tab/stack when the container is the only child.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
@martinetd take a look at this

File: sway/tree/layout.c [hunk 1]
```diff
@@ -312,6 +312,19 @@ static void workspace_rejigger(struct sway_container *ws,
 static void move_out_of_tabs_stacks(struct sway_container *container,
 		struct sway_container *current, enum movement_direction move_dir,
 		int offs) {
+	if (container->parent == current->parent
+			&& current->parent->children->length == 1) {
+		wlr_log(L_DEBUG, "Changing layout of %zd", current->parent->id);
+		current->parent->layout = move_dir =
```
Comment (emersion) [inline sway/tree/layout.c]: Missing a `=`?

Comment (RedSoxFan) [reply sway/tree/layout.c]: Oops

**Comment by SirCmpwn** [comment]
Thanks!
