### PR TITLE
Fix xwayland floating views unclickable

### LINKED ISSUE #2195: Firefox download dialog unclickable
1. Open Firefox
2. Click a link that downloads a file
3. The dialog selection whether to open the file with an app or save it is unclickable (input events go to the window underneath)

Works in rootston.

### PR DESCRIPTION
**Pull request by emersion**
Some xwayland views are first configured with a 1x1 size, and then
resized. Since the view size isn't updated, they are unclickable.

Fixes #2195

### CODE REVIEW

File: sway/desktop/xwayland.c [hunk 1]
```diff
@@ -284,6 +284,11 @@ static void handle_commit(struct wl_listener *listener, void *data) {
 		transaction_notify_view_ready_by_size(view,
 				surface_state->width, surface_state->height);
 	}
+
+	if (container_is_floating(view->swayc)) {
+		view_update_size(view, surface_state->width, surface_state->height);
```
Comment (emersion) [inline sway/desktop/xwayland.c]: Note that this function will damage stuff and that it's not necessary because `wlr_surface` does this automatically. Maybe we should just set `view->width` and `view->height`?

Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: Are you sure the damage isn't necessary? What if the surface becomes smaller?

I think you'd need to set `view->swayc->current.view_{width,height}` in addition to `view->{width,height}`. The view properties are considered pending, and the current state is what's used for rendering.

However, you might not want to write them into the current state if there are transactions pending. I would try something like:

    if (view->swayc->instructions->length) {
    	transaction_notify_view_ready_by_size(view,
    			surface_state->width, surface_state->height);
    } else if (container_is_floating(view->swayc)) {
    	view_update_size(view, surface_state->width, surface_state->height);
    }

...then make `view_update_size` set both the the pending properties and current properties. Not sure about damage.

Comment (emersion) [reply sway/desktop/xwayland.c]: >Are you sure the damage isn't necessary? What if the surface becomes smaller?

Nah, this is handled by `wlr_surface`. Though, it's necessary if the view has borders, so in the end I'll probablu keep it.

>I think you'd need to set view->swayc->current.view_{width,height} in addition to view->{width,height}.

The input code is using pending properties, that's why it worked. We probably need to change that.

>However, you might not want to write them into the current state if there are transactions pending.

Well I don't know what to do if transactions are in progress. Once the transaction is applied the view won't have the size we want (from `surface_state`), it'll have the size of the transaction. We probably need to queue a fake transaction instead.

Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: > Well I don't know what to do if transactions are in progress. Once the transaction is applied the view won't have the size we want (from surface_state), it'll have the size of the transaction.

This problem isn't specific to floating xwayland views. We ultimately rely on the client to set their size to what we configure them to. If they don't, the transaction times out and we render them incorrectly.

If we have an xwayland view in a transaction and it resizes to something other than what we tell it to, once the transaction has applied it'll resize the swayc anyway.

Comment (emersion) [reply sway/desktop/xwayland.c]: > If we have an xwayland view in a transaction and it resizes to something other than what we tell it to, once the transaction has applied it'll resize the swayc anyway.

What if it's floating?

Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: I meant floating, and edited my comment to say so. You saw the pre-edit version.

Comment (emersion) [reply sway/desktop/xwayland.c]: Ah okay, this makes more sense

**Comment by emersion** [comment]
Updated

**Comment by SirCmpwn** [comment]
Thanks!
