### PR TITLE
fix remove_view_from_scratchpad

### LINKED ISSUE #1468: Scratchpad show then floating toggle crashes sway.
The following sequence of commands on a window makes sway to crach : 
move to scratchpad
scratchpad show
floating toggle.

Can someone confirm? 
(And question : what is the correct way to get a window out of scratchpad?)

### PR DESCRIPTION
**Pull request by taiyu-len**
Fixes #1468 `Scratchpad show then floating toggle crashes sway.`
Could not reproduce with original instructions,
but can reproduce with instructions provided by nickbatsaras

1. Move a window to scratchpad
2. Move another window to scratchpad
3. Scratchpad show
4. Floating toggle
5. Scratchpad show
6. Scratchpad show

The first sign of the issue starts at step 4.
Given a scratchpad with 2 windows (1,2), with window 1 being a visible container,
turning off floating via `toggle floating` will call `remove_view_from_scratchpad`.
this function was incorrect and resulted in removing window 2,
leaving window 1 in the scratchpad when it shouldnt be and losing window 2 permanently.
the segfault was later caused in update_visibility_output due to window 1 having a NULL parent and dereferencing it.

this fix correctly removes the right container from the scratchpad list,
and  checks for null parent just in case,
also added printing out of scratchpad to layout_log

there might be something more to this that i missed, but for now it seems to work

### CODE REVIEW

File: sway/debug_log.c [hunk 1]
```diff
@@ -72,6 +72,11 @@ void layout_log(const swayc_t *c, int depth) {
 			}
 		}
 	}
+	if (c->type == C_ROOT) {
+		fprintf(stderr,"ScratchPad\n");
```
Comment (SirCmpwn) [inline sway/debug_log.c]: doop

File: sway/debug_log.c [hunk 2]
```diff
@@ -71,6 +71,11 @@ void layout_log(const swayc_t *c, int depth) {
 				layout_log(c->floating->items[i], depth + 1);
 			}
 		}
+	} else if (c->type == C_ROOT && scratchpad->length > 0) {
+		fprintf(stderr, "ScratchPad\n");
```
Comment (SirCmpwn) [inline sway/debug_log.c]: doop

Comment (taiyu-len) [reply sway/debug_log.c]: Im guessing you want that line removed?
i left it in, so the scratchpad list is more clear. the output for example
```
focus:R      |(0x5555557a9320)(p:(nil)   )(f:0x55555583d4a0)(h:18446744073709551615)Type:root|layout:-    |w:1680|h:1818|x:   0|y:   0|g:  0|vis:t|children: 1|name:root
|focus:X     |(0x55555583d4a0)(p:0x5555557a9320)(f:0x55555583d820)(h: 1)Type:op  |layout:-    |w:1014|h: 746|x:   0|y:   0|g: -1|vis:t|children: 1|name:WLC-1
|-focus:W    |(0x55555583d820)(p:0x55555583d4a0)(f:0x555555fd6430)(h:18446744073709551615)Type:ws  |layout:Vert |w:1014|h: 746|x:   0|y:   0|g: -1|vis:t|children: 2|name:1
|--focus:X   |(0x555555fd4f90)(p:0x55555583d820)(f:(nil)   )(h: 4)Type:view|layout:-    |w:1014|h: 373|x:   0|y:   0|g: -1|vis:t|children: 0|name:Wayland Terminal
|--focus:K   |(0x555555fd6430)(p:0x55555583d820)(f:(nil)   )(h: 2)Type:view|layout:-    |w:1014|h: 373|x:   0|y: 373|g: -1|vis:t|children: 0|name:Wayland Terminal
ScratchPad
focus:X      |(0x5555560e69f0)(p:(nil)   )(f:(nil)   )(h: 3)Type:view|layout:-    |w: 507|h: 559|x: 253|y:  93|g: -1|vis:f|children: 0|name:Wayland Terminal
focus:K      |(0x555555fd6430)(p:0x55555583d820)(f:(nil)   )(h: 2)Type:view|layout:-    |w:1014|h: 373|x:   0|y: 373|g: -1|vis:t|children: 0|name:Wayland Terminal
```

Comment (SirCmpwn) [reply sway/debug_log.c]: Ah. Alright.

**Comment by SirCmpwn** [comment]
Thanks!
