### PR TITLE
Fix geometry

### LINKED ISSUE #2178: Window geometry issues
Window geometry isn't handled properly.

Alacritty sets a window geometry larger than the surface's size. We don't handle that properly.

Floating windows have an offset on their input region (but no offset on input events).

Should also try to un-maximize tiled views, to check that we handle window geometry for tiled views correctly.

### LINKED ISSUE #2476: Correctly handle size changes for floating views
We already handle this for xwayland, but not for the other shells.

See https://github.com/swaywm/sway/pull/2466#discussion_r210662665

### PR DESCRIPTION
**Pull request by RyanDwyer**
The only issue I've found with this PR is alacritty flickers while resizing. I think the content area might be a subsurface, and we don't save or render subsurfaces during transactions. From what I've read in the alacritty project their Wayland support is pretty beta.

My testing includes {floating,tiling} {gedit,alacritty,urxvt} and testing {pointer events,moving,resizing}. Urxvt is included to make sure I didn't break anything with views which use normal borders and no geometry.

Fixes #2178

Fixes #2476

### CODE REVIEW

File: sway/desktop/render.c [hunk 1]
```diff
@@ -232,6 +234,10 @@ static void render_saved_view(struct sway_view *view,
 		.width = view->saved_buffer_width,
 		.height = view->saved_buffer_height,
 	};
+	struct wlr_box geometry;
+	view_get_geometry(view, &geometry);
+	box.x -= geometry.x;
+	box.y -= geometry.y;
```
Comment (emersion) [inline sway/desktop/render.c]: Shouldn't this use the saved geometry?

Comment (RyanDwyer) [reply sway/desktop/render.c]: Yeah, it should. I'll amend it after I get some more feedback.

File: sway/desktop/xwayland.c [hunk 2]
```diff
@@ -287,8 +287,6 @@ static void handle_commit(struct wl_listener *listener, void *data) {
 	if (view->swayc->instruction) {
 		transaction_notify_view_ready_by_size(view,
 				surface_state->width, surface_state->height);
-	} else if (container_is_floating(view->swayc)) {
```
Comment (emersion) [inline sway/desktop/xwayland.c]: Hmm, is there any bad consequence of removing this?

Maybe we should have common code for all shells doing that?

File: sway/desktop/xdg_shell.c [hunk 3]
```diff
@@ -231,6 +242,7 @@ static void destroy(struct sway_view *view) {
 static const struct sway_view_impl view_impl = {
 	.get_constraints = get_constraints,
 	.get_string_prop = get_string_prop,
+	.get_geometry = get_geometry,
```
Comment (emersion) [inline sway/desktop/xdg_shell.c]: Need to add the same for zxdg-shell-v6.

File: sway/desktop/xwayland.c (hunk 2 above)
Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: Your commit that I cherry picked removed the `view_set_{position,size}` functions. Maybe it wasn't called here at the time you made your commit.

I'm also unsure if there's any bad consequences of removing it. Maybe we could leave it out and see. If anything does need it, we can put it back and add a comment saying which program needs it.

Comment (emersion) [reply sway/desktop/xwayland.c]: I now remember what the issue is:
1. Open Firefox
2. Initiate a file download (e.g. go to https://www.debian.org/distrib/ and click on "64-bit PC netinst iso")
3. The "Open file/save as" dialog appears. It's initially small and is then resized to a larger size. It's broken with this patch.

File: sway/desktop/xwayland.c [hunk 4]
```diff
@@ -282,13 +282,19 @@ static void handle_commit(struct wl_listener *listener, void *data) {
...
-		view_update_size(view, surface_state->width, surface_state->height);
+				state->width, state->height);
+	} else if ((state->width != view->width || state->height != view->height) &&
+				container_is_floating(view->swayc)) {
+		// eg. The Firefox "Save As" dialog when downloading a file
+		// It maps at a small size then changes afterwards.
+		view->width = state->width;
+		view->height = state->height;
+		container_set_geometry_from_floating_view(view->swayc);
+		transaction_commit_dirty();
```
Comment (emersion) [inline sway/desktop/xwayland.c]: Hmm. So the client updated its size, and `transaction_commit_dirty` will send a new configure event with the same size?

Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: Not quite. `transaction_commit_dirty` sees that the pending size matches the desired size, so it'll won't send a configure. The transaction will be applied immediately.

Comment (emersion) [reply sway/desktop/xwayland.c]: Well `current` isn't updated, is it?

Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: It is. When the transaction is applied it copies the pending state to `current`.

Comment (emersion) [reply sway/desktop/xwayland.c]: I don't get it. `should_configure` has this check:

```c
	if (con->current.view_width == instruction->state.view_width &&
			con->current.view_height == instruction->state.view_height) {
```

When `transaction_commit_dirty` is called, `current` still has the old state (the transaction isn't applied yet). So it still sends a configure event right?

Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: Yeah, `should_configure` correctly returns false, but the instruction is already added to the transaction (added in `transaction_add_container`). An instruction is not a configure. An instruction may or may not need to send a configure. If it helps, you could think of an instruction as a container state that needs to be applied when the transaction is ready.

Comment (emersion) [reply sway/desktop/xwayland.c]: >Yeah, should_configure correctly returns false

No, `should_configure` returns `true`because the pending state (set here) mismatches the current state (set when the transaction is applied).

Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: Yeah, there's something wrong there. Let me mull over this.

Comment (RyanDwyer) [reply sway/desktop/xwayland.c]: This is ready for review again.

File: sway/desktop/transaction.c [hunk 5]
```diff
@@ -169,25 +170,17 @@ static void transaction_apply(struct sway_transaction *transaction) {
...
-		};
-		for (int j = 0; j < root_container.current.children->length; ++j) {
-			struct sway_container *output = root_container.current.children->items[j];
-			if (output->sway_output) {
-				output_damage_box(output->sway_output, &old_box);
-				output_damage_box(output->sway_output, &new_box);
-			}
+		// Damage the old location
+		desktop_damage_whole_container(container);
+		if (container->type == C_VIEW && container->sway_view->saved_buffer) {
```
[the remark this answers is not in the document]
Comment (RyanDwyer) [reply sway/desktop/transaction.c]: It seems to work as expected. We damage the container (using `desktop_damage_whole_container`) then apply the new state to `current` and call it again. The damage is based off the x/y properties, and these properties are changed when gaps are applied or removed.

[the remark this answers is not in the document]
Comment (emersion) [reply sway/desktop/transaction.c]: Oh right, missed that `desktop_damage_whole_container` call.

**Comment by emersion** [comment]
Fairly weird bug:

1. Open Gedit
2. Open the Preferences window, it's a floating window
3. Resize it smaller than the minimum size, it jumps a little at some point
4. Enter and leave the dialog a few times, each time it's configured it jumps

**Comment by RyanDwyer** [comment]
I can't reproduce that. When I make the preferences window small it stops at a certain size. I don't notice any jumping when resizing, nor when switching focus between the preferences window and the main window behind it.

**Comment by emersion** [comment]
https://sr.ht/WEMm.mkv

**Comment by RyanDwyer** [comment]
I still can't reproduce it, even using the default config. Can you try it with the default config if you're not already?

**Comment by emersion** [comment]
Tried with the default config, same issue.

**Comment by SirCmpwn** [comment]
I can reproduce this too, but it's very inconsistent. Maybe on average once in every 30 times I focus the floating window, it jumps a bit.

**Comment by SirCmpwn** [comment]
Note: willing to file a follow-up ticket for this issue.

**Comment by emersion** [comment]
Yeah, I'm okay with a follow-up issue as well.

**Comment by SirCmpwn** [comment]
Thanks! :tada:
