### PR TITLE
Resize only current and immediate siblings rather than all siblings

### LINKED ISSUE #3253: resize grow/shrink <direction> is not consistent with i3
* Sway Version: sway version 1.0-beta.2-17-gbca21ee0 (Dec 3 2018, branch 'maste
* Configuration File: vanilla configuration, only change is `set $term gnome-terminal`

In a workspace, open 3 terminals with horizontal splits:

```
+---------+
|    A    |
+---------+
|    B    |
+---------+
|    C    |
+---------+
```

In terminal A, typing, `swaymsg resize grow down` moves boundaries of all the windows. In i3, only the boundary between A and B moves, boundary between B and C stays at the same place.

Sidenote: while playing with resize, I got some weird "Error: Cannot resize any further" in terminal B when resize should have happened, but I could not determine what caused the issue. Just posting that here in case someone else noticed it.

### PR DESCRIPTION
**Pull request by RyanDwyer**
For example, create layout `V[view view view]` and resize the leftmost view using mod+rightclick. Previously, the edge between view 2 and 3 would be adjusted as well. Now this edge will remain constant, which matches the behaviour of i3.

To do this operation correctly, the resize tiling seatop now keeps track of two containers, as the container that resizes horizontally will be a different container to the one which resizes vertically (one will be an ancestor). The tiling resize seatop now figures out these containers during the start of the operation and keeps references to them in the event. A new function `container_find_resize_parent` has been introduced to do this. This function is also used by the resize command.

During cursor motion, the seatop logic is similar to before, but now has to choose the correct container to resize.

In `resize.c`, `container_resize_tiled` and `resize_tiled` have been merged into one. One of them originally did nothing except pass the values through to the other.

`container_resize_tiled` now takes a simplified approach where it just finds the immediate siblings on either side and resizes them without worrying about the others. The `parellel_coord` and `parallel_size` functions are no longer needed and have been removed.

Fixes #3253.

### CODE REVIEW

File: sway/commands/resize.c [hunk 1]
```diff
@@ -130,177 +130,108 @@ static bool is_horizontal(uint32_t axis) {
...
+	// both adjacent siblings. For RIGHT or DOWN, just select the next sibling.
+	// For LEFT or UP, convert it to a RIGHT or DOWN resize and reassign con to
+	// the previous sibling.
+	struct sway_container *prev = NULL;
+	struct sway_container *next = NULL;
+	list_t *siblings = container_get_siblings(con);
+	int index = container_sibling_index(con);
+
+	if (axis == AXIS_HORIZONTAL || axis == AXIS_VERTICAL) {
+		prev = siblings->items[index - 1];
```
Comment (RedSoxFan) [inline sway/commands/resize.c]: When running `resize grow width 10px` or `resize grow height 10px` on the first or last child, sway segfaults since `prev` and `next` get assigned invalid values here that are later dereferenced.

Comment (RyanDwyer) [reply sway/commands/resize.c]: Fixed.

**Comment by RedSoxFan** [comment]
Thanks!
