### PR TITLE
Fix commands: criteria, layout, move, workspace

### LINKED ISSUE #1518: move container to back_and_forth
It is currently possible to switch to the workspace where you were before:

> bindsym $mod+b workspace back_and_forth

It is not possible to move a container (window) there:

> \# doesn't work
> bindsym $mod+Shift+b move container to workspace back_and_forth

This is counterintuitive and makes it harder to work with workspaces that are named on the fly. It would be nice to support this.

### LINKED ISSUE #2336: Verify sway commands match i3 commands
Find a list of i3 commands and make sure we have all of them in sway (at least all the ones we want to have). Double check that each sway implementation supports the same arguments as the i3 equivalents.

Criteria:
- [x] class
	- [x] \_\_focused__
- [x] instance
	- [x] \_\_focused__
- [x] window_role
	- [x] \_\_focused__
- [x] window_type
	- [x] normal, dialog, utility, toolbar, splash, menu, dropdown_menu, popup_menu, tooltip, notification
- [x] id
- [x] title
	- [x] \_\_focused__
- [x] urgent
	- [x] latest/newest/last/recent (sway: only latest)
	- [x] oldest/first (sway: only oldest)
- [x] workspace
	- [x] \_\_focused__
- [x] con_mark
- [x] con_id
	- [x] \_\_focused__
- [x] floating
- [x] tiling

Commands:
- [x] exec ~~[--no-startup-id]~~
	- [x] command chaining
	- [x] exec quoting
- [x] split
	- [x] split vertical|horizontal|toggle
	- [x] splith
	- [x] splitv
	- [x] splitt
- [x] layout
	- [x] layout default|tabbed|stacking|splitv|splith (sway: default possible but not documented)
	- [x] layout toggle [split|all] (sway: all is ignored)
	- [x] layout toggle [split|tabbed|stacking|splitv|splith] [split|tabbed|stacking|splitv|splith] (sway: anything except split is ignored)
- [x] focus
	- [x] \<criteria> focus (undocumented)
	- [x] focus left|right|down|up
	- [x] focus parent|child|floating|tiling|mode_toggle
	- [x] focus output left|right|up|down|~~primary~~|\<output> (sway: no primary)
	- [x] focus mode_toggle
- [x] move
	- [x] move <left|right|down|up> [\<px> px] (sway: documentation does not specify px can be included)
	- [x] move [absolute] position <pos_x> [px] <pos_y> [px] (sway: absolute ignored)
	- [x] move [absolute] position center (sway: absolute ignored)
	- [x] move position mouse (sway: allows "absolute")
	- [x] move window|container to mark \<mark>
	- [x] move container|workspace to output left|right|down|up|current|~~primary~~|\<output> (sway: no primary; allows "window")
- [x] swap container with id|con_id|mark \<arg>
- [x] sticky enable|disable|toggle
- [x] workspace
	- [x] workspace next|prev|next_on_output|prev_on_output
	- [x] workspace back_and_forth
	- [x] workspace [--no-auto-back-and-forth] \<name> (sway: no --no-auto-back-and-forth)
	- [x] workspace [--no-auto-back-and-forth] number \<name> (sway: no --no-auto-back-and-forth)
	- [x] move [--no-auto-back-and-forth] [window|container] [to] workspace \<name> (sway: no --no-auto-back-and-forth; "to" has to be included)
	- [x] move [--no-auto-back-and-forth] [window|container] [to] workspace number \<name> (sway: no --no-auto-back-and-forth; "to" has to be included; undocumented)
	- [x] move [window|container] [to] workspace prev|next|current (sway: current undocumented)
        - [x] move container to workspace back_and_forth
	- [x] Also can be identified with both: "number \<number>: \<name>"
	- [x] rename workspace [\<old_name>] to <new_name>
- [x] resize
	- [x] resize grow|shrink <direction> [\<px> px [or \<ppt> ppt]]
	- [x] resize set \<width> [px|ppt] \<height> [px|ppt] (sway: no ppt) (#1737)
- [x] mark
	- [x] mark [--add|--replace] [--toggle] \<identifier>
	- [x] unmark \<identifier>
- [x] title_format \<format>
	- [x] Pango placeholders: %title, %class, %instance
- [x] border
	- [x] border normal|pixel [\<n>]
	- [x] border none|toggle
- [x] ~~shmlog~~
	- [x] ~~shmlog <size_in_bytes>~~
	- [x] ~~shmlog on|off|toggle~~
- [x] debuglog on|off|toggle
- [x] ~~restart~~
- [x] reload
- [x] exit
- [x] scratchpad
	- [x] move scratchpad (sway: also allows "to")
	- [x] scratchpad show
- [x] nop [\<comment>]
- [x] bar
	- [x] ~~bar hidden_state hide|show|toggle [\<bar_id>]~~
	- [x] ~~bar mode dock|hide|invisible|toggle [\<bar_id>]~~
- [x] mode <name>
- [x] floating enable|disable|toggle
- [x] fullscreen
- [x] kill

Configuration:
- [x] comments
- [x] font (sway: can be command)
- [x] Bindings
	- [x] Keyboard: bindsym|bindcode [--release] [\<Group>+][\<Modifiers>+]<keysym|keycode> command 
	- [x] Mouse: bindsym [--release] [--border] [--whole-window] [--exclude-titlebar] [\<Modifiers>+]button\<n> command
- [x] mode [--pango_markup] \<name>
- [x] floating_modifier \<Modifier> (sway: also includes normal|inverse)
- [x] floating_m<in|ax>imum_size \<width> x \<height>
- [x] default_orientation horizontal|vertical|auto (default follows on monitor size)
- [x] workspace_layout default|stacking|tabbed (sway: can be command; allows auto)
- [x] Default border (default: normal)
	- [x] default_[floating_]border normal|none|pixel
	- [x] default_[floating_]border normal|pixel \<px>
- [x] hide_edge_borders none|vertical|horizontal|both|smart (default: none)
- [x] for_window \<criteria> \<command>
- [x] no_focus \<criteria>
- [x] set $\<name> \<value> (sway: can be command, despite documentation; if \<name> is given without $, the $ is silently added instead of error)
- [x] ~~set_from_resource $\<name> <resource_name> \<fallback>~~
- [x] Assign (sway: can be command)
	- [x] assign \<criteria> [→] [workspace] [number] \<workspace> (sway: no number)
	- [x] assign \<criteria> [→] output left|right|up|down|primary|\<output> (sway: undocumented)
- [x] exec[_always] ~~[--no-startup-id]~~ \<command>
- [x] workspace \<workspace> output \<output> (sway: can be command)
- [x] Colors:
	- [x] \<colorclass> \<border> \<background> \<text> \<indicator> <child_border>
	- [x] colorclass: client.focused client.focused_inactive client.unfocused client.urgent client.placeholder client.background
- [x] ~~ipc-socket \<path> (default: /tmp/i3-%u.XXXXXX/ipc-socket.%p)~~
- [x] focus_follows_mouse yes|no (default: yes) (sway: does not document that the default is yes)
- [x] mouse_warping output|none (default: output)
- [x] popup_during_fullscreen smart|ignore|leave_fullscreen (default: smart)
- [x] focus_wrapping yes|no|force (default: yes)
- [x] force_focus_wrapping yes|no (deprecated)
- [x] ~~force_xinerama yes|no (default: no)~~
- [x] workspace_auto_back_and_forth yes|no (default: no) (sway: can be command)
- [x] force_display_urgency_hint \<timeout> ms (default: 500)
- [x] focus_on_window_activation smart|urgent|focus|none (default: smart)
- [x] show_marks yes|no (default: yes) (marks starting with _ will never be drawn) (sway: can be command)
- [x] line continuation \
- [x] bar
	- [x] i3bar_command \<command> (passed to "sh -c") (default: i3bar) (sway: uses swaybar instead of i3bar)
	- [x] status_command \<command> (passed to "sh -c")
	- [x] mode dock|hide|invisibile (default: dock)
	- [x] hidden_state hide|show (default: hide)
	- [x] modifier \<Modifier>|none (default: Mod4)
	- [x] bindsym [--release] button\<n> \<command>
	- [x] id <bar_id> (default: bar-x) (sway: default is not documented)
	- [x] position top|bottom
	- [x] output ~~primary~~|\<output>
	- [x] ~~tray_output none|~~primary~~|\<output>~~
	- [x] tray_padding \<px> [px] (default: 2)
	- [x] font \<font>
	- [x] separator_symbol \<symbol> (default: vertical)
	- [x] workspace_buttons yes|no (default: yes)
	- [x] strip_workspace_buttons yes|no (default: no)
	- [x] binding_mode_indicator yes|no (default: yes)
	- [x] Colors:
		- [x] background, statusline, separator, focused_background (fallback: background), focused_statusline (fallback: statusline), focused_separator (fallback: separator), focused_workspace, active_workspace, inactive_workspace, urgent_workspace, binding_mode (fallback: urgent_workspace)

Sway-exclusive:
- ~~clipboard \<content>~~
- layout auto <next|prev>
- layout auto [master|ncol] [inc|set] \<n>
- move <next|prev|first>
- floating_scroll
- gaps (TODO: check against i3-gaps)
- output
- ~~seamless_mouse~~
- include
- swaybg_command
- swaybar_command
- input
- seat
- opacity
- urgent enable|disable|allow|deny

### PR DESCRIPTION
**Pull request by ianyfan**
Ref #2336 

Fixes #1518

Criteria:
- [x] urgent
- [x] con_id=\_\_focused__

Commands:
- [x] layout
- [x] document \<criteria> focus
- [x] move
    - [x] documentation
    - [x] move position center
    - [x] move to mark
    - [x] move to workspace back_and_forth
    - [x] --no-auto-back-and-forth
    - [x] make "to" optional
- [x] workspace
    - [x] --no-auto-back-and-forth
    - [x] back_and_forth

Also prevents renaming workspace to "back_and_forth", as well as making it clear that they cannot be named to "special" workspace names.

### CODE REVIEW

File: sway/criteria.c [hunk 1]
```diff
@@ -361,8 +361,17 @@ static char *get_focused_prop(enum criteria_token token) {
...
 		}
 		break;
-	case T_CON_ID: // These do not support __focused__
-	case T_CON_MARK:
+	case T_CON_ID:
+		if (view->swayc == NULL) {
+			return NULL;
+		}
+		size_t id = view->swayc->id;
+		int len = snprintf(NULL, 0, "%zu", id) + 1;
```
Comment (minus7) [inline sway/criteria.c]: Is this the standard way to compute the string's length?

File: sway/sway.5.scd [hunk 2]
```diff
@@ -104,24 +104,39 @@ They are expected to be used with *bindsym* or at runtime through *swaymsg*(1).
...
-*layout* toggle split
-	Switches the focused container between the splitv and splith layouts.
+*layout* toggle [split|all]
+	Cycles the layout mode of the focused container though a preset list of
+	layouts. If no argument is given, then it cycles through stacking, tabbed
+	and the last split layout. If "split" is given, then it cycles through
+	splith and splitv. If "all" is given, then it cycles through every layout.
 
-*move* left|right|up|down [<px>]
+*layout* toggle [split|tabbed|stacking|splitv|splith] [split|tabbed|stacking|splitv|splith]...
```
Comment (minus7) [inline sway/sway.5.scd]: Your code doesn't seem to handle `split` here

File: sway/criteria.c (hunk 1 above)
Comment (emersion) [reply sway/criteria.c]: Yes. It's not a length (as in number of chars), it's a size (as in number of bytes that will get malloc'ed) so it probably makes more sense to name it `id_size`. Also it should be a `size_t`, not an `int`.

Comment (ianyfan) [reply sway/criteria.c]: Noted, thanks.

File: sway/sway.5.scd (hunk 2 above)
Comment (ianyfan) [reply sway/sway.5.scd]: Noted, thanks.

File: sway/criteria.c (hunk 1 above)
Comment (ascent12) [reply sway/criteria.c]: >Also it should be a size_t, not an int.

*printf returns an int and so it makes sense to leave it as it is. It really is splitting hairs, though.

Comment (martinetd) [reply sway/criteria.c]: fwiw I found that function after using snprintf like that myself, but for integer string length conversion we have this in `common/util.c` (declared in `include/util.h`):

```
int numlen(int n) {
        if (n == 0) {
                return 1;
        }
        return log10(n) + 1;
}
```

(It doesn't handle negative integers nor the full range of size_t, but both are fixable by just changing the prototype of the function. We only have one user though, it's a shame but it might be just as well to remove that function...)

**Comment by SirCmpwn** [comment]
Can we work on this a few commands at a time? I'd rather not do a mega-PR which attempts to close #2336 all in one go.

**Comment by ianyfan** [comment]
Got it, I'll add a checklist in the description

**Comment by ianyfan** [comment]
Ready for review, though not sure if I've missed a few edge cases in testing.

File: sway/tree/workspace.c [hunk 3]
```diff
@@ -250,20 +250,35 @@ struct sway_container *workspace_by_name(const char *name) {
...
-		return workspace_output_prev(current_output);
-	} else if (strcmp(name, "next") == 0) {
-		return workspace_next(current_workspace);
-	} else if (strcmp(name, "next_on_output") == 0) {
-		return workspace_output_next(current_output);
-	} else if (strcmp(name, "current") == 0) {
-		return current_workspace;
+
+	char *name_cpy = strdup(name);
+	char *first_word = strtok(name_cpy, " ");
```
Comment (RedSoxFan) [inline sway/tree/workspace.c]: What's the reasoning for getting and checking against the first word in this function?

File: sway/tree/workspace.c [hunk 4]
```diff
@@ -250,20 +250,35 @@ struct sway_container *workspace_by_name(const char *name) {
...
+		ws = workspace_output_prev(current_output);
+	} else if (strcmp(first_word, "next") == 0) {
+		ws = workspace_next(current_workspace);
+	} else if (strcmp(first_word, "next_on_output") == 0) {
+		ws = workspace_output_next(current_output);
+	} else if (strcmp(first_word, "current") == 0) {
+		ws = current_workspace;
+	} else if (strcasecmp(first_word, "back_and_forth") == 0) {
+		if (prev_workspace_name) {
+			ws = container_find(&root_container, _workspace_by_name,
```
Comment (RedSoxFan) [inline sway/tree/workspace.c]: Should this recreate the workspace if it doesn't exist anymore?

**Comment by ianyfan** [comment]
The logic is all done now, I think; I'll have a look at splitting the long lines later, and maybe squash some commits together.

**Comment by SirCmpwn** [comment]
Thanks!
