### PR TITLE
Send enter/leave events for floating views

### LINKED ISSUE #2482: Floating views don't handle output enter/leave events properly
If you open a window on a scale=1 output and drag it to a scale=2 output, it will be incorrectly scaled.

### LINKED ISSUE #2485: Workspaces from other outputs have incorrect scaling after unplugging
To test, have 2 outputs, one with a scale factor of 2 and one with a scale factor of 1.
Put some clients on workspaces on the second output (the one with scale = 1), then unplug the second output.
The workspaces then migrate to the first output (scale = 2) and clients are upscaled by the compositor, rather than letting them scale themselves. The only way to fix this is to move the clients to another non-empty workspace with correctly scaled clients.
I suppose the issue is that enter events are not sent when workspaces are migrated between outputs or between workspaces.

### PR DESCRIPTION
**Pull request by RyanDwyer**
Previously we used a reparent event to detect when a view changes parent, then sent an output enter/leave to the surfaces if needed. This worked for tiling views but not floating views, as floating views can intersect another output without changing parent.

The solution implemented for floating views also applies cleanly to tiling views, so the previous method has been completely replaced and the reparent event has been removed.

This introduces a new function `container_discover_outputs`. This function compares the container's `current` position to the outputs, sends enter and leave events as needed, and keeps track of which outputs it's intersecting in a new `container->outputs` list. If it has entered a new output with a different scale then the title and marks textures will also be recreated at the new scale.

The function is called when a transaction applies. This is convenient as it means we don't have to call it from various places.

There is imperfect rendering when a floating view overlaps two outputs with different scales. It renders correctly for the most recently entered output, but there is only one title texture so it renders incorrectly on the old output.

To test:

* Move tiling containers to different outputs and check the title and marks textures scale
* Move floating containers so they overlap multiple outputs and see the new output renders the title and marks texture correctly
* Move a floating split container so it overlaps multiple outputs
* Hotplug outputs and make sure it doesn't crash - I haven't tested this

Debug log messages are printed when an enter or leave event occurs.

Fixes #2482 
Fixes #2485

### CODE REVIEW

File: sway/tree/container.c [hunk 1]
```diff
@@ -1286,3 +1271,67 @@ bool container_is_fullscreen_or_child(struct sway_container *container) {
...
+		container_get_box(output, &output_box);
+		struct wlr_box intersection;
+		bool intersects =
+			wlr_box_intersection(&con_box, &output_box, &intersection);
+		int index = list_find(con->outputs, sway_output);
+
+		if (intersects && index == -1) {
+			// Send enter
+			wlr_log(WLR_DEBUG, "Con %p entered output %p", con, sway_output);
+			if (con->type == C_VIEW) {
```
Comment (emersion) [inline sway/tree/container.c]: Do we really need to maintain a list of entered outputs per non-view container?

File: sway/tree/container.c [hunk 2]
```diff
@@ -781,13 +754,25 @@ void container_damage_whole(struct sway_container *container) {
 	}
 }
 
+/**
+ * Return the output which will be used for scale purposes.
+ * This is the most recently entered output.
+ */
+static struct sway_output *container_get_effective_output(
```
Comment (emersion) [inline sway/tree/container.c]: Note: in the future we'll want to use the effective output when sending frame events. We don't want to send frame events at 120FPS if a view has entered 2 outputs. That's also how Weston does it.

File: sway/tree/container.c (hunk 1 above)
Comment (RyanDwyer) [reply sway/tree/container.c]: Yes. If the container renders its own title (eg. a nested split) then the title texture needs to be recreated at the new scale when the container enters a new output.

Remember, the plan is for root, outputs and workspaces to not be part of `sway_container` any more, so the `outputs` property won't apply to them.

**Comment by emersion** [comment]
Does this also fix https://github.com/swaywm/sway/issues/2158?

**Comment by ianyfan** [comment]
This is causing my sway to crash if I hotplug a new output whilst having floating windows. Logs are normal up to that point and do not give any information on the crash. Can you reproduce?

**Comment by RyanDwyer** [comment]
> Does this also fix #2158?

I've never experienced that issue. Probably a question for @SirCmpwn.

> This is causing my sway to crash if I hotplug a new output whilst having floating windows. Logs are normal up to that point and do not give any information on the crash. Can you reproduce?

I was able to make it crash by running it in a nested session and closing the "output" window from the outer session. I placed a floating view so it overlaps two outputs, then closed the output which it most recently entered. Then I attempted to move the view using mod+click and it crashed. I've added a fix to address this crash. I haven't done any DRM testing but it's likely this commit will fix that too.

**Comment by ianyfan** [comment]
Did not fix the issue, but this time there was an error log:
```
==18105==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x607000070ef8 at pc 0x562ddf0b9a69 bp 0x7fffdf93bf40 sp 0x7fffdf93bf30
READ of size 8 at 0x607000070ef8 thread T0
    #0 0x562ddf0b9a68 in update_marks_texture ../sway/tree/view.c:892
    #1 0x562ddf0ba7ed in view_update_marks_textures ../sway/tree/view.c:965
    #2 0x562ddf0aa10c in container_discover_outputs ../sway/tree/container.c:1330
    #3 0x562ddf04e272 in transaction_apply ../sway/desktop/transaction.c:197
    #4 0x562ddf04e468 in transaction_progress_queue ../sway/desktop/transaction.c:214
    #5 0x562ddf04fd97 in transaction_commit_dirty ../sway/desktop/transaction.c:396
    #6 0x562ddf0b15db in output_layout_handle_change ../sway/tree/root.c:21
    #7 0x7f49c432bdb7 in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #8 0x7f49c43017a4 in output_layout_reconfigure ../subprojects/wlroots/types/wlr_output_layout.c:134
    #9 0x7f49c430308e in wlr_output_layout_add_auto ../subprojects/wlroots/types/wlr_output_layout.c:411
    #10 0x562ddf0715fb in apply_output_config ../sway/config/output.c:215
    #11 0x562ddf0c00dc in output_create ../sway/tree/output.c:75
    #12 0x562ddf041d87 in output_enable ../sway/desktop/output.c:577
    #13 0x562ddf041cc7 in handle_new_output ../sway/desktop/output.c:567
    #14 0x7f49c432bdb7 in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #15 0x7f49c429e614 in new_output_reemit ../subprojects/wlroots/backend/multi/backend.c:113
    #16 0x7f49c432bdb7 in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #17 0x7f49c428e3ae in scan_drm_connectors ../subprojects/wlroots/backend/drm/drm.c:981
    #18 0x7f49c42848a3 in drm_invalidated ../subprojects/wlroots/backend/drm/backend.c:112
    #19 0x7f49c432bdb7 in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #20 0x7f49c42a12d3 in udev_event ../subprojects/wlroots/backend/session/session.c:51
    #21 0x7f49c2822a41 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0x9a41)
    #22 0x7f49c282114b in wl_display_run (/usr/lib/libwayland-server.so.0+0x814b)
    #23 0x562ddf037d3c in server_run ../sway/server.c:164
    #24 0x562ddf0369b5 in main ../sway/main.c:445
    #25 0x7f49c2004222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)
    #26 0x562ddf01eb9d in _start (/usr/local/bin/sway+0x2fb9d)

0x607000070ef8 is located 8 bytes to the left of 80-byte region [0x607000070f00,0x607000070f50)
allocated by thread T0 here:
    #0 0x7f49c4494019 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x562ddf0c6af4 in create_list ../common/list.c:14
    #2 0x562ddf0a0407 in container_create ../sway/tree/container.c:95
    #3 0x562ddf0a215d in container_view_create ../sway/tree/container.c:434
    #4 0x562ddf0b7726 in view_map ../sway/tree/view.c:521
    #5 0x562ddf055165 in handle_map ../sway/desktop/xdg_shell.c:399
    #6 0x7f49c432bdb7 in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #7 0x7f49c42d5120 in handle_xdg_surface_commit ../subprojects/wlroots/types/xdg_shell/wlr_xdg_surface.c:363
    #8 0x7f49c4311c33 in surface_commit_pending ../subprojects/wlroots/types/wlr_surface.c:398
    #9 0x7f49c4312161 in surface_commit ../subprojects/wlroots/types/wlr_surface.c:470
    #10 0x7f49bec5b1c7 in ffi_call_unix64 (/usr/lib/libffi.so.6+0x61c7)
    #11 0x7f49bec5ac29 in ffi_call (/usr/lib/libffi.so.6+0x5c29)
    #12 0x7f49c2824a2e  (/usr/lib/libwayland-server.so.0+0xba2e)
    #13 0x7f49c2820f28  (/usr/lib/libwayland-server.so.0+0x7f28)
    #14 0x7f49c2822a41 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0x9a41)
    #15 0x7f49c282114b in wl_display_run (/usr/lib/libwayland-server.so.0+0x814b)
    #16 0x562ddf037d3c in server_run ../sway/server.c:164
    #17 0x562ddf0369b5 in main ../sway/main.c:445
    #18 0x7f49c2004222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)
    #19 0x562ddf01eb9d in _start (/usr/local/bin/sway+0x2fb9d)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../sway/tree/view.c:892 in update_marks_texture
Shadow bytes around the buggy address:
  0x0c0e80006180: fd fd fd fd fd fd fd fd fa fa fa fa 00 00 00 00
  0x0c0e80006190: 00 00 00 00 00 fa fa fa fa fa 00 00 00 00 00 00
  0x0c0e800061a0: 00 00 00 fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0e800061b0: 00 00 fa fa fa fa 00 00 00 00 00 00 00 00 00 00
  0x0c0e800061c0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fa fa
=>0x0c0e800061d0: fa fa fd fd fd fd fd fd fd fd fd fd fa fa fa[fa]
  0x0c0e800061e0: 00 00 00 00 00 00 00 00 00 00 fa fa fa fa 00 00
  0x0c0e800061f0: 00 00 00 00 00 00 00 00 fa fa fa fa 00 00 00 00
  0x0c0e80006200: 00 00 00 00 00 00 fa fa fa fa 00 00 00 00 00 00
  0x0c0e80006210: 00 00 00 00 fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0e80006220: 00 fa fa fa fa fa 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==18105==ABORTING
```

**Comment by RyanDwyer** [comment]
I've committed a fix but it requires testing on DRM which I can't do at the moment. If you can test it then that'd be awesome, otherwise I'll get around to testing it later.

**Comment by SirCmpwn** [comment]
Does not fix https://github.com/swaywm/sway/issues/2158

**Comment by SirCmpwn** [comment]
Thanks!
