### PR TITLE
Fix scratchpad hidden split container related segfaults

### LINKED ISSUE #4788: Sway crashes on show scratchpad when focused window already is inside the scratchpad
I use a rofi to focus windows, including those in scratchpad
It does this in the background `swaymsg [con_id=<id of client> focus`
This works good for top level windows in the scratchpad, and shows the client.
For "nested" clients, such as a terminal in a tabbed view, it does not show the window
If you then tried to show the scratchpad sway crashes.

* Sway Version: 1.2
* Debug Log: https://gist.github.com/hakeee/3e64be7964ed26ee38c31052502b28a4
* Configuration File: `default` but with `termite` as terminal

* Steps to reproduce the crash:
1. Start sway
2. Open a terminal 
   This terminal gets con_id=5
3. Create a tabbed view
4. Open another terminal
5. Select parent (both tabs)
6. Move to scratchpad `swaymsg move scratchpad`
7. Open a new terminal
8. Execute `swaymsg [con_id=5] focus` 
   I believe the tabbed view should appear here with the terminal foused but it does not. 
   It would be nice if it did.
9. Show scratchpad `swaymsg scratchpad show`

* Stack Trace, if sway crashes: 
```
#0  0x00005574b8a91f5e in  ()
#1  0x00005574b8a92fde in  ()
#2  0x00005574b8a9c1bf in  ()
#3  0x00005574b8ac32c7 in  ()
#4  0x00005574b8aa7477 in  ()
#5  0x00005574b8ab026a in  ()
#6  0x00007fc240f5cb0e in  () at /usr/lib/libwlroots.so.3
#7  0x00007fc240f4afdd in wlr_keyboard_notify_key () at /usr/lib/libwlroots.so.3
#8  0x00007fc240f213b7 in  () at /usr/lib/libwlroots.so.3
#9  0x00007fc240f2032c in  () at /usr/lib/libwlroots.so.3
#10 0x00007fc240fa37f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#11 0x00007fc240fa239c in wl_display_run () at /usr/lib/libwayland-server.so.0
#12 0x00005574b8a86592 in  ()
#13 0x00007fc2415a5153 in __libc_start_main () at /usr/lib/libc.so.6
#14 0x00005574b8a868be in  ()
```

### PR DESCRIPTION
**Pull request by RPigott**
Fixes #4788, Replaces #4789 

OK, so there are a few bugs handling scratchpad hidden split containers (SPHSCs).

Originally reported segfault:
<details>
<summary>
`scratchpad toggle` causes segfault on focused hidden container (because it is inadvertantly possible to focus SPHSCs)
</summary>

 - stack trace in [comment](https://github.com/swaywm/sway/issues/4788#issuecomment-562295664)
</details>
But I've also found:
<details>
<summary>
`move to &lt;dest&gt;` causes segfault on SPHSC dest
</summary>

```
#0  0x0000564610a32042 in node_is_view (node=node@entry=0x0) at ../sway/sway/tree/node.c:41
#1  0x0000564610a10b9c in seat_get_active_tiling_child (seat=0x5646126c4220, parent=parent@entry=0x0) at ../sway/sway/input/seat.c:1251
        current = <optimized out>
#2  0x0000564610a040c6 in output_get_active_workspace (output=output@entry=0x0) at ../sway/sway/desktop/output.c:371
        seat = <optimized out>
        focus = <optimized out>
#3  0x0000564610a211db in cmd_move_container (argv=<optimized out>, argc=<optimized out>, no_auto_back_and_forth=<optimized out>) at ../sway/sway/commands/move.c:522
        new_output = 0x0
        new_workspace = <optimized out>
        node = <optimized out>
        seat = 0x5646126c4220
        old_parent = 0x0
        old_ws = 0x564612c41e60
        new_output_last_ws = <optimized out>
        focus = <optimized out>
        error = 0x0
        workspace = <optimized out>
        container = 0x564612c47540
        old_output = 0x564612715d40
        destination = 0x564612cca330
        __PRETTY_FUNCTION__ = "cmd_move_container"
        error = <optimized out>
        no_auto_back_and_forth = <optimized out>
#4  0x0000564610a211db in cmd_move (argc=<optimized out>, argv=<optimized out>) at ../sway/sway/commands/move.c:941
        error = <optimized out>
        no_auto_back_and_forth = <optimized out>
#5  0x00005646109f6548 in execute_command (_exec=_exec@entry=0x564612cdf870 "move to mark test", seat=0x5646126c4220, seat@entry=0x0, con=con@entry=0x0) at ../sway/sway/commands.c:286
        node = <optimized out>
        res = <optimized out>
        argc = 4
        argv = 0x564612ce8800
        handler = 0x564610a5a0c0 <command_handlers+160>
        cmd = <optimized out>
        matched_delim = 0 '\000'
        views = 0x0
        __PRETTY_FUNCTION__ = "execute_command"
        exec = 0x564612ce0870 "move to mark test"
        head = 0x0
        res_list = 0x564612502b30
#6  0x00005646109ff21c in ipc_client_handle_command (payload_type=<optimized out>, payload_length=<optimized out>, client=0x564612ce96f0) at ../sway/sway/ipc-server.c:634
        line = <optimized out>
        res_list = <optimized out>
        json = <optimized out>
        length = <optimized out>
        buf = 0x564612cdf870 "move to mark test"
        __PRETTY_FUNCTION__ = "ipc_client_handle_command"
        __PRETTY_FUNCTION__ = "ipc_client_handle_command"
#7  0x00005646109ff21c in ipc_client_handle_command (client=0x564612ce96f0, payload_length=17, payload_type=<optimized out>) at ../sway/sway/ipc-server.c:596
        __PRETTY_FUNCTION__ = "ipc_client_handle_command"
#8  0x00005646109fff29 in ipc_client_handle_readable (mask=<optimized out>, data=0x564612ce96f0, client_fd=108) at ../sway/sway/ipc-server.c:269
        pending_length = <optimized out>
        pending_type = <optimized out>
        read_available = 31
        buf = "i3-ipc\021\000\000\000\000\000\000"
        buf32 = 0x7fff07a85ae0
        received = <optimized out>
        client = 0x564612ce96f0
#9  0x00005646109fff29 in ipc_client_handle_readable (client_fd=108, mask=<optimized out>, data=0x564612ce96f0) at ../sway/sway/ipc-server.c:205
        client = 0x564612ce96f0
#10 0x00007fe6fc33a7f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#11 0x00007fe6fc33939c in wl_display_run () at /usr/lib/libwayland-server.so.0
#12 0x00005646109f558c in main (argc=1, argv=0x7fff07a85e78) at ../sway/sway/main.c:403
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x564610a3e47b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x564610a416d1 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x564610a3e480 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x564610a3e489 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x564610a3e3df "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x564610a3d57c "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x564610a3e48f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x564610a3e49e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x564610a3e4ae "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x564610a3e7e0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```
</details>

<details>
<summary>
`split &lt;layout&gt;` causes segfault on SPHSC context
</summary>

```
#0  0x0000556008d41d2c in arrange_workspace (workspace=workspace@entry=0x0) at ../sway/sway/tree/arrange.c:251
        output = <optimized out>
        area = <optimized out>
        first_arrange = <optimized out>
        prev_x = <optimized out>
        prev_y = <optimized out>
        diff_x = <optimized out>
        diff_y = <optimized out>
#1  0x0000556008d420f5 in arrange_workspace (workspace=workspace@entry=0x0) at ../sway/sway/tree/arrange.c:252
#2  0x0000556008d39671 in do_split (layout=2) at ../sway/sway/commands/split.c:33
        con = 0x55600a32bfe0
        ws = 0x0
#3  0x0000556008d0a6fb in execute_command (_exec=_exec@entry=0x55600a325e30 "[con_mark=test] split toggle", seat=0x556009d04210, seat@entry=0x0, con=con@entry=0x0) at ../sway/sway/commands.c:300
        view = <optimized out>
        res = <optimized out>
        i = 0
        fail_res = 0x0
        argc = 2
        argv = 0x55600a316c20
        handler = 0x556008d6e130 <command_handlers+272>
        cmd = <optimized out>
        matched_delim = 0 '\000'
        views = 0x55600a32e9e0
        __PRETTY_FUNCTION__ = "execute_command"
        exec = 0x55600a2037d0 "[con_mark=test] split toggle"
        head = 0x0
        res_list = 0x55600a31ff20
#4  0x0000556008d1321c in ipc_client_handle_command (payload_type=<optimized out>, payload_length=<optimized out>, client=0x55600a31df60) at ../sway/sway/ipc-server.c:634
        line = <optimized out>
        res_list = <optimized out>
        json = <optimized out>
        length = <optimized out>
        buf = 0x55600a325e30 "[con_mark=test] split toggle"
        __PRETTY_FUNCTION__ = "ipc_client_handle_command"
        __PRETTY_FUNCTION__ = "ipc_client_handle_command"
#5  0x0000556008d1321c in ipc_client_handle_command (client=0x55600a31df60, payload_length=28, payload_type=<optimized out>) at ../sway/sway/ipc-server.c:596
        __PRETTY_FUNCTION__ = "ipc_client_handle_command"
#6  0x0000556008d13f29 in ipc_client_handle_readable (mask=<optimized out>, data=0x55600a31df60, client_fd=108) at ../sway/sway/ipc-server.c:269
        pending_length = <optimized out>
        pending_type = <optimized out>
        read_available = 42
        buf = "i3-ipc\034\000\000\000\000\000\000"
        buf32 = 0x7ffdfc63a900
        received = <optimized out>
        client = 0x55600a31df60
#7  0x0000556008d13f29 in ipc_client_handle_readable (client_fd=108, mask=<optimized out>, data=0x55600a31df60) at ../sway/sway/ipc-server.c:205
        client = 0x55600a31df60
#8  0x00007f83a811e7f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#9  0x00007f83a811d39c in wl_display_run () at /usr/lib/libwayland-server.so.0
#10 0x0000556008d0958c in main (argc=1, argv=0x7ffdfc63ac98) at ../sway/sway/main.c:403
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x556008d5247b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x556008d556d1 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x556008d52480 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x556008d52489 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x556008d523df "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x556008d5157c "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x556008d5248f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x556008d5249e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x556008d524ae "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x556008d527e0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```
</details>

I feel like there might be more.

These segfaults all sort of had a common theme, so with this patch I changed `container_is_scratchpad_hidden` to also return true when the container is a child of a scratchpad hidden container. It seems semantically correct to me at least (a child of a scratchpad hidden container is also scratchpad hidden) and fixes the segfaults I found. I also changed `focus` to make SPHSCs visible on focus, as it does for normal split containers, to fix the originally reported segfault.

The change basically transforms segfault cases into "refusal" cases, i.e. the command returns failure after refusing to act. But some commands _could_ do something useful with a SPHSC. I've gone ahead and implemented `move to` for SPHSCs in the second commit, which is mostly some refactoring.

Possibly there could just be a different function `container_is_scratchpad_hidden_or_child` or something, but I looked through the existing uses and the new behavior seems accurate, or at least unharmful, everywhere it is in use.

PTAL.

EDIT: On second look, I'm wondering if the 'make SPHSCs visible again' bit belongs within root_scratchpad_show.

### CODE REVIEW

File: sway/commands/move.c [hunk 1]
```diff
@@ -550,17 +549,23 @@ static struct cmd_results *cmd_move_container(bool no_auto_back_and_forth,
...
-				"Expected output to have a workspace");
-	}
-	if (new_output_last_ws && new_output_last_ws != new_workspace) {
-		struct sway_node *new_output_last_focus =
-			seat_get_focus_inactive(seat, &new_output_last_ws->node);
-		seat_set_raw_focus(seat, new_output_last_focus);
+	struct sway_output *new_output = node_get_output(destination);
+	struct sway_workspace *new_output_last_ws = NULL;
+	if (new_output && old_output == new_output) {
+		new_output_last_ws = output_get_active_workspace(new_output);
```
Comment (RedSoxFan) [inline sway/commands/move.c]: This needs to be before the `container_move_to_{workspace,container}` calls. If the container is focused, the active workspace will be changed and this value won't be correct

File: sway/tree/container.c [hunk 2]
```diff
@@ -1520,5 +1520,9 @@ void container_raise_floating(struct sway_container *con) {
 }
 
 bool container_is_scratchpad_hidden(struct sway_container *con) {
-	return con->scratchpad && !con->workspace;
+	struct sway_container *target = con;
+	while (target->parent) {
```
Comment (RedSoxFan) [inline sway/tree/container.c]: This change breaks frame updates when running `fullscreen global` on a scratchpad hidden container

**Comment by edrex** [comment]
## tested

- [x] scratchpad shown on focus of hidden split scratchpad window

**Comment by RPigott** [comment]
Sorry for the extreme delay. I didn't pay much attention to development around the holidays and I wanted to fix the scale_filter stuff when I did.

Anyway, since it appears the first patch was not accurate in all cases, I've rewritten this without trying to be clever about the meaning of scratchpad_hidden, and use a new scratchpad_hidden_or_child function for the affected scenarios.

For the move command, I handle the SPHSC case early with the scratchpad case. That avoids whatever refactoring I was trying to do.

Would be nice to get these fixed for 1.3 I think. PTAL.

File: sway/commands/move.c [hunk 3]
```diff
@@ -248,12 +248,14 @@ static void container_move_to_container(struct sway_container *container,
...
+	if (destination->workspace) {
+		workspace_focus_fullscreen(destination->workspace);
 
-	// Update workspace urgent state
-	workspace_detect_urgent(destination->workspace);
-	if (old_workspace && old_workspace != destination->workspace) {
-		workspace_detect_urgent(old_workspace);
+		// Update workspace urgent state
+		workspace_detect_urgent(destination->workspace);
+		if (old_workspace && old_workspace != destination->workspace) {
```
Comment (RedSoxFan) [inline sway/commands/move.c]: This if block should not be inside the `if (destination->workspace)` block. Urgency should still be updated for `old_workspace` (if not `NULL`) even when `destination->workspace` is `NULL`

File: sway/commands/move.c [hunk 4]
```diff
@@ -507,9 +509,14 @@ static struct cmd_results *cmd_move_container(bool no_auto_back_and_forth,
...
 
-	if (destination->type == N_CONTAINER &&
-			container_is_scratchpad_hidden(destination->sway_container)) {
-		return cmd_move_to_scratchpad();
+	if (destination->type == N_CONTAINER) {
+		if (container_is_scratchpad_hidden(destination->sway_container)) {
+			return cmd_move_to_scratchpad();
+		}
+		if (container_is_scratchpad_hidden_or_child(destination->sway_container)) {
+			container_move_to_container(container, destination->sway_container);
```
Comment (RedSoxFan) [inline sway/commands/move.c]: This isn't sufficient. It does prevent the segfault, but the workspace is not arranged so there is a gap where the container was

File: sway/commands/move.c (hunk 3 above)
Comment (RPigott) [reply sway/commands/move.c]: Yep. Thanks.

File: sway/commands/move.c (hunk 4 above)
Comment (RPigott) [reply sway/commands/move.c]: Yeah I don't know what I was thinking here... New version handles it better hopefully, unrelated to the garbage in the first patch.

**Comment by RPigott** [comment]
For the `move to` crash, I no longer try to short circuit all the workspace focus/arrange logic, and just deal with the null scratchpad workspace/output as needed.

File: sway/commands/move.c [hunk 5]
```diff
@@ -519,8 +520,12 @@ static struct cmd_results *cmd_move_container(bool no_auto_back_and_forth,
 	}
 
 	struct sway_output *new_output = node_get_output(destination);
-	struct sway_workspace *new_output_last_ws = old_output == new_output ?
-		NULL : output_get_active_workspace(new_output);
+	struct sway_workspace *new_output_last_ws;
```
[the remark this answers is not in the document]
Comment (RPigott) [reply sway/commands/move.c]: Done. Thanks!

**Comment by RedSoxFan** [comment]
Thanks!
