### PR TITLE
Use parent get_root_coords in subsurfaces

### LINKED ISSUE #4191: [firefox] GTK popups such as tooltips/context menus flicker on surface commit
Firefox tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1548496

Some Firefox "popup" surfaces (context menus, tooltips, plugin popups) toggle between visible and invisible for every surface commit. The easiest way to reproduce is to open a context menu with right flick a few times, and then move the cursor around, with every pixel moved causing the state to toggle for some surfaces. It can sometimes take a few tries.

The issue was introduced when Firefox changed its popup handling to create windows with GDK_WINDOW_TYPE_HINT_POPUP_MENU on Wayland, calling gtk_window_set_transient_for to assign the popup to its parent. Before, it used for wayland GDK_WINDOW_TYPE_HINT_UTILITY. The change was introduced in response to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1532643, by this patch: https://phabricator.services.mozilla.com/D26112.

Tests:
- Sway: Flicker
- Rootston: OK
- Weston: OK
- GNOME: OK

WAYLAND_DEBUG for firefox, opening a context menu, moving the cursor while observing flicker, and then leaving the window:
```
[1420963,649] wl_pointer@3.motion(2139321, 19,292969, 2126,281250)
[1420963,798] wl_pointer@3.frame()
[1421395,778] wl_pointer@3.button(8692, 2139753, 273, 1)
[1421395,882] wl_pointer@3.frame()
[1421406,286]  -> wl_compositor@6.create_surface(new id wl_surface@62)
[1421406,310]  -> xdg_wm_base@20.create_positioner(new id xdg_positioner@73)
[1421406,315]  -> xdg_positioner@73.set_size(207, 262)
[1421406,320]  -> xdg_positioner@73.set_anchor_rect(21, 2128, 1, 1)
[1421406,328]  -> xdg_positioner@73.set_offset(0, 0)
[1421406,332]  -> xdg_positioner@73.set_anchor(5)
[1421406,335]  -> xdg_positioner@73.set_gravity(8)
[1421406,341]  -> xdg_positioner@73.set_constraint_adjustment(15)
[1421406,344]  -> xdg_wm_base@20.get_xdg_surface(new id xdg_surface@75, wl_surface@62)
[1421406,354]  -> xdg_surface@75.get_popup(new id xdg_popup@74, xdg_surface@30, xdg_positioner@73)
[1421406,362]  -> xdg_positioner@73.destroy()
[1421406,366]  -> wl_surface@62.commit()
[1421407,239]  -> wl_surface@62.frame(new id wl_callback@79)
[1421407,820] wl_display@1.delete_id(73)
[1421407,831] wl_surface@62.enter(wl_output@19)
[1421407,836] xdg_popup@74.configure(21, 1867, 207, 262)
[1421407,852] xdg_surface@75.configure(8693)
[1421407,860]  -> xdg_surface@75.ack_configure(8693)
[1421407,937]  -> wl_shm@4.create_pool(new id wl_shm_pool@73, fd 98, 216936)
[1421407,969]  -> wl_shm_pool@73.create_buffer(new id wl_buffer@51, 0, 207, 262, 828, 0)
[1421408,093]  -> wl_surface@62.attach(wl_buffer@51, 0, 0)
[1421408,102]  -> wl_surface@62.set_buffer_scale(1)
[1421408,106]  -> wl_surface@62.damage(0, 0, 207, 262)
[1421408,113]  -> xdg_surface@75.set_window_geometry(0, 0, 207, 262)
[1421408,134]  -> wl_surface@62.frame(new id wl_callback@77)
[1421408,140]  -> wl_surface@62.commit()
[1421408,433] wl_buffer@51.release()
[1421420,128] wl_display@1.delete_id(79)
[1421420,146] wl_display@1.delete_id(77)
[1421420,150] wl_callback@79.done(2139777)
[1421420,155] wl_callback@77.done(2139777)
[1421423,861]  -> wl_compositor@6.create_surface(new id wl_surface@77)
[1421423,893]  -> wl_subcompositor@37.get_subsurface(new id wl_subsurface@79, wl_surface@77, wl_surface@62)
[1421423,904]  -> wl_subsurface@79.set_position(0, 0)
[1421423,910]  -> wl_subsurface@79.set_desync()
[1421423,914]  -> wl_compositor@6.create_region(new id wl_region@59)
[1421423,921]  -> wl_surface@77.set_input_region(wl_region@59)
[1421423,927]  -> wl_region@59.destroy()
[1421423,932]  -> wl_surface@77.set_buffer_scale(1)
[1421423,937]  -> wl_surface@77.commit()
[1421423,952]  -> wl_surface@77.damage(0, 0, 207, 262)
[1421423,964]  -> wl_surface@77.frame(new id wl_callback@65)
[1421423,971]  -> wl_surface@77.set_buffer_scale(1)
[1421423,977]  -> wl_surface@77.attach(wl_buffer@54, 0, 0)
[1421423,986]  -> wl_surface@77.commit()
[1421424,366] wl_display@1.delete_id(59)
[1421426,266] wl_buffer@54.release()
[1421437,092] wl_display@1.delete_id(65)
[1421438,672] wl_callback@65.done(2139794)
[1421438,697]  -> wl_surface@77.damage(7, 239, 16, 17)
[1421438,713]  -> wl_surface@77.frame(new id wl_callback@65)
[1421438,732]  -> wl_surface@77.attach(wl_buffer@54, 0, 0)
[1421438,747]  -> wl_surface@77.commit()
[1421442,817] wl_buffer@54.release()
[1421453,943] wl_display@1.delete_id(65)
[1421455,157] wl_callback@65.done(2139811)
[1421492,039] wl_pointer@3.button(8694, 2139849, 273, 0)
[1421492,131] wl_pointer@3.frame()
[1422492,169] wl_pointer@3.leave(8695, wl_surface@28)
[1422492,249]  -> wl_pointer@3.set_cursor(8686, wl_surface@15, 1, 1)
[1422492,313]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1422492,357]  -> wl_surface@15.set_buffer_scale(1)
[1422492,380]  -> wl_surface@15.damage(0, 0, 10, 16)
[1422492,443]  -> wl_surface@15.commit()
[1422492,466] wl_pointer@3.frame()
[1422508,868] wl_surface@15.enter(wl_output@19)
[1422508,930]  -> wl_pointer@3.set_cursor(8686, wl_surface@15, 1, 1)
[1422508,983]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1422509,037]  -> wl_surface@15.set_buffer_scale(1)
[1422509,057]  -> wl_surface@15.damage(0, 0, 10, 16)
[1422509,103]  -> wl_surface@15.commit()
[1422509,124] wl_pointer@3.enter(8696, wl_surface@28, 19,292969, 2126,281250)
[1422509,193]  -> wl_pointer@3.set_cursor(8696, wl_surface@15, 1, 1)
[1422509,244]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1422509,292]  -> wl_surface@15.set_buffer_scale(1)
[1422509,313]  -> wl_surface@15.damage(0, 0, 10, 16)
[1422509,367]  -> wl_surface@15.commit()
[1422509,390] wl_pointer@3.frame()
[1422509,431] wl_pointer@3.motion(2140865, 18,675781, 2126,281250)
[1422509,492] wl_pointer@3.frame()
[1423509,309] wl_pointer@3.leave(8697, wl_surface@28)
[1423509,394]  -> wl_pointer@3.set_cursor(8696, wl_surface@15, 1, 1)
[1423509,460]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1423509,511]  -> wl_surface@15.set_buffer_scale(1)
[1423509,537]  -> wl_surface@15.damage(0, 0, 10, 16)
[1423509,586]  -> wl_surface@15.commit()
[1423509,609] wl_pointer@3.frame()
[1423821,194] wl_surface@15.enter(wl_output@19)
[1423821,257]  -> wl_pointer@3.set_cursor(8696, wl_surface@15, 1, 1)
[1423821,312]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1423821,364]  -> wl_surface@15.set_buffer_scale(1)
[1423821,388]  -> wl_surface@15.damage(0, 0, 10, 16)
[1423821,441]  -> wl_surface@15.commit()
[1423821,459] wl_pointer@3.enter(8698, wl_surface@28, 18,675781, 2126,281250)
[1423821,533]  -> wl_pointer@3.set_cursor(8698, wl_surface@15, 1, 1)
[1423821,608]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1423821,661]  -> wl_surface@15.set_buffer_scale(1)
[1423821,686]  -> wl_surface@15.damage(0, 0, 10, 16)
[1423821,790]  -> wl_surface@15.commit()
[1423821,809] wl_pointer@3.frame()
[1423821,858] wl_pointer@3.button(8699, 2142176, 273, 1)
[1423821,918] wl_pointer@3.frame()
[1423825,517]  -> xdg_popup@74.destroy()
[1423825,559]  -> xdg_surface@75.destroy()
[1423825,574]  -> wl_surface@62.destroy()
[1423825,595]  -> wl_buffer@51.destroy()
[1423825,612]  -> wl_shm_pool@73.destroy()
[1423825,713]  -> wl_subsurface@79.destroy()
[1423825,753]  -> wl_surface@77.destroy()
[1423827,984] wl_display@1.delete_id(74)
[1423828,003] wl_display@1.delete_id(75)
[1423828,024] wl_display@1.delete_id(62)
[1423828,029] wl_display@1.delete_id(51)
[1423828,052] wl_display@1.delete_id(73)
[1423828,056] wl_display@1.delete_id(79)
[1423828,060] wl_display@1.delete_id(77)
[1423915,691] wl_pointer@3.button(8700, 2142273, 273, 0)
[1423915,875] wl_pointer@3.frame()
[1424916,256] wl_pointer@3.leave(8701, wl_surface@28)
[1424916,332]  -> wl_pointer@3.set_cursor(8698, wl_surface@15, 1, 1)
[1424916,396]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1424916,448]  -> wl_surface@15.set_buffer_scale(1)
[1424916,474]  -> wl_surface@15.damage(0, 0, 10, 16)
[1424916,526]  -> wl_surface@15.commit()
[1424916,548] wl_pointer@3.frame()
[1425245,292] wl_surface@15.enter(wl_output@19)
[1425245,360]  -> wl_pointer@3.set_cursor(8698, wl_surface@15, 1, 1)
[1425245,419]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1425245,467]  -> wl_surface@15.set_buffer_scale(1)
[1425245,493]  -> wl_surface@15.damage(0, 0, 10, 16)
[1425245,537]  -> wl_surface@15.commit()
[1425245,556] wl_pointer@3.enter(8702, wl_surface@28, 18,675781, 2126,281250)
[1425245,641]  -> wl_pointer@3.set_cursor(8702, wl_surface@15, 1, 1)
[1425245,706]  -> wl_surface@15.attach(wl_buffer@52, 0, 0)
[1425245,788]  -> wl_surface@15.set_buffer_scale(1)
[1425245,805]  -> wl_surface@15.damage(0, 0, 10, 16)
[1425245,841]  -> wl_surface@15.commit()
[1425245,860] wl_pointer@3.frame()
[1425245,910] wl_pointer@3.motion(2143601, 18,046875, 2126,281250)
```

### PR DESCRIPTION
**Pull request by kennylevinsen**
Subsurfaces need access to the parent get_root_coords impl for positioning in
popups. To do this, we store a reference to the parent view_child where
applicable.

Fixes #4191.

### CODE REVIEW

**Comment by kennylevinsen** [comment]
Now only uses subsurface tree walking to calculate position if the parent view_child is not available. Otherwise, some subsurfaces where the original issue was not observed would end up with doubled offsets.

**Comment by kennylevinsen** [comment]
The parent/child view_child lifetime disconnect might need to be fixed sooner rather than later it seems.

The issue at hand there is that surfaces appear to be destroyed before their respective subsurfaces, which leads to dangling parent pointers.

**Comment by kennylevinsen** [comment]
Disconnect solved by tracking associated children so that the parent can remove the association if destroyed first.

File: sway/tree/view.c [hunk 1]
```diff
@@ -728,15 +728,22 @@ static void subsurface_get_root_coords(struct sway_view_child *child,
 	*root_sx = -child->view->geometry.x;
 	*root_sy = -child->view->geometry.y;
 
-	while (surface && wlr_surface_is_subsurface(surface)) {
-		struct wlr_subsurface *subsurface =
+	if (child->parent && child->parent->impl && child->parent->impl->get_root_coords) {
```
Comment (RedSoxFan) [inline sway/tree/view.c]: style: 80 column limit

File: include/sway/tree/view.h [hunk 2]
```diff
@@ -194,6 +194,8 @@ struct sway_view_child {
 	const struct sway_view_child_impl *impl;
 
 	struct sway_view *view;
+	struct sway_view_child *parent;
+	list_t *children;
```
Comment (RedSoxFan) [inline include/sway/tree/view.h]: nit: I think it would be better if this was a `struct wl_list`

Comment (kennylevinsen) [reply include/sway/tree/view.h]: I had gone by the mantra of "If you think you need a doubly linked list, you're wrong", but it does make child removal code much nicer, so I changed it.

File: sway/tree/view.c (hunk 1 above)
Comment (kennylevinsen) [reply sway/tree/view.c]: Fixed!

**Comment by kennylevinsen** [comment]
Ready again. Found a few additional style issues (indention and line length).

File: include/sway/tree/view.h [hunk 3]
```diff
@@ -192,8 +192,11 @@ struct sway_view_child_impl {
  */
 struct sway_view_child {
 	const struct sway_view_child_impl *impl;
+	struct wl_list parent_link;
```
Comment (RedSoxFan) [inline include/sway/tree/view.h]: Can you change this to just `link` for consistency with other struct definitions?

File: include/sway/tree/view.h [hunk 4]
```diff
@@ -192,8 +192,11 @@ struct sway_view_child_impl {
...
 
 	struct sway_view *view;
+	struct sway_view_child *parent;
+	struct wl_list children;
```
Comment (RedSoxFan) [inline include/sway/tree/view.h]: Can you add `// sway_view_child::link`?

File: include/sway/tree/view.h (hunk 3 above)
Comment (kennylevinsen) [reply include/sway/tree/view.h]: Sure. I had taken the naming from wlr_subsurface, but I see now that it was an outlier. Fixed.

File: include/sway/tree/view.h (hunk 4 above)
Comment (kennylevinsen) [reply include/sway/tree/view.h]: Fixed.

File: include/sway/tree/view.h (hunk 3 above)
Comment (emersion) [reply include/sway/tree/view.h]: Yeah, `wlr_subsurface` is very old, so it's not as consistent as other wlroots types. We should probably fix it at some point.

**Comment by RedSoxFan** [comment]
Thanks!

**Comment by MichaelAquilina** [comment]
Any chance this will be included in sway 1.1? This fixes a major issue for every firefox nightly user

**Comment by emersion** [comment]
Bugfixes are included.
