### PR TITLE
input: reset keyboard groups keyboard on reset all

### LINKED ISSUE #5029: Crash in handle_keyboard_repeat
`$swaymsg -t get_version`
`sway version 1.4`

[sway.1.log](https://github.com/swaywm/sway/files/4232504/sway.1.log)
[config.zip](https://github.com/swaywm/sway/files/4232519/config.zip)

coredumpctl gdb sway:
https://gist.github.com/dsreyes1014/ad1e2d7513e01f58e0fe398645b2b7c4

 bt full:
https://gist.github.com/dsreyes1014/7e9e0a1c1fbac03318e9965b8ae3750e

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #5029 

If the keyboard that triggers the reload binding is using the default
keymap, default repeat delay, and default repeat rate, the associated
keyboard group is never being destroyed on reload. This was causing the
keyboard group's keyboard not to get disarmed and result in a
use-after-free in handle_keyboard_repeat.

If the keyboard was not using the defaults for all three settings, then
it's associated keyboard group would get destroyed during the reset -
which did disarm the keyboard group's keyboard. In this case, the
use-after-free would not occur.

This adds a block to input_manager_reset_all_inputs that disarms the
keyboard for all keyboard groups in all seats. Since the inputs are all
being reset anyway, which will disarm all individual keyboards, it is
not necessary to be selective on which ones get disarmed.

### CODE REVIEW

File: sway/input/input-manager.c [hunk 1]
```diff
@@ -539,6 +541,18 @@ void input_manager_reset_all_inputs() {
...
+
+	// If there is at least one keyboard using the default keymap and repeat
+	// delay and rate, then it is possible that there is a keyboard group that
+	// needs to be disarmed. Since all inputs are being reset anyway, just
+	// disarm all of them.
+	struct sway_seat *seat;
+	wl_list_for_each(seat, &server.input->seats, link) {
+		struct sway_keyboard_group *group;
+		wl_list_for_each(group, &seat->keyboard_groups, link) {
+			sway_keyboard_disarm_key_repeat(group->seat_device->keyboard);
```
Comment (Xyene) [inline sway/input/input-manager.c:553]: This fixes the issue, thanks. One question is, should this also be calling `seat_configure_keyboard`? There are exit/re-enter events that it's not clear that this patch is sending (or, does it not matter for keyboard group keyboards?)

https://github.com/swaywm/sway/blob/726d187d3ce83431a2565cc1b423af99da5f7b6b/sway/input/seat.c#L700

**Comment by LaserEyess** [comment]
I can confirm this fixes #5167, previously the crash on reloading was 100% reproducible.

File: sway/input/input-manager.c (hunk 1 above)
Comment (RedSoxFan) [reply sway/input/input-manager.c]: I don't think it's strictly needed now, but may be for #4975 - which is related to keyboards being added/removed to a keyboard group. 

I changed it to call `seat_reset_device`, which is the same method normal input devices use, instead of just `sway_keyboard_disarm_key_repeat`. This required adding a condition in `seat_configure_keyboard` to not call `sway_keyboard_configure` for keyboard group keyboards.

**Comment by LaserEyess** [comment]
I rebuilt sway with the new patch, and I'm still getting the same crash as in #5167. Repeatedly calling `reload` using a keybind triggers it. Sometimes you have to do it for 5 seconds, sometimes 30 seconds.

**Comment by RedSoxFan** [comment]
> I rebuilt sway with the new patch, and I'm still getting the same crash as in #5167. Repeatedly calling `reload` using a keybind triggers it. Sometimes you have to do it for 5 seconds, sometimes 30 seconds.

Oops. Should be fixed now.

**Comment by LaserEyess** [comment]
Ok, after repeated attempts with a clean config, I can't get it to crash again. Spent about 3 minutes trying.
