### PR TITLE
input/cursor: keep reference to cursor in constraint

### LINKED ISSUE #5386: Null pointer dereference in handle_pointer_constraint_set_region
Ref https://github.com/swaywm/sway/commit/34e0cad9acd88ccf18fc24d6917520cfc819abc1

cc @Xyene 

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==11662==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x5571603bf34a bp 0x7fff0d8ba750 sp 0x7fff0d8ba710 T0)
==11662==The signal is caused by a READ memory access.
==11662==Hint: address points to the zero page.
    #0 0x5571603bf34a in handle_pointer_constraint_set_region ../sway/input/cursor.c:837
    #1 0x7f8f4f4f3770 in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #2 0x7f8f4f4b64b6 in pointer_constraint_commit ../subprojects/wlroots/types/wlr_pointer_constraints_v1.c:132
    #3 0x7f8f4f4b6510 in handle_surface_commit ../subprojects/wlroots/types/wlr_pointer_constraints_v1.c:140
    #4 0x7f8f4f4f3770 in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #5 0x7f8f4f4d0c7e in surface_commit_pending ../subprojects/wlroots/types/wlr_surface.c:379
    #6 0x7f8f4f4d188d in surface_commit ../subprojects/wlroots/types/wlr_surface.c:448
    #7 0x7f8f4d645a8c  (/usr/lib/libffi.so.7+0x6a8c)
    #8 0x7f8f4d64501a  (/usr/lib/libffi.so.7+0x601a)
    #9 0x7f8f4e9d7f61  (/usr/lib/libwayland-server.so.0+0xcf61)
    #10 0x7f8f4e9d42db  (/usr/lib/libwayland-server.so.0+0x92db)
    #11 0x7f8f4e9d5fa9 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xafa9)
    #12 0x7f8f4e9d44e6 in wl_display_run (/usr/lib/libwayland-server.so.0+0x94e6)
    #13 0x557160360f7d in server_run ../sway/server.c:225
    #14 0x55716035d24c in main ../sway/main.c:409
    #15 0x7f8f4de40001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #16 0x55716032261d in _start (/home/simon/src/sway/build/sway/sway+0x31961d)
```

### PR DESCRIPTION
**Pull request by Xyene**
`set_region` accepts a `NULL` `*data`, so we can't use it to reference the constraint and find the cursor through its seat.

Fixes #5386.

/cc @emersion, sorry about that, don't know how this didn't fail during my testing...

I've tested this PR with:

```
$ wlroots/build/examples/pointer-constraints confine persistent disjoint-region
```

...and clicked a couple of times to observe `set_region` calls while running with ASan.

An alternative fix is in wlroots, but I recall we didn't want to add a non-`NULL` data parameter to `set_region` yet.

```diff
diff --git a/include/wlr/types/wlr_pointer_constraints_v1.h b/include/wlr/types/wlr_pointer_constraints_v1.h
index 0c49e3bf..d99b92f7 100644
--- a/include/wlr/types/wlr_pointer_constraints_v1.h
+++ b/include/wlr/types/wlr_pointer_constraints_v1.h
@@ -60,6 +60,8 @@ struct wlr_pointer_constraint_v1 {
                /**
                 * Called when a pointer constraint's region is updated,
                 * post-surface-commit.
+                *
+                * data: struct wlr_pointer_constraint_v1 *
                 */
                struct wl_signal set_region;
                struct wl_signal destroy;
diff --git a/types/wlr_pointer_constraints_v1.c b/types/wlr_pointer_constraints_v1.c
index eca45984..36c0a359 100644
--- a/types/wlr_pointer_constraints_v1.c
+++ b/types/wlr_pointer_constraints_v1.c
@@ -129,7 +129,7 @@ static void pointer_constraint_commit(
        }
 
        if (updated_region) {
-               wlr_signal_emit_safe(&constraint->events.set_region, NULL);
+               wlr_signal_emit_safe(&constraint->events.set_region, constraint);
        }
 }
```

### CODE REVIEW

File: sway/input/cursor.c [hunk 1]
```diff
@@ -835,7 +835,7 @@ static void handle_pointer_constraint_set_region(struct wl_listener *listener,
 		wl_container_of(listener, sway_constraint, set_region);
 	struct wlr_pointer_constraint_v1 *constraint = data;
```
Comment (emersion) [inline sway/input/cursor.c:836]: Let's remove these two declarations.

**Comment by emersion** [comment]
>An alternative fix is in wlroots, but I recall we didn't want to add a non-NULL data parameter to set_region yet.

Yes. I'd like to make most `data` pointers NULL to make the API more extensible.

**Comment by emersion** [comment]
Also this PR removes a bunch of `void *` implicit casts, that's a good thing.

File: sway/input/cursor.c (hunk 1 above)
Comment (Xyene) [reply sway/input/cursor.c]: Ah yes, those were there to test the wlroots patch version... removed.
