### PR TITLE
Fix sway crashes for scratchpad layouts

### LINKED ISSUE #4240: Sway crashes when splitting or changing the layout of the scrach window.
**Sway version:**

sway version 1.1-rc1-32-g4d93b96b (Jun  9 2019, branch 'master')

**Problem:**

It seems that the scratchpad window does not support regular window operations (splits, tabbed layout, nesting etc.). Whenever I open a scratch window and try to nest some splits inside it, sway either crashes or behaves oddly (e.g. the scratch window gets much smaller). Has anyone experienced the same thing? And could someone try to reproduce the issue by splitting, nesting, changing layout (tabbed,stacked,split) inside the scratch window I'm curious if it's just my setup? P.S. I'll try to produce some debug logs if needed.

**Stack trace:**
```
(gdb) bt full
#0  0x000055f2536d5846 in arrange_workspace (workspace=0x0) at ../sway/sway/tree/arrange.c:183
        output = 0x0
        area = 0x55f254f9ab90
        first_arrange = 85
        prev_x = 6.9533118000079448e-310
        prev_y = 4.6688842958101473e-310
        diff_x = 4.6688859539108083e-310
        diff_y = 4.668885575677865e-310
#1  0x000055f2536dbc73 in root_scratchpad_hide (con=0x55f2556e7bf0) at ../sway/sway/tree/root.c:161
        seat = 0x55f254f9ae90
        focus = 0x55f255006030
        ws = 0x0
#2  0x000055f2536ca19f in scratchpad_toggle_auto () at ../sway/sway/commands/scratchpad.c:34
        seat = 0x55f254f9ae90
        focus = 0x55f2556e7bf0
        ws = 0x55f255006030
        __PRETTY_FUNCTION__ = "scratchpad_toggle_auto"
        con = 0x100000002
#3  0x000055f2536ca5fa in cmd_scratchpad (argc=1, argv=0x55f25580f218) at ../sway/sway/commands/scratchpad.c:127
        error = 0x0
#4  0x000055f2536908d0 in execute_command (_exec=0x55f254fcf040 "scratchpad show, resize set 1420 980", seat=0x55f254f9ae90, con=0x0) at ../sway/sway/commands.c:293
        node = 0x55f255006030
        res = 0x0
        argc = 2
        argv = 0x55f25580f210
        handler = 0x55f253706470 <command_handlers+240>
        res_list = 0x55f25580dcf0
        exec = 0x55f2556dee70 "scratchpad show"
        head = 0x0
        cmdlist = 0x55f2556dee80 " resize set 1420 980"
        cmd = 0x55f2556dee70 "scratchpad show"
        views = 0x0
        __PRETTY_FUNCTION__ = "execute_command"
#5  0x000055f2536bf492 in seat_execute_command (seat=0x55f254f9ae90, binding=0x55f254fe0130) at ../sway/sway/commands/bind.c:577
        con = 0x0
        res_list = 0x0
        success = 202
#6  0x000055f2536b7feb in handle_keyboard_key (listener=0x55f255756b60, data=0x7fffcae89450) at ../sway/sway/input/keyboard.c:396
        keyboard = 0x55f255756b50
        seat = 0x55f254f9ae90
        wlr_seat = 0x55f254f9afc0
        wlr_device = 0x55f2557508d0
        device_identifier = 0x55f255739fc0 "1:1:AT_Translated_Set_2_keyboard"
        event = 0x7fffcae89450
        input_inhibited = false
        keycode = 65
        raw_keysyms = 0x55f25576a188
        raw_modifiers = 32
        raw_keysyms_len = 1
        translated_keysyms = 0x55f25576a188
        translated_modifiers = 32
        translated_keysyms_len = 1
        code_modifiers = 32
        handled = false
```

### PR DESCRIPTION
**Pull request by Emantor**
Currently container_replace removes the container from the scratchpad
and re-adds it afterwards. For the split commands this results in the
container being send to the scratchpad, which results in a NULL segfault
if the same container should be shown.
Pass an optional workspace to root_scratchpad_add_container, if the
workspace is passed the window will continue to show on the workspace.
If NULL is passed it is sent to the scratchpad.
This was an issue if no other window except the scratchpad container was
on the workspace.

Fixes #4240

### CODE REVIEW

File: include/sway/tree/root.h [hunk 1]
```diff
@@ -46,8 +46,12 @@ void root_destroy(struct sway_root *root);
 
 /**
  * Move a container to the scratchpad.
+ * If a workspace is passed, the container is assumed to have been in
+ * the scratchpad before and is shown on the workspace.
+ * The ws parameter can safely be NULL.
  */
-void root_scratchpad_add_container(struct sway_container *con);
+void root_scratchpad_add_container(struct sway_container *con,
+								   struct sway_workspace *ws);
```
Comment (ddevault) [inline include/sway/tree/root.h]: style: don't align args with the opening paren, just indent once

Comment (Emantor) [reply include/sway/tree/root.h]: will fix.

**Comment by ddevault** [comment]
Thanks!
