### PR TITLE
input/seatop_default: release on empty workspace

### LINKED ISSUE #3932: wl_data_source.cancelled not sent when dropping outside any surface
* Sway Version: 1.0

* Reproduction Steps:

1. start weston-dnd, make it floating
2. drag to outside of weston-dnd and release mouse

### PR DESCRIPTION
**Pull request by Emantor**
Instead of handling presses and releases on empty workspaces as setting
focus to the workspace, handle releases by notifying the seat of a
pointer action. This way DnDs are correctly released if the button is
released over an empty workspace.

Fixes #3932

### CODE REVIEW

File: sway/input/seatop_default.c [hunk 1]
```diff
@@ -279,8 +279,12 @@ static void handle_button(struct sway_seat *seat, uint32_t time_msec,
 	}
 
 	// Handle clicking an empty workspace
-	if (node && node->type == N_WORKSPACE) {
-		seat_set_focus(seat, node);
+	if (node && node->type == N_WORKSPACE ) {
+		if ( state == WLR_BUTTON_PRESSED) {
```
Comment (emersion) [inline sway/input/seatop_default.c:283]: Style: stray space here

File: sway/input/seatop_default.c [hunk 2]
```diff
@@ -279,8 +279,12 @@ static void handle_button(struct sway_seat *seat, uint32_t time_msec,
...
+			seat_set_focus(seat, node);
+		} else {
+			seat_pointer_notify_button(seat, time_msec, button, state);
```
Comment (emersion) [inline sway/input/seatop_default.c:286]: Hmm, we should probably call `seat_pointer_notify_button` unconditionally here?

File: sway/input/seatop_default.c [hunk 3]
```diff
@@ -279,8 +279,12 @@ static void handle_button(struct sway_seat *seat, uint32_t time_msec,
 	}
 
 	// Handle clicking an empty workspace
-	if (node && node->type == N_WORKSPACE) {
-		seat_set_focus(seat, node);
+	if (node && node->type == N_WORKSPACE ) {
```
Comment (emersion) [inline sway/input/seatop_default.c:282]: Style: another stray space here

File: sway/input/seatop_default.c (hunk 2 above)
Comment (Emantor) [reply sway/input/seatop_default.c]: In that case I simply removed the return from the function, `handle_button()` will call `seat_pointer_notify_button()` at the very end, and none of the other functions should run on empty workspaces. Pushed the new version.

**Comment by emersion** [comment]
Hmm. Why the `state == WLR_BUTTON_PRESSED` check?

I'm a little worried about removing that `return`. This is inconsistent with the rest of the function.

**Comment by Emantor** [comment]
> Hmm. Why the `state == WLR_BUTTON_PRESSED` check?

The comment states that focus should change on click, not on release.

> I'm a little worried about removing that `return`. This is inconsistent with the rest of the function.

IMO this function and the pointer handling will require more cleanups to fix all issues with DnD. But I did not have the time to do a deeper analysis. I can change this back to include the return.

**Comment by emersion** [comment]
>I can change this back to include the return.

I'd prefer to keep this if branch consistent with the rest of the function. It can be surprising that all if branches `return` except this one.

**Comment by Emantor** [comment]
Pushed a version which includes the return.
