### PR TITLE
Fix jumping views

### LINKED ISSUE #2490: Floating gnome-calculator moves by itself
1. Open gnome-calculator
2. Make it float
3. Switch focus, it'll move

Similar to https://github.com/swaywm/sway/pull/2466#issuecomment-414039753

### PR DESCRIPTION
**Pull request by RyanDwyer**
Fixes #2490.

To be honest I'm not sure why this fixes the issue.

I observed that I could only make the view jump if I resized it to the smallest possible size first. Then I had a suspicion that we were accidentally factoring in the title and border sizes into the view size when it uses CSD. So I changed that and it appears to have fixed the jumping issue.

I guess when we factor the title and borders in, we send a configure to the surface with a size smaller than the minimum, and it comes back with a surface at the minimum size. We interpret this as an unexpected resize, and this somehow makes it jump.

### CODE REVIEW

File: sway/tree/view.c [hunk 1]
```diff
@@ -236,7 +236,12 @@ void view_autoconfigure(struct sway_view *view) {
 		view->border_top = false;
 	}
 
-	switch (view->border) {
+	enum sway_container_border border = view->border;
+	if (view->using_csd) {
```
Comment (emersion) [inline sway/tree/view.c]: Maybe switching CSD should also change `view->border` and save the previous value in `saved_border`? (I think https://github.com/swaywm/sway/issues/2491 is due to this as well)

Comment (RyanDwyer) [reply sway/tree/view.c]: If we did that then we'd have to change the `border` command so it either ignores the command or writes to `view->saved_border` if CSD is in effect. But on the other hand, at the moment the rendering code has to check the `using_csd` value and omit the borders if so. I'm not sure which is best.

**Comment by emersion** [comment]
Thanks!
