### PR TITLE
output_get_active_workspace: check workspaces length

### LINKED ISSUE #3043: segfault in cursor_rebase on startup
*  sway version

sway version 1.0-beta.1-116-ge21a2334 (oct 31 2018, branch 'master')

* after some help at irc, I was instructed to open this issue with the related [stack trace](https://pastebin.com/DtTw8wKy).

Thank you very much and please let me know if some other information is needed.

### LINKED ISSUE #3654: Crash in container_is_transient_for when undocking
Seems like there are NULL elements in `workspace->current.floating`.

```
#0  0x000055c17b234a53 in container_is_transient_for (child=0x0, ancestor=0x55c17de52228) at ../sway/tree/container.c:1310
#1  0x000055c17b204d31 in output_render (output=0x55c17d9a3260, when=0x7fff94169290, damage=0x7fff941692a0) at ../sway/desktop/render.c:1021
        floater = 0x0
        i = 6
        clear_color = {0, 0, 0, 1}
        nrects = 1
        rects = 0x7fff941692a0
        wlr_output = 0x55c17dab13b0
        renderer = 0x55c17d4eb470
        __PRETTY_FUNCTION__ = "output_render"
        workspace = 0x55c17de158a0
        fullscreen_con = 0x55c17de52228
        seat = 0x200000002
        focus = 0x64000000000
        width = 0
        height = 1
        transform = 32767
#2  0x000055c17b2010ac in damage_handle_frame (listener=0x55c17d9a33d8, data=0x55c17d9a3420) at ../sway/desktop/output.c:386
        output = 0x55c17d9a3260
        now = {tv_sec = 369520, tv_nsec = 289829890}
        needs_swap = true
        damage = {extents = {x1 = 0, y1 = 0, x2 = 1600, y2 = 900}, data = 0x0}
#3  0x00007f13e3580fd5 in wlr_signal_emit_safe (signal=0x55c17d9a3480, data=0x55c17d9a3420) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55c17d9a33d8
        l = 0x55c17d9a33d8
        cursor = {link = {prev = 0x55c17d9a33d8, next = 0x7fff94169310}, notify = 0x7f13e3580f1f <handle_noop>}
        end = {link = {prev = 0x7fff941692f0, next = 0x55c17d9a3480}, notify = 0x7f13e3580f1f <handle_noop>}
#4  0x00007f13e356dbbe in output_handle_frame (listener=0x55c17d9a3518, data=0x55c17dab13b0) at ../subprojects/wlroots/types/wlr_output_damage.c:50
        output_damage = 0x55c17d9a3420
#5  0x00007f13e3580fd5 in wlr_signal_emit_safe (signal=0x55c17dab14d0, data=0x55c17dab13b0) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55c17d9a3518
        l = 0x55c17d9a3518
        cursor = {link = {prev = 0x55c17d9a3518, next = 0x7fff941693b0}, notify = 0x7f13e3580f1f <handle_noop>}
        end = {link = {prev = 0x7fff94169390, next = 0x55c17dab14d0}, notify = 0x7f13e3580f1f <handle_noop>}
#6  0x00007f13e3570af1 in wlr_output_send_frame (output=0x55c17dab13b0) at ../subprojects/wlroots/types/wlr_output.c:417
#7  0x00007f13e35328dd in page_flip_handler (fd=9, seq=8639132, tv_sec=369520, tv_usec=252633, data=0x55c17dab13b0) at ../subprojects/wlroots/backend/drm/drm.c:1305
        conn = 0x55c17dab13b0
        drm = 0x55c17d20e5f0
        present_time = {tv_sec = 369520, tv_nsec = 252633000}
        present_event = {output = 0x55c17dab13b0, when = 0x7fff94169430, seq = 8639132, refresh = 16656950, flags = 7}
#8  0x00007f13e2988725 in drmHandleEvent () at /lib64/libdrm.so.2
#9  0x00007f13e3532962 in handle_drm_event (fd=9, mask=1, data=0x0) at ../subprojects/wlroots/backend/drm/drm.c:1315
        event = {version = 2, vblank_handler = 0x0, page_flip_handler = 0x7f13e3532774 <page_flip_handler>, page_flip_handler2 = 0x0, sequence_handler = 0x0}
#10 0x00007f13e2ec8dd2 in wl_event_loop_dispatch (loop=0x55c17d1fef10, timeout=<optimized out>) at src/event-loop.c:641
        ep = 
              {{events = 1, data = {ptr = 0x55c17d2219a0, fd = 2099386784, u32 = 2099386784, u64 = 94289516435872}}, {events = 4, data = {ptr = 0x55c17df898a0, fd = 2113444000, u3--Type <RET> for more, q to quit, c to continue without paging--
2 = 2113444000, u64 = 94289530493088}}, {events = 4, data = {ptr = 0x55c17df55120, fd = 2113229088, u32 = 2113229088, u64 = 94289530278176}}, {events = 1, data = {ptr = 0x55c17dd0aad0, fd = 2110827216, u32 = 2110827216, u64 = 94289527876304}}, {events = 1, data = {ptr = 0x55c17dd0a7a0, fd = 2110826400, u32 = 2110826400, u64 = 94289527875488}}, {events = 1, data = {ptr = 0x55c17dd0a250, fd = 2110825040, u32 = 2110825040, u64 = 94289527874128}}, {events = 1, data = {ptr = 0x55c17dd09c50, fd = 2110823504, u32 = 2110823504, u64 = 94289527872592}}, {events = 1, data = {ptr = 0x55c17dd101e0, fd = 2110849504, u32 = 2110849504, u64 = 94289527898592}}, {events = 1, data = {ptr = 0x55c17dbdb750, fd = 2109585232, u32 = 2109585232, u64 = 94289526634320}}, {events = 1, data = {ptr = 0x55c17ddf9680, fd = 2111805056, u32 = 2111805056, u64 = 94289528854144}}, {events = 1, data = {ptr = 0x55c17de07150, fd = 2111861072, u32 = 2111861072, u64 = 94289528910160}}, {events = 1, data = {ptr = 0x55c17df602b0, fd = 2113274544, u32 = 2113274544, u64 = 94289530323632}}, {events = 1, data = {ptr = 0x55c17de24800, fd = 2111981568, u32 = 2111981568, u64 = 94289529030656}}, {events = 1, data = {ptr = 0x55c17de1cac0, fd = 2111949504, u32 = 2111949504, u64 = 94289528998592}}, {events = 1, data = {ptr = 0x55c17e030240, fd = 2114126400, u32 = 2114126400, u64 = 94289531175488}}, {events = 1, data = {ptr = 0x55c17e015170, fd = 2114015600, u32 = 2114015600, u64 = 94289531064688}}, {events = 1, data = {ptr = 0x55c17dc2a930, fd = 2109909296, u32 = 2109909296, u64 = 94289526958384}}, {events = 1, data = {ptr = 0x55c17de5d930, fd = 2112215344, u32 = 2112215344, u64 = 94289529264432}}, {events = 1, data = {ptr = 0x55c17e06fb70, fd = 2114386800, u32 = 2114386800, u64 = 94289531435888}}, {events = 1, data = {ptr = 0x55c17e085a60, fd = 2114476640, u32 = 2114476640, u64 = 94289531525728}}, {events = 1, data = {ptr = 0x55c17dd100d0, fd = 2110849232, u32 = 2110849232, u64 = 94289527898320}}, {events = 21953, data = {ptr = 0x55c17dde5b30, fd = 2111724336, u32 = 2111724336, u64 = 94289528773424}}, {events = 2111724288, data = {ptr = 0x7df60d48000055c1, fd = 21953, u32 = 21953, u64 = 9076456701900641729}}, {events = 21953, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2111724384, data = {ptr = 0xe2ec6587000055c1, fd = 21953, u32 = 21953, u64 = 16351555977570440641}}, {events = 32531, data = {ptr = 0x55c17df60d40, fd = 2113277248, u32 = 2113277248, u64 = 94289530326336}}, {events = 69807360, data = {ptr = 0x94169ad4ab78bec0, fd = -1418150208, u32 = 2876817088, u64 = 10670886605301530304}}, {events = 32767, data = {ptr = 0xab78bec004292d00, fd = 69807360, u32 = 69807360, u64 = 12355835309603761408}}, {events = 69807360, data = {ptr = 0x7de751f0ab78bec0, fd = -1418150208, u32 = 2876817088, u64 = 9072310068471971520}}, {events = 21953, data = {ptr = 0x7fff94169b50, fd = -1810457776, u32 = 2484509520, u64 = 140735677897552}}, {events = 2113146512, data = {ptr = 0x94169c90000055c1, fd = 21953, u32 = 21953, u64 = 10670888509390214593}}, {events = 32767, data = {ptr = 0x55c17de75228, fd = 2112311848, u32 = 2112311848, u64 = 94289529360936}}}
        count = 21
        i = <optimized out>
        source = 0x0
#11 0x00007f13e2ec6dbd in wl_display_run (display=0x55c17d201700) at src/wayland-server.c:1260
#12 0x000055c17b1fdfb3 in server_run (server=0x55c17b25ed20 <server>) at ../sway/server.c:212
#13 0x000055c17b1fd4fc in main (argc=1, argv=0x7fff94169c98) at ../sway/main.c:395
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55c17b245e20 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55c17b245e25 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55c17b245e2c "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55c17b245e35 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55c17b245e3b "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55c17b245e43 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55c17b245e4b "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55c17b245e5a "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55c17b245e6a "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55c17b245938 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

### LINKED ISSUE #3658: Segmentation fault in output_render
```
#0  0x000055d86bbbcc94 in output_render (output=0x55d86c2bbca0, when=0x7ffc1f747310, damage=0x7ffc1f747320)
    at ../sway/desktop/render.c:1006
        clear_color = {0, 0, 0, 1}
        nrects = 1
        rects = 0x7ffc1f747320
        wlr_output = 0x55d86be62400
        renderer = 0x55d86be4ee20
        __PRETTY_FUNCTION__ = "output_render"
        workspace = 0x55d86c436390
        fullscreen_con = 0x3f00000077e
        seat = 0x0
        focus = 0x7ffc00000002
        width = 527725168
        height = 1
        transform = 32764
#1  0x000055d86bbb9100 in damage_handle_frame (listener=0x55d86c2bbe18, data=0x55d86c2bbe60)
    at ../sway/desktop/output.c:386
        output = 0x55d86c2bbca0
        now = {tv_sec = 244029, tv_nsec = 491214679}
        needs_swap = true
        damage = {extents = {x1 = 0, y1 = 0, x2 = 1920, y2 = 1080}, data = 0x0}
#2  0x00007fd4d7163795 in wlr_signal_emit_safe (signal=0x55d86c2bbec0, data=0x55d86c2bbe60)
    at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55d86c2bbe18
        l = 0x55d86c2bbe18
        cursor = {link = {prev = 0x55d86c2bbe18, next = 0x7ffc1f747390}, notify = 0x7fd4d71636df <handle_noop>}
        end = {link = {prev = 0x7ffc1f747370, next = 0x55d86c2bbec0}, notify = 0x7fd4d71636df <handle_noop>}
#3  0x00007fd4d715037e in output_handle_frame (listener=0x55d86c2bbf58, data=0x55d86be62400)
    at ../subprojects/wlroots/types/wlr_output_damage.c:50
        output_damage = 0x55d86c2bbe60
#4  0x00007fd4d7163795 in wlr_signal_emit_safe (signal=0x55d86be62520, data=0x55d86be62400)
    at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55d86c2bbf58
        l = 0x55d86c2bbf58
        cursor = {link = {prev = 0x55d86c2bbf58, next = 0x7ffc1f747430}, notify = 0x7fd4d71636df <handle_noop>}
        end = {link = {prev = 0x7ffc1f747410, next = 0x55d86be62520}, notify = 0x7fd4d71636df <handle_noop>}
#5  0x00007fd4d71532b1 in wlr_output_send_frame (output=0x55d86be62400)
    at ../subprojects/wlroots/types/wlr_output.c:417
#6  0x00007fd4d71148dd in page_flip_handler (fd=9, seq=625211574, tv_sec=244029, tv_usec=395845, data=0x55d86be62400)
    at ../subprojects/wlroots/backend/drm/drm.c:1305
        conn = 0x55d86be62400
        drm = 0x55d86bcd0210
        present_time = {tv_sec = 244029, tv_nsec = 395845000}
        present_event = 
          {output = 0x55d86be62400, when = 0x7ffc1f7474b0, seq = 625211574, refresh = 16661112, flags = 7}
#7  0x00007fd4d6767725 in drmHandleEvent () at /usr/lib/libdrm.so.2
#8  0x00007fd4d7114962 in handle_drm_event (fd=9, mask=1, data=0x0) at ../subprojects/wlroots/backend/drm/drm.c:1315
        event = 
    {version = 2, vblank_handler = 0x0, page_flip_handler = 0x7fd4d7114774 <page_flip_handler>, page_flip_handler2 = 0x0, sequence_handler = 0x0}
#9  0x00007fd4d6aaa702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#10 0x00007fd4d6aa92ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#11 0x000055d86bbb6007 in server_run (server=0x55d86bc16d20 <server>) at ../sway/server.c:212
#12 0x000055d86bbb5550 in main (argc=1, argv=0x7ffc1f747d08) at ../sway/main.c:403
        verbose = 0
        debug = 0
--Type <RET> for more, q to quit, c to continue without paging--
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55d86bbfde70 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55d86bbfde75 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55d86bbfde7c "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55d86bbfde85 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55d86bbfde8b "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55d86bbfde93 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55d86bbfde9b "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55d86bbfdeaa "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55d86bbfdeba "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55d86bbfd938 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

Looks like the workspace->current is broken:
```
(gdb) p workspace->current
$2 = {fullscreen = 0x3f00000077e, x = 2.138971758237648e-311, y = 2.151703732986404e-311, width = 90, height = 1014, 
  layout = 172, output = 0x3f600000778, floating = 0x4180000077e, tiling = 0x41800000778, 
  focused_inactive_child = 0x41e0000077e, focused = 16}
(gdb) p workspace->current.fullscreen
$3 = (struct sway_container *) 0x3f00000077e
```

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #3658 
Fixes #3654 
Fixes #3043 

If an output's node was dirty and the transaction was committed before a
workspace was moved to or created for the output, the instruction would
have a bad value for `state->active_workspace` due to a missing
length check in `output_get_active_workspace`. If there was no focus on
the output, the first workspace was being returned. If the workspace
list was currently empty, the value was either garbage, or in the case of
an output being disabled and re-enabled, a workspace that may have been
previously freed. This just adds the length check to avoid returning out
of bounds value.

### CODE REVIEW

**Comment by ddevault** [comment]
Thanks!

File: sway/desktop/output.c [hunk 1]
```diff
@@ -320,6 +320,9 @@ struct sway_workspace *output_get_active_workspace(struct sway_output *output) {
 	struct sway_seat *seat = input_manager_current_seat();
 	struct sway_node *focus = seat_get_active_tiling_child(seat, &output->node);
 	if (!focus) {
+		if (!output->workspaces->length) {
+			return NULL;
```
Comment (emersion) [inline sway/desktop/output.c]: Are all `output_get_active_workspace` callers expecting a NULL return value?

Comment (RedSoxFan) [reply sway/desktop/output.c]: https://github.com/swaywm/sway/pull/3744
