### PR TITLE
cmd_bindswitch: add option to execute on reload

### LINKED ISSUE #4305: Output config reloads with 'swaymsg reload'
NVIDIA: no
version: 1.1-rc1-47-gb59139c2 (Jun 22 2019, branch 'master')
configuration file: https://gist.github.com/jasperro/aa237e0201885970f5cec45d513f11f5

When I run `swaymsg reload` and my laptop lid is closed, the laptop display is enabled again, which is not what I want. I don't know if this is a bug, or an intended feature.

I tried adding `exec_always cat /proc/acpi/button/lid/LID0/state | awk '{print $2}' | grep -q 'closed' && swaymsg output 'Unknown 0x1E3D 0x00000000' toggle &` to the end of my config file, which works, but crashes alacritty (terminal) and breaks right-click menus in firefox.

My proposal is to only load output configuration on first start and not reload it after that.

### PR DESCRIPTION
**Pull request by RedSoxFan**
Closes #4305

This adds a --reload flag to cmd_bindswitch that allows for the binding
to be executed on reload. One possible use case for this is to  allow
users to disable outputs when the lid closes and enable them when the
lid opens without having to open and re-close the lid after a reload.

### CODE REVIEW

File: include/sway/input/switch.h [hunk 1]
```diff
@@ -5,6 +5,8 @@
 
 struct sway_switch {
     struct sway_seat_device *seat_device;
```
Comment (emersion) [inline include/sway/input/switch.h]: Unrelated note: seems like this file is using mixed tabs and spaces

Comment (RedSoxFan) [reply include/sway/input/switch.h]: Not anymore. All tabs now
