### PR TITLE
Fix layer surface segfault on output destroy

### LINKED ISSUE #1877: Disabling an output makes Sway crash
```
#0  0x000056025d7e5496 in arrange_output (output=0x56025fefa930) at ../sway/tree/arrange.c:55
55		for (int i = 0; i < output->children->length; ++i) {
(gdb) bt
#0  0x000056025d7e5496 in arrange_output (output=0x56025fefa930) at ../sway/tree/arrange.c:55
#1  0x000056025d7ce3ee in arrange_layers (output=0x56025fefa700) at ../sway/desktop/layer_shell.c:179
#2  0x000056025d7cf1ec in handle_destroy (listener=0x56025fded398, data=0x56025fde80c0) at ../sway/desktop/layer_shell.c:277
#3  0x00007f7e7d06388c in wlr_signal_emit_safe (signal=0x56025fde81e0, data=0x56025fde80c0) at ../subprojects/wlroots/util/signal.c:29
#4  0x00007f7e7d0450ac in layer_surface_destroy (surface=0x56025fde80c0) at ../subprojects/wlroots/types/wlr_layer_shell.c:180
#5  0x00007f7e7d04506d in layer_surface_resource_destroy (resource=0x56025fde8230) at ../subprojects/wlroots/types/wlr_layer_shell.c:194
#6  0x00007f7e7b514c12 in  () at /usr/lib/libwayland-server.so.0
#7  0x00007f7e7b514c62 in wl_resource_destroy () at /usr/lib/libwayland-server.so.0
#8  0x00007f7e7d0454b9 in resource_handle_destroy (client=0x56025fdf9200, resource=0x56025fde8230) at ../subprojects/wlroots/types/wlr_layer_shell.c:18
#9  0x00007f7e769fd1c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#10 0x00007f7e769fcc2a in ffi_call () at /usr/lib/libffi.so.6
#11 0x00007f7e7b5187fd in  () at /usr/lib/libwayland-server.so.0
#12 0x00007f7e7b514f79 in  () at /usr/lib/libwayland-server.so.0
#13 0x00007f7e7b5169b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#14 0x00007f7e7b51514c in wl_display_run () at /usr/lib/libwayland-server.so.0
#15 0x000056025d7c35d4 in server_run (server=0x56025da00310 <server>) at ../sway/server.c:141
#16 0x000056025d7c27b2 in main (argc=4, argv=0x7ffc56225608) at ../sway/main.c:418
```

Logs:

```
2018-05-01 08:42:41 - [sway/commands.c:334] Handling command 'output WL-2 disable'
2018-05-01 08:42:41 - [sway/commands.c:220] find_handler(output) 0
2018-05-01 08:42:41 - [sway/commands/output.c:291] Config stored for output WL-2 (enabled: 0) (-1x-1@-1.000000Hz position -1,-1 scale -1.000000 transform -1) (bg (null) (null))
2018-05-01 08:42:41 - [sway/tree/layout.c:131] Adding 0x56025fefac00 (2, 534.000000x854.000000) to 0x56025fde4760 (1, 533.000000x876.000000)
2018-05-01 08:42:41 - [sway/tree/arrange.c:54] Arranging output 'WL-1' at 534.000000,0.000000
2018-05-01 08:42:41 - [sway/tree/arrange.c:73] Usable area for ws: 533x854@0,22
2018-05-01 08:42:41 - [sway/tree/arrange.c:79] Arranging workspace '1' at 0.000000, 22.000000
2018-05-01 08:42:41 - [sway/tree/arrange.c:187] Arranging layout for 0x56025fddc800 1 533.000000x854.000000+0.000000,22.000000
2018-05-01 08:42:41 - [sway/tree/arrange.c:105] Arranging 0x56025fddc800 horizontally
2018-05-01 08:42:41 - [sway/tree/arrange.c:112] Calculating arrangement for 0x56025ff251e0:4 (will scale 533.000000 by 1.000000)
2018-05-01 08:42:41 - [sway/tree/arrange.c:73] Usable area for ws: 533x854@0,22
2018-05-01 08:42:41 - [sway/tree/arrange.c:79] Arranging workspace '2' at 0.000000, 22.000000
2018-05-01 08:42:41 - [sway/tree/arrange.c:187] Arranging layout for 0x56025fefac00 2 533.000000x854.000000+0.000000,22.000000
2018-05-01 08:42:41 - [sway/tree/container.c:159] OUTPUT: Destroying output 'WL-2'
2018-05-01 08:42:41 - [sway/tree/arrange.c:54] Arranging output 'WL-1' at 0.000000,0.000000
2018-05-01 08:42:41 - [sway/tree/arrange.c:73] Usable area for ws: 533x854@0,22
2018-05-01 08:42:41 - [sway/tree/arrange.c:79] Arranging workspace '1' at 0.000000, 22.000000
2018-05-01 08:42:41 - [sway/tree/arrange.c:187] Arranging layout for 0x56025fddc800 1 533.000000x854.000000+0.000000,22.000000
2018-05-01 08:42:41 - [sway/tree/arrange.c:105] Arranging 0x56025fddc800 horizontally
2018-05-01 08:42:41 - [sway/tree/arrange.c:112] Calculating arrangement for 0x56025ff251e0:4 (will scale 533.000000 by 1.000000)
2018-05-01 08:42:41 - [sway/tree/arrange.c:73] Usable area for ws: 533x854@0,22
2018-05-01 08:42:41 - [sway/tree/arrange.c:79] Arranging workspace '2' at 0.000000, 22.000000
2018-05-01 08:42:41 - [sway/tree/arrange.c:187] Arranging layout for 0x56025fefac00 2 533.000000x854.000000+0.000000,22.000000
2018-05-01 08:42:41 - [sway/ipc-server.c:657] Added IPC reply to client 30 queue: [ { "success": true } ]
2018-05-01 08:42:41 - [sway/ipc-server.c:356] Client 30 writable
2018-05-01 08:42:41 - [sway/ipc-server.c:192] Client 30 hung up
2018-05-01 08:42:41 - [sway/ipc-server.c:388] IPC Client 30 disconnected
2018-05-01 08:42:41 - [sway/desktop/layer_shell.c:266] Layer surface destroyed (panel)
2018-05-01 08:42:41 - [sway/desktop/layer_shell.c:177] Usable area changed, rearranging output
2018-05-01 08:42:41 - [sway/tree/arrange.c:54] Arranging output ' j�_V' at 0.000000,0.000000
```

### PR DESCRIPTION
**Pull request by thejan2009**
Before freeing sway_output, NULL the wlr_output reference to it. Check for that
NULL in layer_shell handle_destroy. Don't damage null container in unmap.
Additionaly, terminate swaybg if its output is being disabled.

Fixes #1877 segfaults, but reenabling output still doesn't work.

### CODE REVIEW

File: sway/config/output.c [hunk 1]
```diff
@@ -128,6 +128,9 @@ void apply_output_config(struct output_config *oc, struct sway_container *output
 	struct wlr_output *wlr_output = output->sway_output->wlr_output;
 
 	if (oc && oc->enabled == 0) {
+		if (output->sway_output->bg_pid != 0) {
+			terminate_swaybg(output->sway_output->bg_pid);
```
Comment (emersion) [inline sway/config/output.c]: Should set it to 0 here

**Comment by emersion** [comment]
Thanks for looking into this! When this gets merged, please open a new issue for "reenabling output still doesn't work".
