### PR TITLE
xdg_shell: allow views to change geometry anytime

### LINKED ISSUE #5750: Clients may draw outside their window geometry
```
$ swaymsg -pt get_version
sway version 1.5-cc8d318a (Oct 20 2020, branch 'master')
$ pacman -Qo /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 is owned by polkit-gnome 0.105-5
```

Some clients can render outside their geometry, and the window border is drawn over the window. My example is `polkit-gnome-authentication-agent-1`, pic below. It is GTK. I have read #4924 and #5125, but this seems different because there is no subsurface involved. Just running the agent and triggering an authentication for it to open the window should be enough to reproduce the issue.

image

The agent only receives pointer input that is within the drawn window border.

Here is a sway debug log where I reproduced the issue:

<details>
<summary>
sway -d log
</summary>

```
00:00:00.000 [sway/main.c:327] Sway version 1.5-cc8d318a (Oct 20 2020, branch 'master')
00:00:00.003 [sway/main.c:154] Linux rxps 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
00:00:00.003 [sway/main.c:170] Contents of /etc/lsb-release:
00:00:00.003 [sway/main.c:154] LSB_VERSION=1.4
00:00:00.003 [sway/main.c:154] DISTRIB_ID=Arch
00:00:00.003 [sway/main.c:154] DISTRIB_RELEASE=rolling
00:00:00.003 [sway/main.c:154] DISTRIB_DESCRIPTION="Arch Linux"
00:00:00.003 [sway/main.c:170] Contents of /etc/os-release:
00:00:00.003 [sway/main.c:154] NAME="Arch Linux"
00:00:00.003 [sway/main.c:154] PRETTY_NAME="Arch Linux"
00:00:00.003 [sway/main.c:154] ID=arch
00:00:00.003 [sway/main.c:154] BUILD_ID=rolling
00:00:00.003 [sway/main.c:154] ANSI_COLOR="38;2;23;147;209"
00:00:00.003 [sway/main.c:154] HOME_URL="https://www.archlinux.org/"
00:00:00.003 [sway/main.c:154] DOCUMENTATION_URL="https://wiki.archlinux.org/"
00:00:00.003 [sway/main.c:154] SUPPORT_URL="https://bbs.archlinux.org/"
00:00:00.003 [sway/main.c:154] BUG_REPORT_URL="https://bugs.archlinux.org/"
00:00:00.003 [sway/main.c:154] LOGO=archlinux
00:00:00.003 [sway/main.c:142] LD_LIBRARY_PATH=
00:00:00.003 [sway/main.c:142] LD_PRELOAD=
00:00:00.003 [sway/main.c:142] PATH=/home/ronan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
00:00:00.003 [sway/main.c:142] SWAYSOCK=/run/user/1000/sway-ipc.1000.981.sock
00:00:00.003 [sway/server.c:44] Preparing Wayland server initialization
00:00:00.003 [INFO] [backend/wayland/backend.c:253] Creating wayland backend
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wl_shm v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wl_drm v2
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_linux_dmabuf_v1 v3
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wl_compositor v4
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wl_subcompositor v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wl_data_device_manager v3
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_gamma_control_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: gtk_primary_selection_device_manager v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zxdg_output_manager_v1 v3
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: org_kde_kwin_idle v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_idle_inhibit_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_layer_shell_v1 v2
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: xdg_wm_base v2
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_tablet_manager_v2 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: org_kde_kwin_server_decoration_manager v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zxdg_decoration_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_relative_pointer_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_pointer_constraints_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wp_presentation v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_output_manager_v1 v2
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_output_power_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_input_method_manager_v2 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_text_input_manager_v3 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_foreign_toplevel_manager_v1 v3
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_export_dmabuf_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_screencopy_manager_v1 v3
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_data_control_manager_v1 v2
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_primary_selection_device_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wp_viewporter v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_virtual_keyboard_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_virtual_pointer_manager_v1 v2
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwlr_input_inhibit_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_keyboard_shortcuts_inhibit_manager_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wl_seat v7
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: zwp_pointer_gestures_v1 v1
00:00:00.003 [DEBUG] [backend/wayland/backend.c:100] Remote wayland global: wl_output v3
00:00:00.256 [INFO] [render/egl.c:297] Using EGL 1.5
00:00:00.256 [INFO] [render/egl.c:298] Supported EGL client extensions: EGL_EXT_platform_base EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_KHR_platform_x11 EGL_EXT_platform_x11 EGL_EXT_platform_device EGL_KHR_platform_wayland EGL_EXT_platform_wayland EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
00:00:00.256 [INFO] [render/egl.c:299] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_swap_buffers_with_damage EGL_IMG_context_priority EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_KHR_swap_buffers_with_damage EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display EGL_WL_create_wayland_buffer_from_image 
00:00:00.256 [INFO] [render/egl.c:300] EGL vendor: Mesa Project
00:00:00.256 [DEBUG] [render/egl.c:175] Supported dmabuf buffer formats: AB4H XB4H AR30 XR30 AB30 AR24 AB24 XR24 XB24 AR15 RG16 R8   R16  GR88 GR32 YUV9 YU11 YU12 YU16 YU24 YVU9 YV11 YV12 YV16 YV24 NV12 P010 P012 P016 NV16 AYUV XYUV YUYV UYVY 
00:00:00.258 [INFO] [render/gles2/renderer.c:674] Using OpenGL ES 3.2 Mesa 20.2.1
00:00:00.258 [INFO] [render/gles2/renderer.c:675] GL vendor: Intel
00:00:00.258 [INFO] [render/gles2/renderer.c:676] GL renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
00:00:00.258 [INFO] [render/gles2/renderer.c:677] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_OES_viewport_array GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_INTEL_conservative_rasterization GL_INTEL_performance_query GL_ANDROID_extension_pack_es31a GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_gpu_shader5 GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_render_snorm GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_norm16 GL_EXT_texture_view GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_image_formats GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_gpu_shader5 GL_OES_primitive_bounding_box GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_texture_view GL_EXT_blend_func_extended GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_shader_samples_identical GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_NV_fragment_shader_interlock GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_clip_cull_distance GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_MESA_shader_integer_functions GL_EXT_clip_control GL_EXT_texture_compression_bptc GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_sRGB_R8 GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_demote_to_helper_invocation GL_EXT_depth_clamp GL_EXT_texture_query_lod 
00:00:00.264 [sway/main.c:375] Starting sway version 1.5-cc8d318a (Oct 20 2020, branch 'master')
00:00:00.265 [sway/server.c:57] Initializing Wayland server
00:00:00.265 [DEBUG] [types/wlr_idle.c:247] idle manager created
00:00:00.265 [INFO] [wayland] unable to lock lockfile /run/user/1000/wayland-1.lock, maybe another compositor is running
00:00:00.265 [INFO] [backend/noop/backend.c:51] Creating noop backend
00:00:00.265 [INFO] [backend/headless/backend.c:171] Creating headless backend
00:00:00.267 [sway/config.c:379] Loading config from /home/ronan/.config/sway/debug
00:00:00.267 [sway/config.c:789] Read line 1: # Default config for sway
00:00:00.267 [sway/config.c:789] Read line 2: #
00:00:00.267 [sway/config.c:789] Read line 3: # Copy this to ~/.config/sway/config and edit it to your liking.
00:00:00.267 [sway/config.c:789] Read line 4: #
00:00:00.267 [sway/config.c:789] Read line 5: # Read `man 5 sway` for a complete reference.
00:00:00.267 [sway/config.c:789] Read line 6: 
00:00:00.267 [sway/config.c:789] Read line 7: ### Variables
00:00:00.267 [sway/config.c:789] Read line 8: #
00:00:00.267 [sway/config.c:789] Read line 9: # Logo key. Use Mod1 for Alt.
00:00:00.267 [sway/config.c:789] Read line 10: set $mod Mod1
00:00:00.267 [sway/commands.c:372] Config command: set $mod Mod1
00:00:00.267 [sway/commands.c:392] After replacement: set $mod Mod1
00:00:00.267 [sway/config.c:789] Read line 11: # Home row direction keys, like vim
00:00:00.267 [sway/config.c:789] Read line 12: set $left h
00:00:00.267 [sway/commands.c:372] Config command: set $left h
00:00:00.267 [sway/commands.c:392] After replacement: set $left h
00:00:00.267 [sway/config.c:789] Read line 13: set $down j
00:00:00.267 [sway/commands.c:372] Config command: set $down j
00:00:00.267 [sway/commands.c:392] After replacement: set $down j
00:00:00.267 [sway/config.c:789] Read line 14: set $up k
00:00:00.267 [sway/commands.c:372] Config command: set $up k
00:00:00.267 [sway/commands.c:392] After replacement: set $up k
00:00:00.267 [sway/config.c:789] Read line 15: set $right l
00:00:00.267 [sway/commands.c:372] Config command: set $right l
00:00:00.267 [sway/commands.c:392] After replacement: set $right l
00:00:00.267 [sway/config.c:789] Read line 16: # Your preferred terminal emulator
00:00:00.267 [sway/config.c:789] Read line 17: set $term termite
00:00:00.267 [sway/commands.c:372] Config command: set $term termite
00:00:00.267 [sway/commands.c:392] After replacement: set $term termite
00:00:00.267 [sway/config.c:789] Read line 18: # Your preferred application launcher
00:00:00.267 [sway/config.c:789] Read line 19: # Note: pass the final command to swaymsg so that the resulting window can be opened
00:00:00.267 [sway/config.c:789] Read line 20: # on the original workspace that the command was run on.
00:00:00.267 [sway/config.c:789] Read line 21: set $menu dmenu_path | dmenu | xargs swaymsg exec --
00:00:00.267 [sway/commands.c:372] Config command: set $menu dmenu_path | dmenu | xargs swaymsg exec --
00:00:00.267 [sway/commands.c:392] After replacement: set $menu dmenu_path | dmenu | xargs swaymsg exec --
00:00:00.267 [sway/config.c:789] Read line 22: 
00:00:00.267 [sway/config.c:789] Read line 23: ### Output configuration
00:00:00.267 [sway/config.c:789] Read line 24: #
00:00:00.267 [sway/config.c:789] Read line 25: # Default wallpaper (more resolutions are available in /usr/share/backgrounds/sway/)
00:00:00.267 [sway/config.c:789] Read line 26: output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
00:00:00.267 [sway/commands.c:372] Config command: output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
00:00:00.267 [sway/commands.c:392] After replacement: output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
00:00:00.267 [sway/commands.c:423] Subcommand: bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
00:00:00.267 [sway/config/output.c:223] Adding output * config
00:00:00.267 [sway/config/output.c:227] Config stored for output * (enabled: -1) (-1x-1@-1.000000Hz position -1,-1 scale -1.000000 subpixel unknown transform -1) (bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill) (dpms 0) (max render time: -1)
00:00:00.267 [sway/config/output.c:789] spawn_swaybg cmd[0] = swaybg
00:00:00.267 [sway/config/output.c:789] spawn_swaybg cmd[1] = -o
00:00:00.267 [sway/config/output.c:789] spawn_swaybg cmd[2] = *
00:00:00.267 [sway/config/output.c:789] spawn_swaybg cmd[3] = -i
00:00:00.267 [sway/config/output.c:789] spawn_swaybg cmd[4] = /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png
00:00:00.267 [sway/config/output.c:789] spawn_swaybg cmd[5] = -m
00:00:00.267 [sway/config/output.c:789] spawn_swaybg cmd[6] = fill
00:00:00.269 [sway/config.c:789] Read line 27: #
00:00:00.269 [sway/config.c:789] Read line 28: # Example configuration:
00:00:00.269 [sway/config.c:789] Read line 29: #
00:00:00.269 [sway/config.c:789] Read line 30: #   output HDMI-A-1 resolution 1920x1080 position 1920,0
00:00:00.269 [sway/config.c:789] Read line 31: #
00:00:00.269 [sway/config.c:789] Read line 32: # You can get the names of your outputs by running: swaymsg -t get_outputs
00:00:00.269 [sway/config.c:789] Read line 33: 
00:00:00.269 [sway/config.c:789] Read line 34: ### Idle configuration
00:00:00.269 [sway/config.c:789] Read line 35: #
00:00:00.269 [sway/config.c:789] Read line 36: # Example configuration:
00:00:00.269 [sway/config.c:789] Read line 37: #
00:00:00.269 [sway/config.c:789] Read line 38: # exec swayidle -w \
00:00:00.269 [sway/config.c:789] Read line 39: #          timeout 300 'swaylock -f -c 000000' \
00:00:00.269 [sway/config.c:789] Read line 40: #          timeout 600 'swaymsg "output * dpms off"' \
00:00:00.269 [sway/config.c:789] Read line 41: #               resume 'swaymsg "output * dpms on"' \
00:00:00.269 [sway/config.c:789] Read line 42: #          before-sleep 'swaylock -f -c 000000'
00:00:00.269 [sway/config.c:789] Read line 43: #
00:00:00.269 [sway/config.c:789] Read line 44: # This will lock your screen after 300 seconds of inactivity, then turn off
00:00:00.269 [sway/config.c:789] Read line 45: # your displays after another 300 seconds, and turn your screens back on when
00:00:00.269 [sway/config.c:789] Read line 46: # resumed. It will also lock your screen before your computer goes to sleep.
00:00:00.269 [sway/config.c:789] Read line 47: 
00:00:00.269 [sway/config.c:789] Read line 48: ### Input configuration
00:00:00.269 [sway/config.c:789] Read line 49: #
00:00:00.269 [sway/config.c:789] Read line 50: # Example configuration:
00:00:00.269 [sway/config.c:789] Read line 51: #
00:00:00.269 [sway/config.c:789] Read line 52: #   input "2:14:SynPS/2_Synaptics_TouchPad" {
00:00:00.269 [sway/config.c:789] Read line 53: #       dwt enabled
00:00:00.269 [sway/config.c:789] Read line 54: #       tap enabled
00:00:00.269 [sway/config.c:789] Read line 55: #       natural_scroll enabled
00:00:00.269 [sway/config.c:789] Read line 56: #       middle_emulation enabled
00:00:00.269 [sway/config.c:789] Read line 57: #   }
00:00:00.269 [sway/config.c:789] Read line 58: #
00:00:00.269 [sway/config.c:789] Read line 59: # You can get the names of your inputs by running: swaymsg -t get_inputs
00:00:00.269 [sway/config.c:789] Read line 60: # Read `man 5 sway-input` for more information about this section.
00:00:00.269 [sway/config.c:789] Read line 61: 
00:00:00.269 [sway/config.c:789] Read line 62: ### Key bindings
00:00:00.269 [sway/config.c:789] Read line 63: #
00:00:00.269 [sway/config.c:789] Read line 64: # Basics:
00:00:00.269 [sway/config.c:789] Read line 65: #
00:00:00.269 [sway/config.c:789] Read line 66:     # Start a terminal
00:00:00.269 [sway/config.c:789] Read line 67:     bindsym $mod+Return exec $term
00:00:00.269 [sway/commands.c:372] Config command: bindsym $mod+Return exec $term
00:00:00.269 [sway/commands.c:392] After replacement: bindsym Mod1+Return exec termite
00:00:00.269 [sway/commands/bind.c:297] bindsym - Bound Mod1+Return to command `exec termite` for device '*'
00:00:00.269 [sway/config.c:789] Read line 68: 
00:00:00.269 [sway/config.c:789] Read line 69:     # Kill focused window
00:00:00.269 [sway/config.c:789] Read line 70:     bindsym $mod+Shift+q kill
00:00:00.269 [sway/commands.c:372] Config command: bindsym $mod+Shift+q kill
00:00:00.269 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+q kill
00:00:00.269 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+q to command `kill` for device '*'
00:00:00.269 [sway/config.c:789] Read line 71: 
00:00:00.269 [sway/config.c:789] Read line 72:     # Start your launcher
00:00:00.269 [sway/config.c:789] Read line 73:     bindsym $mod+d exec $menu
00:00:00.269 [sway/commands.c:372] Config command: bindsym $mod+d exec $menu
00:00:00.269 [sway/commands.c:392] After replacement: bindsym Mod1+d exec dmenu_path | dmenu | xargs swaymsg exec --
00:00:00.269 [sway/commands/bind.c:297] bindsym - Bound Mod1+d to command `exec dmenu_path | dmenu | xargs swaymsg exec --` for device '*'
00:00:00.269 [sway/config.c:789] Read line 74: 
00:00:00.269 [sway/config.c:789] Read line 75:     # Drag floating windows by holding down $mod and left mouse button.
00:00:00.269 [sway/config.c:789] Read line 76:     # Resize them with right mouse button + $mod.
00:00:00.269 [sway/config.c:789] Read line 77:     # Despite the name, also works for non-floating windows.
00:00:00.269 [sway/config.c:789] Read line 78:     # Change normal to inverse to use left mouse button for resizing and right
00:00:00.270 [sway/config.c:789] Read line 79:     # mouse button for dragging.
00:00:00.270 [sway/config.c:789] Read line 80:     floating_modifier $mod normal
00:00:00.270 [sway/commands.c:372] Config command: floating_modifier $mod normal
00:00:00.270 [sway/commands.c:392] After replacement: floating_modifier Mod1 normal
00:00:00.270 [sway/config.c:789] Read line 81: 
00:00:00.270 [sway/config.c:789] Read line 82:     # Reload the configuration file
00:00:00.270 [sway/config.c:789] Read line 83:     bindsym $mod+Shift+c reload
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+c reload
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+c reload
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+c to command `reload` for device '*'
00:00:00.270 [sway/config.c:789] Read line 84: 
00:00:00.270 [sway/config.c:789] Read line 85:     # Exit sway (logs you out of your Wayland session)
00:00:00.270 [sway/config.c:789] Read line 86:     bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+e to command `exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'` for device '*'
00:00:00.270 [sway/config.c:789] Read line 87: #
00:00:00.270 [sway/config.c:789] Read line 88: # Moving around:
00:00:00.270 [sway/config.c:789] Read line 89: #
00:00:00.270 [sway/config.c:789] Read line 90:     # Move your focus around
00:00:00.270 [sway/config.c:789] Read line 91:     bindsym $mod+$left focus left
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+$left focus left
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+h focus left
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+h to command `focus left` for device '*'
00:00:00.270 [sway/config.c:789] Read line 92:     bindsym $mod+$down focus down
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+$down focus down
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+j focus down
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+j to command `focus down` for device '*'
00:00:00.270 [sway/config.c:789] Read line 93:     bindsym $mod+$up focus up
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+$up focus up
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+k focus up
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+k to command `focus up` for device '*'
00:00:00.270 [sway/config.c:789] Read line 94:     bindsym $mod+$right focus right
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+$right focus right
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+l focus right
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+l to command `focus right` for device '*'
00:00:00.270 [sway/config.c:789] Read line 95:     # Or use $mod+[up|down|left|right]
00:00:00.270 [sway/config.c:789] Read line 96:     bindsym $mod+Left focus left
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Left focus left
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Left focus left
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Left to command `focus left` for device '*'
00:00:00.270 [sway/config.c:789] Read line 97:     bindsym $mod+Down focus down
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Down focus down
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Down focus down
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Down to command `focus down` for device '*'
00:00:00.270 [sway/config.c:789] Read line 98:     bindsym $mod+Up focus up
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Up focus up
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Up focus up
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Up to command `focus up` for device '*'
00:00:00.270 [sway/config.c:789] Read line 99:     bindsym $mod+Right focus right
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Right focus right
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Right focus right
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Right to command `focus right` for device '*'
00:00:00.270 [sway/config.c:789] Read line 100: 
00:00:00.270 [sway/config.c:789] Read line 101:     # Move the focused window with the same, but add Shift
00:00:00.270 [sway/config.c:789] Read line 102:     bindsym $mod+Shift+$left move left
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+$left move left
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+h move left
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+h to command `move left` for device '*'
00:00:00.270 [sway/config.c:789] Read line 103:     bindsym $mod+Shift+$down move down
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+$down move down
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+j move down
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+j to command `move down` for device '*'
00:00:00.270 [sway/config.c:789] Read line 104:     bindsym $mod+Shift+$up move up
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+$up move up
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+k move up
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+k to command `move up` for device '*'
00:00:00.270 [sway/config.c:789] Read line 105:     bindsym $mod+Shift+$right move right
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+$right move right
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+l move right
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+l to command `move right` for device '*'
00:00:00.270 [sway/config.c:789] Read line 106:     # Ditto, with arrow keys
00:00:00.270 [sway/config.c:789] Read line 107:     bindsym $mod+Shift+Left move left
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+Left move left
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+Left move left
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+Left to command `move left` for device '*'
00:00:00.270 [sway/config.c:789] Read line 108:     bindsym $mod+Shift+Down move down
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+Down move down
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+Down move down
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+Down to command `move down` for device '*'
00:00:00.270 [sway/config.c:789] Read line 109:     bindsym $mod+Shift+Up move up
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+Up move up
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+Up move up
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+Up to command `move up` for device '*'
00:00:00.270 [sway/config.c:789] Read line 110:     bindsym $mod+Shift+Right move right
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+Right move right
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+Right move right
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+Right to command `move right` for device '*'
00:00:00.270 [sway/config.c:789] Read line 111: #
00:00:00.270 [sway/config.c:789] Read line 112: # Workspaces:
00:00:00.270 [sway/config.c:789] Read line 113: #
00:00:00.270 [sway/config.c:789] Read line 114:     # Switch to workspace
00:00:00.270 [sway/config.c:789] Read line 115:     bindsym $mod+1 workspace 1
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+1 workspace 1
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+1 workspace 1
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+1 to command `workspace 1` for device '*'
00:00:00.270 [sway/config.c:789] Read line 116:     bindsym $mod+2 workspace 2
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+2 workspace 2
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+2 workspace 2
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+2 to command `workspace 2` for device '*'
00:00:00.270 [sway/config.c:789] Read line 117:     bindsym $mod+3 workspace 3
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+3 workspace 3
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+3 workspace 3
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+3 to command `workspace 3` for device '*'
00:00:00.270 [sway/config.c:789] Read line 118:     bindsym $mod+4 workspace 4
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+4 workspace 4
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+4 workspace 4
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+4 to command `workspace 4` for device '*'
00:00:00.270 [sway/config.c:789] Read line 119:     bindsym $mod+5 workspace 5
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+5 workspace 5
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+5 workspace 5
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+5 to command `workspace 5` for device '*'
00:00:00.270 [sway/config.c:789] Read line 120:     bindsym $mod+6 workspace 6
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+6 workspace 6
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+6 workspace 6
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+6 to command `workspace 6` for device '*'
00:00:00.270 [sway/config.c:789] Read line 121:     bindsym $mod+7 workspace 7
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+7 workspace 7
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+7 workspace 7
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+7 to command `workspace 7` for device '*'
00:00:00.270 [sway/config.c:789] Read line 122:     bindsym $mod+8 workspace 8
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+8 workspace 8
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+8 workspace 8
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+8 to command `workspace 8` for device '*'
00:00:00.270 [sway/config.c:789] Read line 123:     bindsym $mod+9 workspace 9
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+9 workspace 9
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+9 workspace 9
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+9 to command `workspace 9` for device '*'
00:00:00.270 [sway/config.c:789] Read line 124:     bindsym $mod+0 workspace 10
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+0 workspace 10
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+0 workspace 10
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+0 to command `workspace 10` for device '*'
00:00:00.270 [sway/config.c:789] Read line 125:     # Move focused container to workspace
00:00:00.270 [sway/config.c:789] Read line 126:     bindsym $mod+Shift+1 move container to workspace 1
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+1 move container to workspace 1
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+1 move container to workspace 1
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+1 to command `move container to workspace 1` for device '*'
00:00:00.270 [sway/config.c:789] Read line 127:     bindsym $mod+Shift+2 move container to workspace 2
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+2 move container to workspace 2
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+2 move container to workspace 2
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+2 to command `move container to workspace 2` for device '*'
00:00:00.270 [sway/config.c:789] Read line 128:     bindsym $mod+Shift+3 move container to workspace 3
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+3 move container to workspace 3
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+3 move container to workspace 3
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+3 to command `move container to workspace 3` for device '*'
00:00:00.270 [sway/config.c:789] Read line 129:     bindsym $mod+Shift+4 move container to workspace 4
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+4 move container to workspace 4
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+4 move container to workspace 4
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+4 to command `move container to workspace 4` for device '*'
00:00:00.270 [sway/config.c:789] Read line 130:     bindsym $mod+Shift+5 move container to workspace 5
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+5 move container to workspace 5
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+5 move container to workspace 5
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+5 to command `move container to workspace 5` for device '*'
00:00:00.270 [sway/config.c:789] Read line 131:     bindsym $mod+Shift+6 move container to workspace 6
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+6 move container to workspace 6
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+6 move container to workspace 6
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+6 to command `move container to workspace 6` for device '*'
00:00:00.270 [sway/config.c:789] Read line 132:     bindsym $mod+Shift+7 move container to workspace 7
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+7 move container to workspace 7
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+7 move container to workspace 7
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+7 to command `move container to workspace 7` for device '*'
00:00:00.270 [sway/config.c:789] Read line 133:     bindsym $mod+Shift+8 move container to workspace 8
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+8 move container to workspace 8
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+8 move container to workspace 8
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+8 to command `move container to workspace 8` for device '*'
00:00:00.270 [sway/config.c:789] Read line 134:     bindsym $mod+Shift+9 move container to workspace 9
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+9 move container to workspace 9
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+9 move container to workspace 9
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+9 to command `move container to workspace 9` for device '*'
00:00:00.270 [sway/config.c:789] Read line 135:     bindsym $mod+Shift+0 move container to workspace 10
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+0 move container to workspace 10
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+0 move container to workspace 10
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+0 to command `move container to workspace 10` for device '*'
00:00:00.270 [sway/config.c:789] Read line 136:     # Note: workspaces can have any name you want, not just numbers.
00:00:00.270 [sway/config.c:789] Read line 137:     # We just use 1-10 as the default.
00:00:00.270 [sway/config.c:789] Read line 138: #
00:00:00.270 [sway/config.c:789] Read line 139: # Layout stuff:
00:00:00.270 [sway/config.c:789] Read line 140: #
00:00:00.270 [sway/config.c:789] Read line 141:     # You can "split" the current object of your focus with
00:00:00.270 [sway/config.c:789] Read line 142:     # $mod+b or $mod+v, for horizontal and vertical splits
00:00:00.270 [sway/config.c:789] Read line 143:     # respectively.
00:00:00.270 [sway/config.c:789] Read line 144:     bindsym $mod+b splith
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+b splith
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+b splith
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+b to command `splith` for device '*'
00:00:00.270 [sway/config.c:789] Read line 145:     bindsym $mod+v splitv
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+v splitv
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+v splitv
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+v to command `splitv` for device '*'
00:00:00.270 [sway/config.c:789] Read line 146: 
00:00:00.270 [sway/config.c:789] Read line 147:     # Switch the current container between different layout styles
00:00:00.270 [sway/config.c:789] Read line 148:     bindsym $mod+s layout stacking
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+s layout stacking
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+s layout stacking
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+s to command `layout stacking` for device '*'
00:00:00.270 [sway/config.c:789] Read line 149:     bindsym $mod+w layout tabbed
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+w layout tabbed
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+w layout tabbed
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+w to command `layout tabbed` for device '*'
00:00:00.270 [sway/config.c:789] Read line 150:     bindsym $mod+e layout toggle split
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+e layout toggle split
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+e layout toggle split
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+e to command `layout toggle split` for device '*'
00:00:00.270 [sway/config.c:789] Read line 151: 
00:00:00.270 [sway/config.c:789] Read line 152:     # Make the current focus fullscreen
00:00:00.270 [sway/config.c:789] Read line 153:     bindsym $mod+f fullscreen
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+f fullscreen
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+f fullscreen
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+f to command `fullscreen` for device '*'
00:00:00.270 [sway/config.c:789] Read line 154: 
00:00:00.270 [sway/config.c:789] Read line 155:     # Toggle the current focus between tiling and floating mode
00:00:00.270 [sway/config.c:789] Read line 156:     bindsym $mod+Shift+space floating toggle
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+Shift+space floating toggle
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+space floating toggle
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+space to command `floating toggle` for device '*'
00:00:00.270 [sway/config.c:789] Read line 157: 
00:00:00.270 [sway/config.c:789] Read line 158:     # Swap focus between the tiling area and the floating area
00:00:00.270 [sway/config.c:789] Read line 159:     bindsym $mod+space focus mode_toggle
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+space focus mode_toggle
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+space focus mode_toggle
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+space to command `focus mode_toggle` for device '*'
00:00:00.270 [sway/config.c:789] Read line 160: 
00:00:00.270 [sway/config.c:789] Read line 161:     # Move focus to the parent container
00:00:00.270 [sway/config.c:789] Read line 162:     bindsym $mod+a focus parent
00:00:00.270 [sway/commands.c:372] Config command: bindsym $mod+a focus parent
00:00:00.270 [sway/commands.c:392] After replacement: bindsym Mod1+a focus parent
00:00:00.270 [sway/commands/bind.c:297] bindsym - Bound Mod1+a to command `focus parent` for device '*'
00:00:00.270 [sway/config.c:789] Read line 163: #
00:00:00.271 [sway/config.c:789] Read line 164: # Scratchpad:
00:00:00.271 [sway/config.c:789] Read line 165: #
00:00:00.271 [sway/config.c:789] Read line 166:     # Sway has a "scratchpad", which is a bag of holding for windows.
00:00:00.271 [sway/config.c:789] Read line 167:     # You can send windows there and get them back later.
00:00:00.271 [sway/config.c:789] Read line 168: 
00:00:00.271 [sway/config.c:789] Read line 169:     # Move the currently focused window to the scratchpad
00:00:00.271 [sway/config.c:789] Read line 170:     bindsym $mod+Shift+minus move scratchpad
00:00:00.271 [sway/commands.c:372] Config command: bindsym $mod+Shift+minus move scratchpad
00:00:00.271 [sway/commands.c:392] After replacement: bindsym Mod1+Shift+minus move scratchpad
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Mod1+Shift+minus to command `move scratchpad` for device '*'
00:00:00.271 [sway/config.c:789] Read line 171: 
00:00:00.271 [sway/config.c:789] Read line 172:     # Show the next scratchpad window or hide the focused scratchpad window.
00:00:00.271 [sway/config.c:789] Read line 173:     # If there are multiple scratchpad windows, this command cycles through them.
00:00:00.271 [sway/config.c:789] Read line 174:     bindsym $mod+minus scratchpad show
00:00:00.271 [sway/commands.c:372] Config command: bindsym $mod+minus scratchpad show
00:00:00.271 [sway/commands.c:392] After replacement: bindsym Mod1+minus scratchpad show
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Mod1+minus to command `scratchpad show` for device '*'
00:00:00.271 [sway/config.c:789] Read line 175: #
00:00:00.271 [sway/config.c:789] Read line 176: # Resizing containers:
00:00:00.271 [sway/config.c:789] Read line 177: #
00:00:00.271 [sway/config.c:789] Read line 178: mode "resize" {
00:00:00.271 [sway/config.c:843] Entering block 'mode "resize"'
00:00:00.271 [sway/config.c:789] Read line 179:     # left will shrink the containers width
00:00:00.271 [sway/config.c:789] Read line 180:     # right will grow the containers width
00:00:00.271 [sway/config.c:789] Read line 181:     # up will shrink the containers height
00:00:00.271 [sway/config.c:789] Read line 182:     # down will grow the containers height
00:00:00.271 [sway/config.c:789] Read line 183:     bindsym $left resize shrink width 10px
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym $left resize shrink width 10px
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym h resize shrink width 10px
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym h resize shrink width 10px
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound h to command `resize shrink width 10px` for device '*'
00:00:00.271 [sway/config.c:789] Read line 184:     bindsym $down resize grow height 10px
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym $down resize grow height 10px
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym j resize grow height 10px
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym j resize grow height 10px
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound j to command `resize grow height 10px` for device '*'
00:00:00.271 [sway/config.c:789] Read line 185:     bindsym $up resize shrink height 10px
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym $up resize shrink height 10px
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym k resize shrink height 10px
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym k resize shrink height 10px
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound k to command `resize shrink height 10px` for device '*'
00:00:00.271 [sway/config.c:789] Read line 186:     bindsym $right resize grow width 10px
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym $right resize grow width 10px
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym l resize grow width 10px
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym l resize grow width 10px
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound l to command `resize grow width 10px` for device '*'
00:00:00.271 [sway/config.c:789] Read line 187: 
00:00:00.271 [sway/config.c:789] Read line 188:     # Ditto, with arrow keys
00:00:00.271 [sway/config.c:789] Read line 189:     bindsym Left resize shrink width 10px
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym Left resize shrink width 10px
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym Left resize shrink width 10px
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym Left resize shrink width 10px
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Left to command `resize shrink width 10px` for device '*'
00:00:00.271 [sway/config.c:789] Read line 190:     bindsym Down resize grow height 10px
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym Down resize grow height 10px
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym Down resize grow height 10px
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym Down resize grow height 10px
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Down to command `resize grow height 10px` for device '*'
00:00:00.271 [sway/config.c:789] Read line 191:     bindsym Up resize shrink height 10px
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym Up resize shrink height 10px
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym Up resize shrink height 10px
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym Up resize shrink height 10px
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Up to command `resize shrink height 10px` for device '*'
00:00:00.271 [sway/config.c:789] Read line 192:     bindsym Right resize grow width 10px
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym Right resize grow width 10px
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym Right resize grow width 10px
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym Right resize grow width 10px
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Right to command `resize grow width 10px` for device '*'
00:00:00.271 [sway/config.c:789] Read line 193: 
00:00:00.271 [sway/config.c:789] Read line 194:     # Return to default mode
00:00:00.271 [sway/config.c:789] Read line 195:     bindsym Return mode "default"
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym Return mode "default"
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym Return mode "default"
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym Return mode "default"
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Return to command `mode "default"` for device '*'
00:00:00.271 [sway/config.c:789] Read line 196:     bindsym Escape mode "default"
00:00:00.271 [sway/commands.c:372] Config command: mode "resize" bindsym Escape mode "default"
00:00:00.271 [sway/commands.c:392] After replacement: mode "resize" bindsym Escape mode "default"
00:00:00.271 [sway/commands.c:423] Subcommand: bindsym Escape mode "default"
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Escape to command `mode "default"` for device '*'
00:00:00.271 [sway/config.c:789] Read line 197: }
00:00:00.271 [sway/config.c:860] Exiting block 'mode "resize"'
00:00:00.271 [sway/config.c:789] Read line 198: bindsym $mod+r mode "resize"
00:00:00.271 [sway/commands.c:372] Config command: bindsym $mod+r mode "resize"
00:00:00.271 [sway/commands.c:392] After replacement: bindsym Mod1+r mode "resize"
00:00:00.271 [sway/commands/bind.c:297] bindsym - Bound Mod1+r to command `mode "resize"` for device '*'
00:00:00.271 [sway/config.c:789] Read line 199: 
00:00:00.271 [sway/config.c:789] Read line 200: #
00:00:00.271 [sway/config.c:789] Read line 201: # Status Bar:
00:00:00.271 [sway/config.c:789] Read line 202: #
00:00:00.271 [sway/config.c:789] Read line 203: # Read `man 5 sway-bar` for more information about this section.
00:00:00.271 [sway/config.c:789] Read line 204: # bar {
00:00:00.271 [sway/config.c:789] Read line 205: #     position top
00:00:00.271 [sway/config.c:789] Read line 206: 
00:00:00.271 [sway/config.c:789] Read line 207: #     # When the status_command prints a new line to stdout, swaybar updates.
00:00:00.271 [sway/config.c:789] Read line 208: #     # The default just shows the current date and time.
00:00:00.271 [sway/config.c:789] Read line 209: #     status_command while date +'%Y-%m-%d %l:%M:%S %p'; do sleep 1; done
00:00:00.271 [sway/config.c:789] Read line 210: 
00:00:00.271 [sway/config.c:789] Read line 211: #     colors {
00:00:00.271 [sway/config.c:789] Read line 212: #         statusline #ffffff
00:00:00.271 [sway/config.c:789] Read line 213: #         background #323232
00:00:00.271 [sway/config.c:789] Read line 214: #         inactive_workspace #32323200 #32323200 #5c5c5c
00:00:00.271 [sway/config.c:789] Read line 215: #     }
00:00:00.271 [sway/config.c:789] Read line 216: # }
00:00:00.271 [sway/config.c:789] Read line 217: 
00:00:00.271 [sway/config.c:789] Read line 218: # include /etc/sway/config.d/*
00:00:00.271 [sway/server.c:208] Initializing Xwayland (lazy=1)
00:00:00.271 [sway/server.c:231] Starting backend on wayland display 'wayland-2'
00:00:00.271 [INFO] [backend/wayland/backend.c:156] Initializating wayland backend
00:00:00.271 [DEBUG] [backend/wayland/seat.c:733] seat 0x5555556011b0 offered pointer
00:00:00.271 [DEBUG] [backend/wayland/seat.c:758] seat 0x5555556011b0 offered keyboard
00:00:00.271 [sway/input/input-manager.c:234] adding device: '0:0:wayland'
00:00:00.271 [sway/input/input-manager.c:184] no fallback seat config - creating default
00:00:00.271 [sway/config/seat.c:65] Adding non-wildcard seat config
00:00:00.271 [sway/config/seat.c:82] Config stored for seat seat0
00:00:00.271 [sway/input/input-manager.c:585] applying seat config for seat seat0
00:00:00.271 [sway/input/seat.c:871] adding device 0:0:wayland to seat seat0
00:00:00.274 [sway/input/keyboard.c:877] Created keyboard group 0x555555da2590
00:00:00.275 [sway/input/keyboard.c:900] Adding keyboard 0:0:wayland to group 0x555555da2590
00:00:00.283 [sway/desktop/output.c:910] New output 0x555555d69d20: WL-1
00:00:00.283 [sway/config/output.c:348] Turning on output WL-1
00:00:00.283 [sway/config/output.c:379] Auto-detected output scale: 1.000000
00:00:00.283 [sway/config/output.c:409] Committing output WL-1
00:00:00.283 [sway/tree/workspace.c:283] Workspace: Generating new workspace name for output WL-1
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '1'
00:00:00.283 [sway/tree/workspace.c:274] Workspace: Found free name 1
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '2'
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '3'
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '4'
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '5'
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '6'
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '7'
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '8'
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '9'
00:00:00.283 [sway/tree/workspace.c:218] Got valid workspace command for target: '10'
00:00:00.283 [sway/tree/output.c:127] Creating default workspace 1
00:00:00.283 [sway/tree/workspace.c:63] Adding workspace 1 for output WL-1
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:243] Loaded cursor theme 'default', available cursors:
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] right_side (1 images) 24x24+19,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] col-resize (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] target (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] icon (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] bottom_left_corner (1 images) 24x24+10,15
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 08e8e1c95fe2fc01f976f1e063a24ccd (60 images) 24x24+4,3
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-no-drop (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] default (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] crossed_circle (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] double_arrow (1 images) 24x24+12,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] h_double_arrow (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] top_left_arrow (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-copy (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] right_ptr (1 images) 24x24+21,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] cell (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] nesw-resize (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 640fb0e74195791501fd1ed57b41487f (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] lr_angle (1 images) 24x24+20,19
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] size_hor (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] bd_double_arrow (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_left_arrow (1 images) 24x24+6,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] bottom_right_corner (1 images) 24x24+15,15
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] ur_angle (1 images) 24x24+20,5
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 4498f0e0c1937ffe01fd06f973665830 (1 images) 24x24+12,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] pirate (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] se-resize (1 images) 24x24+15,15
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] left_ptr_watch (60 images) 24x24+4,3
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] ew-resize (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] bottom_side (1 images) 24x24+13,18
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] circle (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] arrow (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] fcf1c3c7cd4491d801f1e1c78f100000 (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] fd_double_arrow (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] d9ce0ab605698f320427677b458ad60b (1 images) 24x24+12,21
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 028006030e0e7ebffc7f7070c0600140 (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 1081e37283d90000800003c07f3ef6bf (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] e29285e634086352946a0e7090d73106 (1 images) 24x24+8,5
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] c7088f0f3e6c8088236ef8e1e3e70000 (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] left_tee (1 images) 24x24+6,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] w-resize (1 images) 24x24+6,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] ll_angle (1 images) 24x24+4,19
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] progress (60 images) 24x24+4,3
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] plus (1 images) 24x24+10,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] top_tee (1 images) 24x24+12,5
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_up_arrow (1 images) 24x24+12,3
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] bottom_tee (1 images) 24x24+12,19
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] draped_box (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] left_ptr_help (1 images) 24x24+12,21
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] ul_angle (1 images) 24x24+4,5
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] zoom-out (1 images) 24x24+11,10
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] size_bdiag (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_down_arrow (1 images) 24x24+12,19
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] grabbing (1 images) 24x24+12,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 6407b0e94181790501fd1e167b474872 (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] no-drop (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 14fef782d02440884392942c11205230 (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] ne-resize (1 images) 24x24+15,10
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] question_arrow (1 images) 24x24+12,21
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 5c6cd98b3f3ebcb1f9c7f1c204630408 (1 images) 24x24+12,21
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] vertical-text (1 images) 24x24+12,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] s-resize (1 images) 24x24+13,18
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 00008160000006810000408080010102 (1 images) 24x24+12,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] tcross (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_right_arrow (1 images) 24x24+19,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] copy (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] draft_small (1 images) 24x24+21,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] draft_large (1 images) 24x24+21,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] right_tee (1 images) 24x24+20,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] cross (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] hand2 (1 images) 24x24+8,5
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] pointer-move (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] sw-resize (1 images) 24x24+10,15
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] fleur (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] help (1 images) 24x24+12,21
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] size_ver (1 images) 24x24+12,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] top_side (1 images) 24x24+13,6
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] not-allowed (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] row-resize (1 images) 24x24+12,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] nw-resize (1 images) 24x24+10,10
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-move (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] n-resize (1 images) 24x24+13,6
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] left_ptr (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] crosshair (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] pointer (1 images) 24x24+8,5
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 3085a0e285430894940527032f8b26df (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] size_fdiag (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] nwse-resize (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] xterm (1 images) 24x24+11,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] watch (60 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] dotbox (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] diamond_cross (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-none (1 images) 24x24+12,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] size_all (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] all-scroll (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] hand (1 images) 24x24+8,5
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] e-resize (1 images) 24x24+19,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] cross_reverse (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_v_double_arrow (1 images) 24x24+12,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] wait (60 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] dot_box_mask (1 images) 24x24+11,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] hand1 (1 images) 24x24+11,7
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] link (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 9081237383d90e509aa00f00170e968f (1 images) 24x24+12,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] alias (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] top_left_corner (1 images) 24x24+10,10
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] zoom-in (1 images) 24x24+11,10
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] X_cursor (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-ask (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 9d800788f1b08800ae810202380a0822 (1 images) 24x24+8,5
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] pencil (1 images) 24x24+7,21
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] move (1 images) 24x24+12,11
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] context-menu (1 images) 24x24+4,4
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] text (1 images) 24x24+11,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_h_double_arrow (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] left_side (1 images) 24x24+6,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 03b6e0fcb3499374a867c041f52298f0 (1 images) 24x24+12,12
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] grab (1 images) 24x24+11,7
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] ns-resize (1 images) 24x24+12,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-link (1 images) 24x24+9,9
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 2870a09082c103050810ffdffffe0204 (1 images) 24x24+12,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] top_right_corner (1 images) 24x24+15,10
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] v_double_arrow (1 images) 24x24+12,13
00:00:00.294 [DEBUG] [xcursor/wlr_xcursor.c:248] 3ecb610c1bf2410f44200f48c40d3599 (60 images) 24x24+4,3
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:243] Loaded cursor theme 'default', available cursors:
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] right_side (1 images) 24x24+19,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] col-resize (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] target (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] icon (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] bottom_left_corner (1 images) 24x24+10,15
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 08e8e1c95fe2fc01f976f1e063a24ccd (60 images) 24x24+4,3
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-no-drop (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] default (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] crossed_circle (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] double_arrow (1 images) 24x24+12,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] h_double_arrow (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] top_left_arrow (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-copy (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] right_ptr (1 images) 24x24+21,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] cell (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] nesw-resize (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 640fb0e74195791501fd1ed57b41487f (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] lr_angle (1 images) 24x24+20,19
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] size_hor (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] bd_double_arrow (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_left_arrow (1 images) 24x24+6,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] bottom_right_corner (1 images) 24x24+15,15
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] ur_angle (1 images) 24x24+20,5
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 4498f0e0c1937ffe01fd06f973665830 (1 images) 24x24+12,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] pirate (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] se-resize (1 images) 24x24+15,15
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] left_ptr_watch (60 images) 24x24+4,3
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] ew-resize (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] bottom_side (1 images) 24x24+13,18
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] circle (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] arrow (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] fcf1c3c7cd4491d801f1e1c78f100000 (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] fd_double_arrow (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] d9ce0ab605698f320427677b458ad60b (1 images) 24x24+12,21
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 028006030e0e7ebffc7f7070c0600140 (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 1081e37283d90000800003c07f3ef6bf (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] e29285e634086352946a0e7090d73106 (1 images) 24x24+8,5
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] c7088f0f3e6c8088236ef8e1e3e70000 (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] left_tee (1 images) 24x24+6,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] w-resize (1 images) 24x24+6,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] ll_angle (1 images) 24x24+4,19
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] progress (60 images) 24x24+4,3
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] plus (1 images) 24x24+10,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] top_tee (1 images) 24x24+12,5
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_up_arrow (1 images) 24x24+12,3
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] bottom_tee (1 images) 24x24+12,19
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] draped_box (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] left_ptr_help (1 images) 24x24+12,21
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] ul_angle (1 images) 24x24+4,5
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] zoom-out (1 images) 24x24+11,10
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] size_bdiag (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_down_arrow (1 images) 24x24+12,19
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] grabbing (1 images) 24x24+12,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 6407b0e94181790501fd1e167b474872 (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] no-drop (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 14fef782d02440884392942c11205230 (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] ne-resize (1 images) 24x24+15,10
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] question_arrow (1 images) 24x24+12,21
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 5c6cd98b3f3ebcb1f9c7f1c204630408 (1 images) 24x24+12,21
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] vertical-text (1 images) 24x24+12,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] s-resize (1 images) 24x24+13,18
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 00008160000006810000408080010102 (1 images) 24x24+12,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] tcross (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_right_arrow (1 images) 24x24+19,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] copy (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] draft_small (1 images) 24x24+21,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] draft_large (1 images) 24x24+21,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] right_tee (1 images) 24x24+20,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] cross (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] hand2 (1 images) 24x24+8,5
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] pointer-move (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] sw-resize (1 images) 24x24+10,15
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] fleur (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] help (1 images) 24x24+12,21
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] size_ver (1 images) 24x24+12,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] top_side (1 images) 24x24+13,6
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] not-allowed (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] row-resize (1 images) 24x24+12,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] nw-resize (1 images) 24x24+10,10
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-move (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] n-resize (1 images) 24x24+13,6
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] left_ptr (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] crosshair (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] pointer (1 images) 24x24+8,5
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 3085a0e285430894940527032f8b26df (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] size_fdiag (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] nwse-resize (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] xterm (1 images) 24x24+11,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] watch (60 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] dotbox (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] diamond_cross (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-none (1 images) 24x24+12,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] size_all (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] all-scroll (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] hand (1 images) 24x24+8,5
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] e-resize (1 images) 24x24+19,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] cross_reverse (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_v_double_arrow (1 images) 24x24+12,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] wait (60 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] dot_box_mask (1 images) 24x24+11,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] hand1 (1 images) 24x24+11,7
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] link (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 9081237383d90e509aa00f00170e968f (1 images) 24x24+12,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] alias (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] top_left_corner (1 images) 24x24+10,10
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] zoom-in (1 images) 24x24+11,10
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] X_cursor (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-ask (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 9d800788f1b08800ae810202380a0822 (1 images) 24x24+8,5
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] pencil (1 images) 24x24+7,21
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] move (1 images) 24x24+12,11
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] context-menu (1 images) 24x24+4,4
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] text (1 images) 24x24+11,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] sb_h_double_arrow (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] left_side (1 images) 24x24+6,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 03b6e0fcb3499374a867c041f52298f0 (1 images) 24x24+12,12
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] grab (1 images) 24x24+11,7
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] ns-resize (1 images) 24x24+12,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] dnd-link (1 images) 24x24+9,9
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 2870a09082c103050810ffdffffe0204 (1 images) 24x24+12,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] top_right_corner (1 images) 24x24+15,10
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] v_double_arrow (1 images) 24x24+12,13
00:00:00.304 [DEBUG] [xcursor/wlr_xcursor.c:248] 3ecb610c1bf2410f44200f48c40d3599 (60 images) 24x24+4,3
00:00:00.304 [sway/desktop/layer_shell.c:189] Usable area changed, rearranging output
00:00:00.304 [sway/tree/arrange.c:263] Usable area for ws: 1280x720@0,0
00:00:00.304 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:00.304 [sway/tree/arrange.c:263] Usable area for ws: 1280x720@0,0
00:00:00.304 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:00.309 [sway/desktop/transaction.c:427] Transaction 0x555556009ca0 committing with 2 instructions
00:00:00.309 [sway/desktop/transaction.c:281] Applying transaction 0x555556009ca0
00:00:00.309 [sway/input/input-manager.c:234] adding device: '0:0:wayland'
00:00:00.309 [sway/input/seat.c:871] adding device 0:0:wayland to seat seat0
00:00:00.309 [sway/input/seat.c:664] Applying input config to 0:0:wayland
00:00:00.309 [sway/input/seat.c:680] Mapping input device 0:0:wayland to output WL-1
00:00:00.309 [sway/input/seat.c:700] Mapped to output WL-1
00:00:00.311 [INFO] [backend/headless/backend.c:21] Starting headless backend
00:00:00.311 [sway/server.c:242] Running compositor on wayland display 'wayland-2'
00:00:00.312 [sway/desktop/layer_shell.c:189] Usable area changed, rearranging output
00:00:00.312 [sway/tree/arrange.c:263] Usable area for ws: 1900x339@0,0
00:00:00.312 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:00.312 [sway/tree/arrange.c:263] Usable area for ws: 1900x339@0,0
00:00:00.312 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:00.312 [sway/desktop/transaction.c:427] Transaction 0x555555d672b0 committing with 1 instructions
00:00:00.312 [sway/desktop/transaction.c:281] Applying transaction 0x555555d672b0
00:00:00.312 [sway/tree/arrange.c:263] Usable area for ws: 1900x339@0,0
00:00:00.312 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:00.312 [sway/desktop/transaction.c:427] Transaction 0x555555d672b0 committing with 1 instructions
00:00:00.312 [sway/desktop/transaction.c:281] Applying transaction 0x555555d672b0
2020-10-21 11:52:15 - [swaybg/main.c:299] Found config * for output WL-1 ((null))
00:00:00.312 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x555555f995d0 (res 0x555555f99980)
00:00:00.312 [DEBUG] [types/wlr_layer_shell_v1.c:458] new layer_surface 0x555555ffd460 (res 0x555555638e20)
00:00:00.312 [sway/desktop/layer_shell.c:513] new layer surface: namespace wallpaper layer 0 anchor 15 size 0x0 margin 0,0,0,0,
00:00:00.924 [sway/desktop/layer_shell.c:189] Usable area changed, rearranging output
00:00:00.925 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:00.925 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:00.925 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:00.925 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:00.925 [sway/desktop/transaction.c:427] Transaction 0x555555ddaae0 committing with 1 instructions
00:00:00.925 [sway/desktop/transaction.c:281] Applying transaction 0x555555ddaae0
00:00:00.925 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:00.925 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:00.925 [sway/desktop/transaction.c:427] Transaction 0x555555d8c410 committing with 1 instructions
00:00:00.925 [sway/desktop/transaction.c:281] Applying transaction 0x555555d8c410
00:00:17.718 [sway/commands/bind.c:616] running command for binding: exec termite
00:00:17.718 [sway/commands.c:255] Handling command 'exec termite'
00:00:17.718 [sway/commands/exec_always.c:50] Executing termite
00:00:17.725 [sway/commands/exec_always.c:91] Child process created with pid 6373
00:00:17.725 [sway/tree/root.c:290] Recording workspace for process 6373
00:00:17.761 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x555555fa2900 (res 0x555555dde850)
00:00:17.761 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x555556007190 (res 0x555555ddefb0)
00:00:17.857 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x555555ddf760 (res 0x555555ddfb10)
00:00:17.857 [DEBUG] [types/xdg_shell/wlr_xdg_surface.c:462] new xdg_surface 0x555555ddfc30 (res 0x555555de8460)
00:00:17.857 [sway/desktop/xdg_shell.c:518] New xdg_shell toplevel title='' app_id='termite'
00:00:17.857 [DEBUG] [types/wlr_server_decoration.c:106] new server_decoration 0x555555dda980 (res 0x555555de89c0)
00:00:17.877 [sway/tree/root.c:249] Looking up workspace for pid 6373
00:00:17.877 [sway/tree/root.c:256] found pid_workspace for pid 6373, workspace 1
00:00:17.901 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:17.901 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:17.901 [sway/tree/arrange.c:77] Arranging 0x7fffffffd280 horizontally
00:00:17.901 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:17.901 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:17.901 [sway/tree/arrange.c:77] Arranging 0x7fffffffd370 horizontally
00:00:17.901 [sway/desktop/transaction.c:427] Transaction 0x55555606c950 committing with 3 instructions
00:00:17.907 [sway/desktop/transaction.c:505] Transaction 0x55555606c950 is ready
00:00:17.907 [sway/desktop/transaction.c:281] Applying transaction 0x55555606c950
00:00:17.907 [sway/tree/container.c:1193] Container 0x5555560049e0 entered output 0x555555d7c5f0
00:00:35.347 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x5555560b5bf0 (res 0x5555560b2ee0)
00:00:35.347 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x5555560b61a0 (res 0x5555560b6550)
00:00:40.385 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x5555560b7d60 (res 0x555555dde710)
00:00:40.410 [DEBUG] [types/xdg_shell/wlr_xdg_surface.c:462] new xdg_surface 0x5555560b2060 (res 0x555555dde610)
00:00:40.410 [sway/desktop/xdg_shell.c:518] New xdg_shell toplevel title='Authenticate' app_id='polkit-gnome-authentication-agent-1'
00:00:40.410 [DEBUG] [types/wlr_server_decoration.c:106] new server_decoration 0x5555560ae280 (res 0x5555560b42b0)
00:00:40.419 [sway/tree/root.c:249] Looking up workspace for pid 6435
00:00:40.426 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:40.426 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:40.426 [sway/tree/arrange.c:77] Arranging 0x7fffffffd280 horizontally
00:00:40.426 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:40.426 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:40.426 [sway/tree/arrange.c:77] Arranging 0x7fffffffd370 horizontally
00:00:40.426 [sway/desktop/transaction.c:427] Transaction 0x5555560b6900 committing with 4 instructions
00:00:40.433 [sway/desktop/transaction.c:505] Transaction 0x5555560b6900 is ready
00:00:40.433 [sway/desktop/transaction.c:281] Applying transaction 0x5555560b6900
00:00:40.433 [sway/tree/container.c:1193] Container 0x5555560bf130 entered output 0x555555d7c5f0
00:00:44.145 [sway/commands/bind.c:616] running command for binding: kill
00:00:44.145 [sway/commands.c:255] Handling command 'kill'
00:00:44.150 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:44.150 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:44.150 [sway/tree/arrange.c:77] Arranging 0x7fffffffd300 horizontally
00:00:44.150 [sway/desktop/transaction.c:427] Transaction 0x555555de36c0 committing with 4 instructions
00:00:44.150 [sway/desktop/transaction.c:281] Applying transaction 0x555555de36c0
00:00:46.236 [sway/input/cursor.c:867] denying request to set cursor from unfocused client
00:00:46.236 [sway/input/cursor.c:867] denying request to set cursor from unfocused client
00:00:55.466 [sway/commands/bind.c:616] running command for binding: kill
00:00:55.466 [sway/commands.c:255] Handling command 'kill'
00:00:55.472 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:55.472 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:55.472 [sway/desktop/transaction.c:427] Transaction 0x555555d93c60 committing with 2 instructions
00:00:55.472 [sway/desktop/transaction.c:281] Applying transaction 0x555555d93c60
00:00:55.945 [sway/commands/bind.c:616] running command for binding: exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'
00:00:55.945 [sway/commands.c:255] Handling command 'exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit''
00:00:55.945 [sway/commands/exec_always.c:50] Executing swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'
00:00:55.954 [sway/commands/exec_always.c:91] Child process created with pid 6490
00:00:55.954 [sway/tree/root.c:290] Recording workspace for process 6490
00:00:55.987 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x555555de8a90 (res 0x5555560b3de0)
00:00:55.987 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x555555ddf760 (res 0x5555560b7160)
00:00:55.987 [DEBUG] [types/wlr_layer_shell_v1.c:458] new layer_surface 0x5555560095a0 (res 0x5555560b7050)
00:00:55.987 [sway/desktop/layer_shell.c:513] new layer surface: namespace swaynag layer 2 anchor 13 size 0x35 margin 0,0,0,0,
00:00:55.987 [sway/desktop/layer_shell.c:189] Usable area changed, rearranging output
00:00:55.987 [sway/tree/arrange.c:263] Usable area for ws: 945x1003@0,35
00:00:55.987 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 35.000000
00:00:55.987 [sway/desktop/transaction.c:427] Transaction 0x5555560b6900 committing with 1 instructions
00:00:55.987 [sway/desktop/transaction.c:281] Applying transaction 0x5555560b6900
00:00:55.987 [sway/desktop/layer_shell.c:189] Usable area changed, rearranging output
00:00:55.987 [sway/tree/arrange.c:263] Usable area for ws: 945x1005@0,33
00:00:55.987 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 33.000000
00:00:55.987 [sway/desktop/transaction.c:427] Transaction 0x5555560a4b40 committing with 1 instructions
00:00:55.987 [sway/desktop/transaction.c:281] Applying transaction 0x5555560a4b40
00:00:57.570 [DEBUG] [types/seat/wlr_seat_pointer.c:382] button_count=1 grab_serial=0 serial=114
00:00:57.579 [sway/ipc-server.c:153] Event on IPC listening socket
00:00:57.579 [sway/ipc-server.c:199] New client: fd 24
00:00:57.579 [sway/ipc-server.c:219] Client 24 readable
00:00:57.579 [sway/commands.c:255] Handling command 'exit'
00:00:57.579 [sway/ipc-server.c:958] Added IPC reply of type 0x0 to client 24 queue: [ { "success": true } ]
00:00:57.579 [sway/main.c:415] Shutting down sway
00:00:57.579 [sway/desktop/layer_shell.c:343] Layer surface destroyed (wallpaper)
00:00:57.579 [sway/desktop/layer_shell.c:343] Layer surface destroyed (swaynag)
00:00:57.579 [sway/desktop/layer_shell.c:189] Usable area changed, rearranging output
00:00:57.579 [sway/tree/arrange.c:263] Usable area for ws: 945x1038@0,0
00:00:57.579 [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 0.000000
00:00:57.579 [sway/desktop/transaction.c:427] Transaction 0x555555ddfbf0 committing with 1 instructions
00:00:57.579 [sway/desktop/transaction.c:281] Applying transaction 0x555555ddfbf0
00:00:57.579 [sway/tree/output.c:259] Disabling output 'WL-1'
00:00:57.579 [sway/tree/workspace.c:143] Destroying workspace '1'
00:00:57.579 [sway/input/seat.c:664] Applying input config to 0:0:wayland
00:00:57.579 [sway/input/seat.c:680] Mapping input device 0:0:wayland to output WL-1
00:00:57.579 [sway/input/seat.c:692] Requested output WL-1 for device 0:0:wayland isn't present
00:00:57.585 [sway/desktop/transaction.c:427] Transaction 0x555555dda270 committing with 2 instructions
00:00:57.585 [sway/desktop/transaction.c:281] Applying transaction 0x555555dda270
00:00:57.585 [sway/tree/output.c:283] Destroying output 'WL-1'
00:00:57.585 [sway/desktop/transaction.c:427] Transaction 0x555555dda270 committing with 1 instructions
00:00:57.585 [sway/desktop/transaction.c:281] Applying transaction 0x555555dda270
00:00:57.585 [sway/input/input-manager.c:202] removing device: '0:0:wayland'
00:00:57.585 [sway/input/seat.c:891] removing device 0:0:wayland from seat seat0
00:00:57.585 [sway/input/input-manager.c:202] removing device: '0:0:wayland'
00:00:57.585 [sway/input/seat.c:891] removing device 0:0:wayland from seat seat0
00:00:57.585 [sway/input/keyboard.c:765] Removing keyboard 0:0:wayland from group 0x555555da2590
00:00:57.585 [sway/input/keyboard.c:771] Destroying empty keyboard group 0x555555da2590
00:00:57.593 [sway/ipc-server.c:565] IPC Client 24 disconnected
00:00:00.014 [common/ipc-client.c:87] Unable to receive IPC response
```
</details>

And here is a WAYLAND_DEBUG=1 log of the client:

<details>
<summary>
Full WAYLAND_DEBUG=1 log
</summary>

```
[2660405.783]  -> wl_display@1.get_registry(new id wl_registry@2)
[2660405.813]  -> wl_display@1.sync(new id wl_callback@3)
[2660405.909] wl_display@1.delete_id(3)
[2660405.918] wl_registry@2.global(1, "wl_shm", 1)
[2660405.937]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@4)
[2660406.005]  -> wl_shm@4.create_pool(new id wl_shm_pool@5, fd 11, 2304)
[2660406.178]  -> wl_shm_pool@5.resize(6912)
[2660406.289]  -> wl_shm_pool@5.resize(16128)
[2660407.378]  -> wl_shm_pool@5.resize(34560)
[2660407.424]  -> wl_shm_pool@5.resize(71424)
[2660407.497]  -> wl_shm_pool@5.resize(145152)
[2660407.599]  -> wl_shm_pool@5.resize(292608)
[2660409.097]  -> wl_shm_pool@5.resize(587520)
[2660411.280]  -> wl_shm_pool@5.resize(1177344)
[2660423.547] wl_registry@2.global(2, "wl_drm", 2)
[2660423.564] wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 3)
[2660423.570] wl_registry@2.global(4, "wl_compositor", 4)
[2660423.576]  -> wl_registry@2.bind(4, "wl_compositor", 3, new id [unknown]@6)
[2660423.583] wl_registry@2.global(5, "wl_subcompositor", 1)
[2660423.588]  -> wl_registry@2.bind(5, "wl_subcompositor", 1, new id [unknown]@7)
[2660423.596] wl_registry@2.global(6, "wl_data_device_manager", 3)
[2660423.605]  -> wl_registry@2.bind(6, "wl_data_device_manager", 3, new id [unknown]@8)
[2660423.618] wl_registry@2.global(7, "zwlr_gamma_control_manager_v1", 1)
[2660423.627] wl_registry@2.global(8, "gtk_primary_selection_device_manager", 1)
[2660423.639]  -> wl_registry@2.bind(8, "gtk_primary_selection_device_manager", 1, new id [unknown]@9)
[2660423.652] wl_registry@2.global(9, "zxdg_output_manager_v1", 3)
[2660423.661]  -> wl_registry@2.bind(9, "zxdg_output_manager_v1", 3, new id [unknown]@10)
[2660423.674]  -> wl_display@1.sync(new id wl_callback@11)
[2660423.683] wl_registry@2.global(10, "org_kde_kwin_idle", 1)
[2660423.696] wl_registry@2.global(11, "zwp_idle_inhibit_manager_v1", 1)
[2660423.707] wl_registry@2.global(12, "zwlr_layer_shell_v1", 2)
[2660423.719] wl_registry@2.global(13, "xdg_wm_base", 2)
[2660423.733] wl_registry@2.global(14, "zwp_tablet_manager_v2", 1)
[2660423.744]  -> wl_registry@2.bind(14, "zwp_tablet_manager_v2", 1, new id [unknown]@12)
[2660423.760] wl_registry@2.global(15, "org_kde_kwin_server_decoration_manager", 1)
[2660423.773]  -> wl_registry@2.bind(15, "org_kde_kwin_server_decoration_manager", 1, new id [unknown]@13)
[2660423.790] wl_registry@2.global(16, "zxdg_decoration_manager_v1", 1)
[2660423.804] wl_registry@2.global(17, "zwp_relative_pointer_manager_v1", 1)
[2660423.816] wl_registry@2.global(18, "zwp_pointer_constraints_v1", 1)
[2660423.829] wl_registry@2.global(19, "wp_presentation", 1)
[2660423.841] wl_registry@2.global(20, "zwlr_output_manager_v1", 2)
[2660423.853] wl_registry@2.global(21, "zwlr_output_power_manager_v1", 1)
[2660423.865] wl_registry@2.global(22, "zwp_input_method_manager_v2", 1)
[2660423.877] wl_registry@2.global(23, "zwp_text_input_manager_v3", 1)
[2660423.889] wl_registry@2.global(24, "zwlr_foreign_toplevel_manager_v1", 3)
[2660423.901] wl_registry@2.global(25, "zwlr_export_dmabuf_manager_v1", 1)
[2660423.912] wl_registry@2.global(26, "zwlr_screencopy_manager_v1", 3)
[2660423.925] wl_registry@2.global(27, "zwlr_data_control_manager_v1", 2)
[2660423.937] wl_registry@2.global(28, "zwp_primary_selection_device_manager_v1", 1)
[2660423.950] wl_registry@2.global(29, "wp_viewporter", 1)
[2660423.962] wl_registry@2.global(30, "zwp_virtual_keyboard_manager_v1", 1)
[2660423.975] wl_registry@2.global(31, "zwlr_virtual_pointer_manager_v1", 2)
[2660423.989] wl_registry@2.global(32, "zwlr_input_inhibit_manager_v1", 1)
[2660424.002] wl_registry@2.global(33, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[2660424.015]  -> wl_registry@2.bind(33, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1, new id [unknown]@14)
[2660424.032] wl_registry@2.global(34, "wl_seat", 7)
[2660424.045]  -> wl_registry@2.bind(34, "wl_seat", 5, new id [unknown]@15)
[2660426.326]  -> wl_compositor@6.create_surface(new id wl_surface@16)
[2660426.346]  -> gtk_primary_selection_device_manager@9.get_device(new id gtk_primary_selection_device@17, wl_seat@15)
[2660426.359]  -> wl_data_device_manager@8.get_data_device(new id wl_data_device@18, wl_seat@15)
[2660426.447]  -> wl_compositor@6.create_surface(new id wl_surface@19)
[2660426.457]  -> zwp_tablet_manager_v2@12.get_tablet_seat(new id zwp_tablet_seat_v2@20, wl_seat@15)
[2660426.469]  -> wl_display@1.sync(new id wl_callback@21)
[2660426.477] wl_registry@2.global(35, "zwp_pointer_gestures_v1", 1)
[2660426.491]  -> wl_registry@2.bind(35, "zwp_pointer_gestures_v1", 1, new id [unknown]@22)
[2660426.508] wl_registry@2.global(36, "wl_output", 3)
[2660426.517]  -> wl_registry@2.bind(36, "wl_output", 2, new id [unknown]@23)
[2660426.562]  -> zxdg_output_manager_v1@10.get_xdg_output(new id zxdg_output_v1@24, wl_output@23)
[2660426.575]  -> wl_display@1.sync(new id wl_callback@25)
[2660426.585] wl_callback@3.done(2346)
[2660426.694] wl_display@1.delete_id(11)
[2660426.701] wl_display@1.delete_id(21)
[2660426.706] wl_display@1.delete_id(25)
[2660426.711] wl_shm@4.format(0)
[2660426.717] wl_shm@4.format(1)
[2660426.723] wl_shm@4.format(875709016)
[2660426.730] wl_shm@4.format(875708993)
[2660426.736] wl_callback@11.done(2346)
[2660426.742] org_kde_kwin_server_decoration_manager@13.default_mode(2)
[2660426.751] wl_seat@15.name("seat0")
[2660426.759] wl_seat@15.capabilities(3)
[2660426.766]  -> wl_seat@15.get_pointer(new id wl_pointer@11)
[2660426.786]  -> zwp_pointer_gestures_v1@22.get_swipe_gesture(new id zwp_pointer_gesture_swipe_v1@3, wl_pointer@11)
[2660426.799]  -> zwp_pointer_gestures_v1@22.get_pinch_gesture(new id zwp_pointer_gesture_pinch_v1@26, wl_pointer@11)
[2660426.810]  -> wl_seat@15.get_keyboard(new id wl_keyboard@27)
[2660426.828] wl_callback@21.done(2346)
[2660426.835] wl_output@23.geometry(0, 0, 350, 190, 0, "Sharp Corporation", "0x1453", 0)
[2660426.850] wl_output@23.mode(1, 1920, 1080, 59934)
[2660426.857] wl_output@23.scale(1)
[2660426.860] wl_output@23.done()
[2660426.867] zxdg_output_v1@24.name("eDP-1")
[2660426.870] zxdg_output_v1@24.description("Sharp Corporation 0x1453 0x00000000 (eDP-1)")
[2660426.873] zxdg_output_v1@24.logical_position(0, 0)
[2660426.877] zxdg_output_v1@24.logical_size(1920, 1080)
[2660426.884] wl_output@23.done()
[2660426.892] wl_callback@25.done(2346)
[2660426.899]  -> wl_registry@2.bind(13, "xdg_wm_base", 1, new id [unknown]@25)
[2660454.064] wl_keyboard@27.keymap(1, fd 14, 47427)
[2660455.844] wl_keyboard@27.repeat_info(25, 200)
[2667756.268]  -> wl_display@1.get_registry(new id wl_registry@21)
[2667768.678]  -> wl_compositor@6.create_surface(new id wl_surface@28)
[2667806.354]  -> xdg_wm_base@25.get_xdg_surface(new id xdg_surface@29, wl_surface@28)
[2667806.407]  -> xdg_surface@29.get_toplevel(new id xdg_toplevel@30)
[2667806.411]  -> xdg_toplevel@30.set_parent(nil)
[2667806.415]  -> xdg_toplevel@30.set_title("Authenticate")
[2667806.439]  -> xdg_toplevel@30.set_app_id("polkit-gnome-authentication-agent-1")
[2667806.445]  -> wl_surface@28.commit()
[2667806.449]  -> org_kde_kwin_server_decoration_manager@13.create(new id org_kde_kwin_server_decoration@31, wl_surface@28)
[2667806.471]  -> org_kde_kwin_server_decoration@31.request_mode(2)
[2667808.369] wl_registry@21.global(1, "wl_shm", 1)
[2667808.401] wl_registry@21.global(2, "wl_drm", 2)
[2667808.407] wl_registry@21.global(3, "zwp_linux_dmabuf_v1", 3)
[2667808.414] wl_registry@21.global(4, "wl_compositor", 4)
[2667808.440] wl_registry@21.global(5, "wl_subcompositor", 1)
[2667808.447] wl_registry@21.global(6, "wl_data_device_manager", 3)
[2667808.476] wl_registry@21.global(7, "zwlr_gamma_control_manager_v1", 1)
[2667808.487] wl_registry@21.global(8, "gtk_primary_selection_device_manager", 1)
[2667808.498] wl_registry@21.global(9, "zxdg_output_manager_v1", 3)
[2667808.511] wl_registry@21.global(10, "org_kde_kwin_idle", 1)
[2667808.523] wl_registry@21.global(11, "zwp_idle_inhibit_manager_v1", 1)
[2667808.536] wl_registry@21.global(12, "zwlr_layer_shell_v1", 2)
[2667808.546] wl_registry@21.global(13, "xdg_wm_base", 2)
[2667808.558] wl_registry@21.global(14, "zwp_tablet_manager_v2", 1)
[2667808.570] wl_registry@21.global(15, "org_kde_kwin_server_decoration_manager", 1)
[2667808.583] wl_registry@21.global(16, "zxdg_decoration_manager_v1", 1)
[2667808.596] wl_registry@21.global(17, "zwp_relative_pointer_manager_v1", 1)
[2667808.607] wl_registry@21.global(18, "zwp_pointer_constraints_v1", 1)
[2667808.617] wl_registry@21.global(19, "wp_presentation", 1)
[2667808.643] wl_registry@21.global(20, "zwlr_output_manager_v1", 2)
[2667808.653] wl_registry@21.global(21, "zwlr_output_power_manager_v1", 1)
[2667808.664] wl_registry@21.global(22, "zwp_input_method_manager_v2", 1)
[2667808.676] wl_registry@21.global(23, "zwp_text_input_manager_v3", 1)
[2667808.690]  -> wl_registry@21.bind(23, "zwp_text_input_manager_v3", 1, new id [unknown]@32)
[2667808.710]  -> zwp_text_input_manager_v3@32.get_text_input(new id zwp_text_input_v3@33, wl_seat@15)
[2667808.722] wl_registry@21.global(24, "zwlr_foreign_toplevel_manager_v1", 3)
[2667808.733] wl_registry@21.global(25, "zwlr_export_dmabuf_manager_v1", 1)
[2667808.746] wl_registry@21.global(26, "zwlr_screencopy_manager_v1", 3)
[2667808.758] wl_registry@21.global(27, "zwlr_data_control_manager_v1", 2)
[2667808.769] wl_registry@21.global(28, "zwp_primary_selection_device_manager_v1", 1)
[2667808.781] wl_registry@21.global(29, "wp_viewporter", 1)
[2667808.792] wl_registry@21.global(30, "zwp_virtual_keyboard_manager_v1", 1)
[2667808.805] wl_registry@21.global(31, "zwlr_virtual_pointer_manager_v1", 2)
[2667808.815] wl_registry@21.global(32, "zwlr_input_inhibit_manager_v1", 1)
[2667808.825] wl_registry@21.global(33, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[2667808.836] wl_registry@21.global(34, "wl_seat", 7)
[2667808.847] wl_registry@21.global(35, "zwp_pointer_gestures_v1", 1)
[2667808.857] wl_registry@21.global(36, "wl_output", 3)
[2667808.884] xdg_wm_base@25.ping(2409)
[2667808.891]  -> xdg_wm_base@25.pong(2409)
[2667808.897] org_kde_kwin_server_decoration@31.mode(2)
[2667808.903] xdg_toplevel@30.configure(0, 0, array)
[2667808.916] xdg_surface@29.configure(2408)
[2667808.923]  -> wl_surface@28.set_buffer_scale(1)
[2667808.939]  -> xdg_surface@29.ack_configure(2408)
[2667811.119]  -> wl_shm@4.create_pool(new id wl_shm_pool@34, fd 17, 585168)
[2667811.164]  -> wl_shm_pool@34.create_buffer(new id wl_buffer@35, 0, 876, 167, 3504, 0)

(polkit-gnome-authentication-agent-1:4360): Gtk-WARNING **: 11:36:09.482: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
[2667820.772]  -> wl_surface@28.attach(wl_buffer@35, 0, 0)
[2667820.784]  -> wl_surface@28.set_buffer_scale(1)
[2667820.806]  -> wl_surface@28.damage(0, 0, 876, 167)
[2667820.834]  -> xdg_toplevel@30.set_min_size(876, 167)
[2667820.842]  -> xdg_toplevel@30.set_max_size(876, 167)
[2667820.849]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 167)
[2667820.874]  -> wl_compositor@6.create_region(new id wl_region@36)
[2667820.900]  -> wl_region@36.add(0, 0, 876, 167)
[2667820.911]  -> wl_surface@28.set_opaque_region(wl_region@36)
[2667820.918]  -> wl_region@36.destroy()
[2667820.923]  -> wl_surface@28.set_input_region(nil)
[2667820.935]  -> wl_surface@28.frame(new id wl_callback@37)
[2667820.956]  -> wl_surface@28.commit()
[2667821.899] wl_display@1.delete_id(36)
[2667821.911] wl_display@1.delete_id(37)
[2667821.918] wl_buffer@35.release()
[2667821.922] wl_keyboard@27.enter(2413, wl_surface@28, array)
[2667821.974] wl_keyboard@27.modifiers(2414, 0, 0, 0, 0)
[2667821.998] wl_data_device@18.data_offer(new id wl_data_offer@1816504752)
[2667822.026] wl_data_offer@4278190080.offer("image/png")
[2667822.051] wl_data_device@18.selection(wl_data_offer@4278190080)
[2667822.062] gtk_primary_selection_device@17.data_offer(new id gtk_primary_selection_offer@1816504848)
[2667822.072] gtk_primary_selection_offer@4278190081.offer("UTF8_STRING")
[2667822.077] gtk_primary_selection_offer@4278190081.offer("COMPOUND_TEXT")
[2667822.083] gtk_primary_selection_offer@4278190081.offer("TEXT")
[2667822.090] gtk_primary_selection_offer@4278190081.offer("STRING")
[2667822.096] gtk_primary_selection_offer@4278190081.offer("text/plain;charset=utf-8")
[2667822.101] gtk_primary_selection_offer@4278190081.offer("text/plain")
[2667822.106] gtk_primary_selection_device@17.selection(gtk_primary_selection_offer@4278190081)
[2667822.113] wl_callback@37.done(780248)
[2667822.123] xdg_toplevel@30.configure(876, 167, array)
[2667822.137] xdg_surface@29.configure(2412)
[2667822.146]  -> xdg_surface@29.ack_configure(2412)
[2667823.864]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667823.879]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667823.907]  -> wl_buffer@35.destroy()
[2667823.910]  -> wl_shm_pool@34.destroy()
[2667823.956]  -> wl_surface@28.set_buffer_scale(1)
[2667824.500]  -> wl_shm@4.create_pool(new id wl_shm_pool@37, fd 17, 704304)
[2667824.534]  -> wl_shm_pool@37.create_buffer(new id wl_buffer@36, 0, 876, 201, 3504, 0)
[2667825.958]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667825.978]  -> wl_surface@28.set_buffer_scale(1)
[2667826.002]  -> wl_surface@28.damage(0, 0, 876, 201)
[2667826.009]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667826.014]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667826.018]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667826.049]  -> wl_compositor@6.create_region(new id wl_region@38)
[2667826.053]  -> wl_region@38.add(0, 0, 876, 201)
[2667826.062]  -> wl_surface@28.set_opaque_region(wl_region@38)
[2667826.066]  -> wl_region@38.destroy()
[2667826.069]  -> wl_surface@28.set_input_region(nil)
[2667826.081]  -> wl_surface@28.frame(new id wl_callback@39)
[2667826.087]  -> wl_surface@28.commit()
[2667827.424] wl_display@1.delete_id(35)
[2667827.436] wl_display@1.delete_id(34)
[2667827.440] wl_display@1.delete_id(38)
[2667827.465] wl_buffer@36.release()
[2667827.469] wl_surface@28.enter(wl_output@23)
[2667828.764] wl_display@1.delete_id(39)
[2667828.773] wl_callback@39.done(780255)
[2667829.256]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667829.286]  -> wl_surface@28.set_buffer_scale(1)
[2667829.290]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667829.318]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667829.322]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667829.327]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667829.342]  -> wl_surface@28.frame(new id wl_callback@39)
[2667829.346]  -> wl_surface@28.commit()
[2667829.624] wl_buffer@36.release()
[2667845.470] wl_display@1.delete_id(39)
[2667845.486] wl_callback@39.done(780272)
[2667845.988]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667846.019]  -> wl_surface@28.set_buffer_scale(1)
[2667846.023]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667846.051]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667846.058]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667846.064]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667846.079]  -> wl_surface@28.frame(new id wl_callback@39)
[2667846.083]  -> wl_surface@28.commit()
[2667846.384] wl_buffer@36.release()
[2667862.396] wl_display@1.delete_id(39)
[2667862.413] wl_callback@39.done(780289)
[2667862.961]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667862.979]  -> wl_surface@28.set_buffer_scale(1)
[2667862.983]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667862.991]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667862.995]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667863.000]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667863.013]  -> wl_surface@28.frame(new id wl_callback@39)
[2667863.020]  -> wl_surface@28.commit()
[2667863.242] wl_buffer@36.release()
[2667878.849] wl_display@1.delete_id(39)
[2667878.873] wl_callback@39.done(780305)
[2667879.569]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667879.588]  -> wl_surface@28.set_buffer_scale(1)
[2667879.594]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667879.605]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667879.611]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667879.618]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667879.639]  -> wl_surface@28.frame(new id wl_callback@39)
[2667879.646]  -> wl_surface@28.commit()
[2667879.905] wl_buffer@36.release()
[2667895.813] wl_display@1.delete_id(39)
[2667895.849] wl_callback@39.done(780322)
[2667897.046]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667897.085]  -> wl_surface@28.set_buffer_scale(1)
[2667897.096]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667897.114]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667897.127]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667897.141]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667897.180]  -> wl_surface@28.frame(new id wl_callback@39)
[2667897.212]  -> wl_surface@28.commit()
[2667897.634] wl_buffer@36.release()
[2667912.342] wl_display@1.delete_id(39)
[2667912.386] wl_callback@39.done(780339)
[2667913.746]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667913.787]  -> wl_surface@28.set_buffer_scale(1)
[2667913.799]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667913.826]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667913.845]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667913.860]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667913.910]  -> wl_surface@28.frame(new id wl_callback@39)
[2667913.925]  -> wl_surface@28.commit()
[2667914.396] wl_buffer@36.release()
[2667929.230] wl_display@1.delete_id(39)
[2667929.276] wl_callback@39.done(780356)
[2667930.784]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667930.831]  -> wl_surface@28.set_buffer_scale(1)
[2667930.844]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667930.871]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667930.893]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667930.910]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667930.955]  -> wl_surface@28.frame(new id wl_callback@39)
[2667930.973]  -> wl_surface@28.commit()
[2667931.430] wl_buffer@36.release()
[2667945.708] wl_display@1.delete_id(39)
[2667945.753] wl_callback@39.done(780372)
[2667947.228]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667947.271]  -> wl_surface@28.set_buffer_scale(1)
[2667947.285]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667947.308]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667947.335]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667947.355]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667947.406]  -> wl_surface@28.frame(new id wl_callback@39)
[2667947.424]  -> wl_surface@28.commit()
[2667948.833] wl_buffer@36.release()
[2667963.204] wl_display@1.delete_id(39)
[2667963.246] wl_callback@39.done(780390)
[2667964.751]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667964.795]  -> wl_surface@28.set_buffer_scale(1)
[2667964.809]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667964.838]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667964.858]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667964.880]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667964.923]  -> wl_surface@28.frame(new id wl_callback@39)
[2667964.943]  -> wl_surface@28.commit()
[2667966.817] wl_buffer@36.release()
[2667979.061] wl_display@1.delete_id(39)
[2667979.107] wl_callback@39.done(780405)
[2667980.596]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667980.641]  -> wl_surface@28.set_buffer_scale(1)
[2667980.654]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667980.678]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667980.698]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667980.718]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667980.777]  -> wl_surface@28.frame(new id wl_callback@39)
[2667980.794]  -> wl_surface@28.commit()
[2667981.933] wl_buffer@36.release()
[2667995.931] wl_display@1.delete_id(39)
[2667995.976] wl_callback@39.done(780422)
[2667997.483]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667997.530]  -> wl_surface@28.set_buffer_scale(1)
[2667997.543]  -> wl_surface@28.damage(152, 73, 712, 34)
[2667997.571]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667997.594]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667997.615]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667997.675]  -> wl_surface@28.frame(new id wl_callback@39)
[2667997.700]  -> wl_surface@28.commit()
[2667998.170] wl_buffer@36.release()
[2668013.191] wl_display@1.delete_id(39)
[2668013.234] wl_callback@39.done(780440)
[2668014.875]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2668014.921]  -> wl_surface@28.set_buffer_scale(1)
[2668014.933]  -> wl_surface@28.damage(152, 73, 712, 34)
[2668014.955]  -> xdg_toplevel@30.set_min_size(876, 201)
[2668014.968]  -> xdg_toplevel@30.set_max_size(876, 201)
[2668014.989]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2668015.032]  -> wl_surface@28.frame(new id wl_callback@39)
[2668015.050]  -> wl_surface@28.commit()
[2668015.491] wl_buffer@36.release()
[2668029.286] wl_display@1.delete_id(39)
[2668029.329] wl_callback@39.done(780456)
[2668030.665]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2668030.708]  -> wl_surface@28.set_buffer_scale(1)
[2668030.720]  -> wl_surface@28.damage(152, 73, 712, 34)
[2668030.746]  -> xdg_toplevel@30.set_min_size(876, 201)
[2668030.762]  -> xdg_toplevel@30.set_max_size(876, 201)
[2668030.781]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2668030.824]  -> wl_surface@28.frame(new id wl_callback@39)
[2668030.839]  -> wl_surface@28.commit()
[2668031.344] wl_buffer@36.release()
[2668046.259] wl_display@1.delete_id(39)
[2668046.305] wl_callback@39.done(780473)
[2668338.239] wl_keyboard@27.key(2415, 780764, 125, 1)
[2668338.340] wl_keyboard@27.modifiers(2416, 64, 0, 0, 0)
[2668475.709] wl_keyboard@27.key(2417, 780902, 42, 1)
[2668475.795] wl_keyboard@27.modifiers(2418, 65, 0, 0, 0)
[2668649.897] xdg_toplevel@30.close()
[2668651.852]  -> xdg_toplevel@30.destroy()
[2668651.887]  -> xdg_surface@29.destroy()
[2668651.913]  -> org_kde_kwin_server_decoration@31.release()
[2668651.930]  -> wl_surface@28.destroy()
[2668651.952]  -> wl_buffer@36.destroy()
[2668651.968]  -> wl_shm_pool@37.destroy()
[2668656.442] wl_display@1.delete_id(30)
[2668656.489] wl_display@1.delete_id(29)
[2668656.508] wl_display@1.delete_id(31)
[2668656.530] wl_display@1.delete_id(28)
[2668656.553] wl_display@1.delete_id(36)
[2668656.574] wl_display@1.delete_id(37)
[2668656.599] wl_keyboard@27.leave(2419, nil)
```
</details>

I believe the relevant lines are:

```
[2667811.119]  -> wl_shm@4.create_pool(new id wl_shm_pool@34, fd 17, 585168)
[2667811.164]  -> wl_shm_pool@34.create_buffer(new id wl_buffer@35, 0, 876, 167, 3504, 0)
[2667820.772]  -> wl_surface@28.attach(wl_buffer@35, 0, 0)
[2667820.834]  -> xdg_toplevel@30.set_min_size(876, 167)
[2667820.842]  -> xdg_toplevel@30.set_max_size(876, 167)
[2667820.849]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 167)
[2667820.956]  -> wl_surface@28.commit()
[...]
[2667822.123] xdg_toplevel@30.configure(876, 167, array)
[2667822.137] xdg_surface@29.configure(2412)
[2667822.146]  -> xdg_surface@29.ack_configure(2412)
[2667823.864]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667823.879]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667824.500]  -> wl_shm@4.create_pool(new id wl_shm_pool@37, fd 17, 704304)
[2667824.534]  -> wl_shm_pool@37.create_buffer(new id wl_buffer@36, 0, 876, 201, 3504, 0)
[2667825.958]  -> wl_surface@28.attach(wl_buffer@36, 0, 0)
[2667826.009]  -> xdg_toplevel@30.set_min_size(876, 201)
[2667826.014]  -> xdg_toplevel@30.set_max_size(876, 201)
[2667826.018]  -> xdg_surface@29.set_window_geometry(0, 0, 876, 201)
[2667826.087]  -> wl_surface@28.commit()
```

The agent at first submits a buffer at height=167 then changes its mind and submits again at 201. There are no further configure events. If you attempt an interactive resize on the window (not reproduced in the above logs), it will not be resized (fine since min_size==max_size means it is fixed size), but it will correct the window border to encompass the whole drawn surface.

### PR DESCRIPTION
**Pull request by RPigott**
Fixes #5750.

Currently, when sway sends a configure with some geometry and the client responds with a different geometry in a commit that acks that configure, sway ignores the new size. Sway applies the surface geometry it had requested to the container, not what was actually committed, in the following transaction.

This change allows any client commit to change its surface geometry, even if it is a response to a configure event.

### CODE REVIEW

File: sway/desktop/xdg_shell.c [hunk 1]
```diff
@@ -284,28 +284,23 @@ static void handle_commit(struct wl_listener *listener, void *data) {
...
+				new_geo.height != view->geometry.height ||
+				new_geo.x != view->geometry.x ||
+				new_geo.y != view->geometry.y)) {
+		// The view has unexpectedly sent a new size
+		desktop_damage_view(view);
+		view_update_size(view, new_geo.width, new_geo.height);
+		memcpy(&view->geometry, &new_geo, sizeof(struct wlr_box));
+		desktop_damage_view(view);
+		transaction_commit_dirty();
+		transaction_notify_view_ready_immediately(view);
```
Comment (emersion) [inline sway/desktop/xdg_shell.c:300]: I think we should still `transaction_notify_view_ready_by_serial` if we have a serial.

Comment (RPigott) [reply sway/desktop/xdg_shell.c]: Oh, you're totally right. I was temporarily confused about how the transaction queue worked.

**Comment by Dudemanguy** [comment]
I think this might also fix https://github.com/swaywm/sway/issues/3029? Not totally sure. Nice job, I was actually coming up with a similar fix myself but you beat me to it.

**Review by emersion — APPROVED** [review]
LGTM and works, thanks!

**Comment by kennylevinsen** [comment]
This PR unfortunately breaks atomic resizing of tiles as originally fixed in https://github.com/swaywm/sway/pull/5403, as we cannot update view/container sizes before an atomic transaction completes (or times out).

The problem can be observed by running slow-ack-configure from https://github.com/emersion/wleird tiled with something like foot/alacritty, and then resizing them, with and without this PR.

**Comment by RPigott** [comment]
I tried termite + slow-ack on master, master w/ this reverted and I also tried f8dd7df, but tbh I couldn't see a difference. The tiling resize performce w/ slow-ack seemed equally bad on all three.

I'll have some more time to look into this post-holidays if it isn't addressed in the next few days.

**Comment by kennylevinsen** [comment]
Test is foot and slow-ack-configure side by side, resizing their split fast/in large movements with the mouse.

- https://github.com/swaywm/sway/commit/f1afef5533cac9c5d03e5fb372226e48ac1d8547: foot's content and border is always in sync during resize.
- https://github.com/swaywm/sway/commit/32b93ef6ea394a8f0c564d4bded2806c7b595696: foot's content resizes immediately while the border waits for the transaction, leading to mismatch in size for many frames. This is caused by setting the view geometry before the transaction completed.

I believe what we needed before might have been a means to see if the ready transaction also matched the instructed size. If not we should issue a new transaction. I'll try to find time to look at it.

**Comment by RPigott** [comment]
Ah, I see what you mean now.

**Comment by emersion** [comment]
Created https://github.com/swaywm/sway/issues/5848 to keep track of this issue.
