### PR TITLE
view: display scratchpad hidden containers when activated by ftm

### LINKED ISSUE #5572: Fatal crash in scratchpad show with foreign_toplevel_management
```
$ swaymsg -t get_version
sway version 1.5-4f718e6c (Jul 23 2020, branch 'master')
```

So I'm working on a foreign toplevel management client and ran into this crash while testing. FTM can focus scratchpad hidden views without mapping them, which is definitely a no-no. Trying to `scratchpad show` after that kills sway.

Here's the backtrace. It's late where I live but I can try fixing it tomorrow.

<details>
<summary>bt full</summary>

```
#0  0x000055a2585ad9ae in arrange_workspace (workspace=0x0) at ../sway/sway/tree/arrange.c:253
        output = <optimized out>
        area = <optimized out>
        first_arrange = <optimized out>
        prev_x = <optimized out>
        prev_y = <optimized out>
        diff_x = <optimized out>
        diff_y = <optimized out>
#1  0x000055a2585ade85 in arrange_workspace (workspace=<optimized out>) at ../sway/sway/tree/arrange.c:254
#2  0x000055a2585b350c in root_scratchpad_hide (con=0x55a259c558c0) at ../sway/sway/tree/root.c:177
        seat = 0x55a2595b4650
        focus = 0x55a25986ca70
        ws = 0x0
#3  0x000055a2585a31c9 in scratchpad_toggle_auto () at ../sway/sway/commands/scratchpad.c:34
        seat = <optimized out>
        focus = <optimized out>
        ws = <optimized out>
        con = <optimized out>
        __PRETTY_FUNCTION__ = "scratchpad_toggle_auto"
        error = <optimized out>
#4  cmd_scratchpad (argc=<optimized out>, argv=<optimized out>) at ../sway/sway/commands/scratchpad.c:127
        error = <optimized out>
#5  0x000055a2585704b9 in execute_command (_exec=<optimized out>, seat=seat@entry=0x55a2595b4650, con=0x0) at ../sway/sway/commands.c:286
        node = <optimized out>
        res = <optimized out>
        argc = 2
        argv = 0x55a2596dc390
        handler = 0x55a2585df120 <command_handlers+256>
        cmd = <optimized out>
        matched_delim = 0 '\000'
        containers = 0x0
        __PRETTY_FUNCTION__ = "execute_command"
        exec = 0x55a25985e680 "scratchpad show"
        head = 0x0
        res_list = 0x55a25978d090
#6  0x000055a258599af7 in seat_execute_command (seat=seat@entry=0x55a2595b4650, binding=0x55a2595ebcb0) at ../sway/sway/commands/bind.c:630
        con = <optimized out>
        res_list = <optimized out>
        success = <optimized out>
#7  0x000055a258589ade in handle_key_event (keyboard=0x55a2596362f0, event=0x7ffeb88c4dc0) at ../sway/sway/input/keyboard.c:465
        seat = 0x55a2595b4650
        wlr_seat = 0x55a2595b4830
        wlr_device = 0x55a259623c80
        device_identifier = 0x55a259bf9a30 "0:0:"
        exact_identifier = false
        input_inhibited = false
        sway_inhibitor = <optimized out>
        shortcuts_inhibited = false
        keyinfo = 
          {keycode = 20, code_modifiers = 64, raw_keysyms = 0x55a259637ed8, raw_modifiers = 64, raw_keysyms_len = 1, translated_keysyms = 0x55a259637ed8, translated_modifiers = 64, translated_keysyms_len = 1}
        handled = <optimized out>
        binding_released = 0x0
        binding = 0x55a2595ebcb0
#8  0x00007f1c0467b60e in  () at /usr/lib/libwlroots.so.6
#9  0x00007f1c046656d2 in wlr_keyboard_notify_key () at /usr/lib/libwlroots.so.6
#10 0x00007f1c0467b60e in  () at /usr/lib/libwlroots.so.6
#11 0x00007f1c046656d2 in wlr_keyboard_notify_key () at /usr/lib/libwlroots.so.6
#12 0x00007f1c0463f007 in  () at /usr/lib/libwlroots.so.6
#13 0x00007f1c0463df2c in  () at /usr/lib/libwlroots.so.6
#14 0x00007f1c046cbfaa in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#15 0x00007f1c046ca4e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#16 0x000055a25856f5c0 in main (argc=1, argv=0x7ffeb88c51b8) at ../sway/sway/main.c:410
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55a2585c045b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55a2585c3e09 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55a2585c0460 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55a2585c0469 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55a2585c03bf "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55a2585bf543 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55a2585c046f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55a2585c047e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55a2585c048e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55a2585c0800 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```
</details>

### PR DESCRIPTION
**Pull request by RPigott**
Fix #5572 by showing scratchpad hidden containers when they are activated by ftm.

### CODE REVIEW

File: sway/tree/view.c [hunk 1]
```diff
@@ -625,6 +625,9 @@ static void handle_foreign_activate_request(
 	struct sway_seat *seat;
 	wl_list_for_each(seat, &server.input->seats, link) {
 		if (seat->wlr_seat == event->seat) {
+			if (container_is_scratchpad_hidden_or_child(view->container)) {
```
Comment (RedSoxFan) [inline sway/tree/view.c:628]: Since this is being edit anyway, do you mind adding the following:
```c
seat_consider_warp_to_focus(seat);
container_raise_floating(view->container);
```

So that this block matches the one in `cmd_focus`:
https://github.com/swaywm/sway/blob/4f718e6c75d2168d417b4b41c0e3d5408e0afded/sway/commands/focus.c#L368-L373

Comment (RPigott) [reply sway/tree/view.c:628]: Sounds good. Done.

**Comment by RedSoxFan** [comment]
Thanks!
