### PR TITLE
Fix swaybar teardown when workspace buttons hidden

### LINKED ISSUE #2213: Hiding workspace buttons hides the whole bar
Setting `workspace_buttons no` for a bar causes the entire bar to be hidden

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #2213

When workspace buttons are hidden, `wl_display_dispatch` was returning `-1` with `errno = 71`. Running `swaybar` with `WAYLAND_DEBUG=1` gave `wl_shm@4: error 1: invalid size (0)`. `max_height`was `0` on the first frame render due to the status line not being read yet.

~This PR prevents `max_height` from being `0`.~ This PR prevents rendering the bar if the `height` is not greater than `0`

### CODE REVIEW

File: swaybar/render.c [hunk 1]
```diff
@@ -435,7 +435,7 @@ static uint32_t render_to_cairo(cairo_t *cairo,
 	}
 	cairo_paint(cairo);
 
-	uint32_t max_height = 0;
+	uint32_t max_height = 1;
```
Comment (emersion) [inline swaybar/render.c]: Hmm, this should be already handled by line 488?

Comment (RedSoxFan) [reply swaybar/render.c]: I added a debug line before line 488 and got `bar->config->height = -1`. In `sway/config/bar.c`, there is `bar->height = -1` (line 82), which is passed across the IPC. Unless `bar <bar-id> height <height>` is set in the config, `bar->config->height` will start off at `-1` and line 488 will not force a positive height. I could change `sway/config/bar.c:82` to `bar->height = 1` instead, if that would be preferred.

**Comment by emersion** [comment]
Thanks!
